src/com/projectkorra/ProjectKorra/Utilities/ParticleEffect.java, src/com/projectkorra/ProjectKorra/Utilities/ReflectionHandler.java
Updated both the ParticleEffect and the ReflectionHandler to support 1.8 and added the required code so it would also support the old methods used.
=> ParticleLibrary update to v1.6

.classpath, src/com/projectkorra/ProjectKorra/Utilities/ParticleEffect.java, src/com/projectkorra/ProjectKorra/firebending/Lightning.java
ParticleEffect method can now be used to create specifically colored
RED_DUST particles using hexadecimal color values.
Changed Lightning particles to be light cyan RED_DUST particles.
=> Added color RED_DUST particle functionality and Lightning particle change

src/com/projectkorra/ProjectKorra/Methods.java, src/com/projectkorra/ProjectKorra/PKListener.java, src/com/projectkorra/ProjectKorra/ProjectKorra.java, src/com/projectkorra/ProjectKorra/RevertChecker.java, src/com/projectkorra/ProjectKorra/Storage/Database.java, src/com/projectkorra/ProjectKorra/Utilities/AbilityLoader.java, src/com/projectkorra/ProjectKorra/Utilities/ParticleEffect.java
* Removed unused imports
* Prevented Memory Leak by adding close()
* Used new try-with-resource method from java 1.7
* Corrected javadoc spacing
=> Cleanup/Memory Leak Fix

src/com/projectkorra/ProjectKorra/Commands.java, src/com/projectkorra/ProjectKorra/ConfigManager.java, src/com/projectkorra/ProjectKorra/chiblocking/ChiComboManager.java, src/com/projectkorra/ProjectKorra/chiblocking/QuickStrike.java, src/com/projectkorra/ProjectKorra/chiblocking/SwiftKick.java, src/plugin.yml
Added configuration entries for ChiCombo.
Added Help Message for ChiCombo.
Implemented configuration variables in SwiftKick & QuickStrike.
Added new abilities into plugin.yml.
Made jumping mandatory for SwiftKick.
=> Added missing things to ChiCombos

src/com/projectkorra/ProjectKorra/DBConnection.java, src/com/projectkorra/ProjectKorra/Methods.java, src/com/projectkorra/ProjectKorra/ProjectKorra.java, src/com/projectkorra/ProjectKorra/Storage/MySQL.java, src/com/projectkorra/ProjectKorra/Storage/SQLite.java, src/com/projectkorra/ProjectKorra/firebending/FireStream.java
* Added Material.THIN_GRASS to overwriteable Materials
* Added Material.LEAVES_2 to igniteable
* Update the removed deprecated WG method with an up to date method (source:sk89q himself)
Small Database rework
* Added stopPlugin() method
* Forced plugin to stop while enabling sql database if an error was found
* Prevents a broken database ProjectKorra from continuing to work with horrible errors
=> Update Database, FireStream and Deprecated WG method

src/com/projectkorra/ProjectKorra/firebending/FireBurst.java, src/com/projectkorra/ProjectKorra/firebending/Lightning.java
* Applied checks to prevent a NPE in FireBurst and Lightning
=> Fix NPE found in FireBurst and Lightning

src/com/projectkorra/ProjectKorra/Ability/AvatarState.java, src/com/projectkorra/ProjectKorra/BendingPlayer.java, src/com/projectkorra/ProjectKorra/CustomEvents/PlayerCooldownChangeEvent.java
AvatarState Cooldown Modifications:
- Converted the AvatarState to use the same BPlayer cooldown manager as
all the other abilities
CooldownChangeEvent Modifications:
- Make cooldown changes cancellable so as to increase API functionality
=> Cooldown Modifications

.classpath, src/com/projectkorra/ProjectKorra/Commands.java, src/com/projectkorra/ProjectKorra/Methods.java, src/com/projectkorra/ProjectKorra/firebending/Lightning.java
Fixes:
Recalibrated Colored Particles to 1.8.3 (fixing lightning)
Moved OmniCypher to Dev list (finally)
Additions:
playLightningParticles():
Callable method in Methods class for dev's to easily display Lightning
Particles.
Signature:
(Location loc, float xOffset, float yOffset, float zOffset)
displayColoredParticle():
Callable method in Methods class to easily create and display and passed
in hexadecimal RGB value. Handles multiple particle types. String hexVal does not require a "#" (Ex:   "#FFFFFF" = "FFFFFF")
Signature:
(Location loc, ParticleEffect type, String hexVal, float xOffset, float yOffset, float zOffset)
displayParticleVector():
Callable method in Methods class to easily create and display particles
which will smoothly translate to relative coordinates over time. Handles …
=> Fixes and Additions

src/com/projectkorra/ProjectKorra/airbending/Tornado.java, src/com/projectkorra/ProjectKorra/earthbending/EarthPassive.java, src/com/projectkorra/ProjectKorra/earthbending/EarthTunnel.java, src/com/projectkorra/ProjectKorra/earthbending/Extraction.java, src/com/projectkorra/ProjectKorra/earthbending/LavaWall.java, src/com/projectkorra/ProjectKorra/firebending/Extinguish.java, src/com/projectkorra/ProjectKorra/waterbending/IceSpike.java, src/com/projectkorra/ProjectKorra/waterbending/Melt.java, src/com/projectkorra/ProjectKorra/waterbending/WaterManipulation.java, src/com/projectkorra/ProjectKorra/waterbending/WaterSourceGrabber.java, src/com/projectkorra/ProjectKorra/waterbending/WaterWall.java, src/com/projectkorra/ProjectKorra/waterbending/WaterWave.java
Fixing ambiguity problem for spigot 1.8.3
=> Update to 1.8.3 method for getTargetBlock

src/com/projectkorra/ProjectKorra/Methods.java, src/com/projectkorra/ProjectKorra/PKListener.java
* Add Saving Toggle: http://projectkorra.com/forum/threads/saving-toggle.839/
* toggledOut is reset on stop/reload
* Sends player "Reminder, you toggled your bending before signing off. Enable it again with /bending toggle" upon login
=> Implement Saving Toggle

src/com/projectkorra/ProjectKorra/Commands.java, src/com/projectkorra/ProjectKorra/firebending/Lightning.java
- Added kewl lightning charge up animation
- Small code cleanup in Commands.java
=> Lightning Aesthetic Enhancement

src/com/projectkorra/ProjectKorra/firebending/Lightning.java
Gave external developers a way to get the arcs from lightning
=> Allowed external developers access to arcs

src/com/projectkorra/ProjectKorra/ComboManager.java, src/com/projectkorra/ProjectKorra/airbending/AirCombo.java, src/com/projectkorra/ProjectKorra/firebending/FireCombo.java, src/com/projectkorra/ProjectKorra/waterbending/WaterCombo.java, src/plugin.yml
Combo Permissions:
- FireCombo/AirCombo/WaterCombo and any custom combo abilities can now be enabled and disabled with permissions.
- The permission format is "bending.ability.ComboName", for example, "bending.ability.FireSpin", "bending.ability.AirSweep", "bending.ability.IceBullet"
- Previously "bending.ability.AirCombo" was used to govern all of the AirCombos, now that permission directly grants each individual AirCombo Permission. This also applies to FireCombo and WaterCombo.
- If you add a custom combo you must also add the correct combo permission. Custom combo permissions are not granted to non OP players by default.
- Current Combos: AirSweep, AirStream, Tornado, FireKick, FireSpin, JetBlast, JetBlast, FireWheel, IceBullet, IceWave
=> Combo Permissions

src/com/projectkorra/ProjectKorra/Ability/AbilityModuleManager.java, src/com/projectkorra/ProjectKorra/BendingManager.java, src/com/projectkorra/ProjectKorra/Commands.java, src/com/projectkorra/ProjectKorra/GeneralMethods.java, src/com/projectkorra/ProjectKorra/MetricsLite.java, src/com/projectkorra/ProjectKorra/Objects/Preset.java, src/com/projectkorra/ProjectKorra/PKListener.java, src/com/projectkorra/ProjectKorra/ProjectKorra.java, src/com/projectkorra/ProjectKorra/RevertChecker.java, src/com/projectkorra/ProjectKorra/Storage/Database.java, src/com/projectkorra/ProjectKorra/Storage/MySQL.java, src/com/projectkorra/ProjectKorra/Utilities/AbilityLoadable.java, src/com/projectkorra/ProjectKorra/Utilities/AbilityLoader.java, src/com/projectkorra/ProjectKorra/airbending/AirbendingManager.java, src/com/projectkorra/ProjectKorra/chiblocking/ChiblockingManager.java, src/com/projectkorra/ProjectKorra/earthbending/EarthbendingManager.java, src/com/projectkorra/ProjectKorra/firebending/FirebendingManager.java, src/com/projectkorra/ProjectKorra/waterbending/WaterbendingManager.java
* Add errorLog method to log throwables/exceptions 
* Add methods errorLog(Throwable) and errorLog(Throwable, Boolean) to
GeneralMethods.java
* Add documentation to both methods describing how to use them
* Add exception handler into Ability Managers
* This allows ProjectKorra to handle unexpected errors caused by abilities and logs them
* This is also done for custom abilities in commit 4d3ce66
* Update related classes to use errorLog method
=> Add ERROR.log and related logging methods and updated relevant classes

src/com/projectkorra/ProjectKorra/PKListener.java
* Fixes bending breaking in BETA 4 due to b20c543
=> [URGENT] Fix bending not working due to b20c543

src/com/projectkorra/ProjectKorra/Utilities/BlockSource.java
WaterBottle Fix:
- Fixed a bug caused by dynamic source selection that broke bending from Waterbottles.
=> Fixed WaterBottles after dynamic sourcing broke them

src/com/projectkorra/ProjectKorra/MultiAbilityManager.java, src/com/projectkorra/ProjectKorra/PKListener.java
Fixed the issue that caused MultiAbilities to spam the console if a player logged out while one was active.
Fixed the issue with WaterArms where the ability couldn't be used if the player wasn't opped.
=> Fixed MultiAbility spam and WaterArms non OP glitch.

src/com/projectkorra/ProjectKorra/Commands.java, src/com/projectkorra/ProjectKorra/ProjectKorra.java, src/com/projectkorra/ProjectKorra/Utilities/Updater.java, src/plugin.yml
* Add Updater class that handles updating for PK
* Since all PK plugins require ProjectKorra they can create a new instance of Updater from ProjectKorra without needing to create another Updater class
* Add command /pk check
* Add permission "bending.command.check" support to /pk check
=> Add Updater and /pk check command

src/com/projectkorra/ProjectKorra/ConfigManager.java, src/com/projectkorra/ProjectKorra/waterbending/WaterArmsWhip.java, src/config.yml
Added config options for WaterArms punch range.
Added config option for pull strength.
Weaked the grab strength to be more like bloodbending's strength.
=> Added WaterArms Nerfs

src/com/projectkorra/ProjectKorra/GeneralMethods.java, src/com/projectkorra/ProjectKorra/PKListener.java, src/com/projectkorra/ProjectKorra/configuration/ConfigManager.java
Attempted to fix the wrong Death Message being displayed.
Fixed null pointer exceptions.
Fixed combo messages not being displayed.
=> Death Message Fixes

src/com/projectkorra/ProjectKorra/Commands.java, src/com/projectkorra/ProjectKorra/Utilities/Updater.java
* Change all spellings of "avalible" to "available"
=> Fix spelling of available in Updater

src/com/projectkorra/ProjectKorra/BendingManager.java, src/com/projectkorra/ProjectKorra/BendingPlayer.java, src/com/projectkorra/ProjectKorra/ComboManager.java, src/com/projectkorra/ProjectKorra/Commands.java, src/com/projectkorra/ProjectKorra/Flight.java, src/com/projectkorra/ProjectKorra/GeneralMethods.java, src/com/projectkorra/ProjectKorra/Information.java, src/com/projectkorra/ProjectKorra/MetricsLite.java, src/com/projectkorra/ProjectKorra/MultiAbilityManager.java, src/com/projectkorra/ProjectKorra/PKListener.java, src/com/projectkorra/ProjectKorra/ProjectKorra.java, src/com/projectkorra/ProjectKorra/RevertChecker.java, src/com/projectkorra/ProjectKorra/SubElement.java, src/com/projectkorra/ProjectKorra/TagAPIListener.java, src/com/projectkorra/ProjectKorra/TempBlock.java, src/com/projectkorra/ProjectKorra/TempPotionEffect.java
* Formatted all classes in the package com.projectkorra.ProjectKorra 
* Sub-packages haven't been addressed yet
Format as follows:
* Sort all methods by modifier level then alphabetical
* Structure:
* Fields
* Constructor
* Static methods
* Public, Private, Default, No Modifier Methods
* Nested Class, Enum, Interfaces
* When sorting files and using eclipse:
* Copy to clipboard: Fields, Constructor
* right click > source > sort members > do not sort fields, enum constraints, initializers
* Paste Fields, Constructor 's at the start of the file
* Move nested Class, Enum, Interface to the very bottom of the file
=> [URGENT] Formatted all classes in main package

src/com/projectkorra/ProjectKorra/CustomEvents/BendingReloadEvent.java, src/com/projectkorra/ProjectKorra/GeneralMethods.java, src/com/projectkorra/ProjectKorra/MultiAbilityManager.java
Added new BendingReloadEvent which is fired on the /pk reload command.
Fixed MultiAbilities not getting the correct colors.
=> Bug Fixes and New Event

src/com/projectkorra/ProjectKorra/PKListener.java, src/com/projectkorra/ProjectKorra/airbending/AirSwipe.java, src/plugin.yml
* Fixes NPE caused by @jedk1 's Death messages
* Fix permission typo in AirCombo
=> [BUGFIX] Fix NPE in PKListener, onPlayerDeath when killer was null, Permissions

src/com/projectkorra/ProjectKorra/airbending/AirBlast.java, src/com/projectkorra/ProjectKorra/airbending/AirBurst.java, src/com/projectkorra/ProjectKorra/airbending/AirCombo.java, src/com/projectkorra/ProjectKorra/configuration/ConfigManager.java, src/com/projectkorra/ProjectKorra/earthbending/EarthMethods.java, src/com/projectkorra/ProjectKorra/earthbending/LavaFlow.java, src/com/projectkorra/ProjectKorra/earthbending/LavaWave.java, src/com/projectkorra/ProjectKorra/firebending/FireBlast.java, src/com/projectkorra/ProjectKorra/firebending/FireCombo.java, src/com/projectkorra/ProjectKorra/firebending/FireShield.java, src/com/projectkorra/ProjectKorra/firebending/Fireball.java, src/com/projectkorra/ProjectKorra/firebending/WallOfFire.java
Added a fire tick option for the following abilities:
• FireBlast(Both charged and normal)
• FireWheel and JetBlaze
• FireShield
• WallOfFire
Each ability has it’s own config option for the ticks. The burn time is
in seconds!
Also removed unused imports and removed warnings!
=> FireTicks and cleaning

src/com/projectkorra/ProjectKorra/Flight.java
* Removes reference to player when player is null
* Fixes mistake caused by 2e33659
* Fixes NPE in Flight from revert()
=> [BUGFIX] Actually Fix NPE in Flight revert() from 2e33659

src/com/projectkorra/ProjectKorra/GeneralMethods.java, src/com/projectkorra/ProjectKorra/PKListener.java, src/com/projectkorra/ProjectKorra/Utilities/logging/ErrorLogFilter.java, src/com/projectkorra/ProjectKorra/waterbending/WaterArmsWhip.java
Fixed the null pointer exception caused by death messages.
=> Fixed death null pointer exception bug.

src/com/projectkorra/ProjectKorra/Commands.java
Added some nice little colors and the new names to /b who!
=> Added new peeps to /b who

src/com/projectkorra/ProjectKorra/GeneralMethods.java, src/com/projectkorra/ProjectKorra/Objects/Preset.java
Added a getPresetContents method to return the contents of a preset.
Fixed the particle view range @OmniCypher-
=> New Preset method & Bug Fixes

src/com/projectkorra/ProjectKorra/airbending/AirBlast.java
Readded airblast being able to toggle buttons and levers.
Added more wood door types.
=> AirBlast functionality.

src/com/projectkorra/ProjectKorra/Ability/AbilityModuleManager.java, src/com/projectkorra/ProjectKorra/Ability/StockAbilities.java, src/com/projectkorra/ProjectKorra/PKListener.java, src/com/projectkorra/ProjectKorra/configuration/ConfigManager.java, src/com/projectkorra/ProjectKorra/earthbending/EarthArmor.java, src/com/projectkorra/ProjectKorra/waterbending/HealingWaters.java, src/com/projectkorra/ProjectKorra/waterbending/PlantArmor.java, src/com/projectkorra/ProjectKorra/waterbending/Plantbending.java, src/com/projectkorra/ProjectKorra/waterbending/WaterMethods.java, src/com/projectkorra/ProjectKorra/waterbending/WaterbendingManager.java, src/plugin.yml
**PlantArmor/Related:**
- Add PlantArmor move
- Add playPlantbendingSound(Location loc) in WaterMethods
- Add isPlantbendable(Block block) in WaterMethods
- Add getPlantSourceBlock() in WaterMethods
**EarthArmor:**
- Fix incorrect cooldown configuration
- Properly add cooldown
- Fix EarthArmor + FastSwim bug
=> The Armor Update

src/com/projectkorra/ProjectKorra/ProjectKorra.java, src/com/projectkorra/ProjectKorra/Utilities/logging/LogFilter.java, src/com/projectkorra/ProjectKorra/airbending/AirCombo.java, src/com/projectkorra/ProjectKorra/waterbending/WaterWave.java
* Update error log folder so it generates in the correct folder
* Update LogFilter so it actually filters for "ProjectKorra" instead of "LogTest"
* Fix NPE in WaterWave
* Fix distance location bug in AirCombo
=> [BUGFIX] Fix ErrorLogger, WaterWave, AirCombo

src/com/projectkorra/ProjectKorra/Commands.java, src/com/projectkorra/ProjectKorra/earthbending/EarthBlast.java, src/com/projectkorra/ProjectKorra/earthbending/EarthMethods.java, src/com/projectkorra/ProjectKorra/earthbending/EarthPassive.java, src/com/projectkorra/ProjectKorra/earthbending/EarthSmash.java, src/com/projectkorra/ProjectKorra/waterbending/FreezeMelt.java, src/com/projectkorra/ProjectKorra/waterbending/Torrent.java, src/com/projectkorra/ProjectKorra/waterbending/WaterReturn.java, src/com/projectkorra/ProjectKorra/waterbending/WaterWall.java, src/com/projectkorra/ProjectKorra/waterbending/Wave.java
Fixes various bugs with bottlebending
Colored Sandstone/Sand are compatible with earthbending (RED_SANDSTONE needs to be added to earthbendables in config still)
Fixed Cooldown in Earthsmash
Fixed Desc in PhaseChange
Fixed Dark Green in /b who
=> Bottlebending & Sandstone

src/com/projectkorra/ProjectKorra/BendingManager.java, src/com/projectkorra/ProjectKorra/configuration/ConfigManager.java
- Changed defaults to be balanced.
- Added configurable event messages.
- Added configurable day & night messages.
=> Balance Patch // Event Messages Configurable // Day & Night Messages

src/com/projectkorra/ProjectKorra/Ability/Ability.java, src/com/projectkorra/ProjectKorra/Ability/AbilityModule.java, src/com/projectkorra/ProjectKorra/Ability/AbilityModuleManager.java, src/com/projectkorra/ProjectKorra/Ability/BaseAbility.java, src/com/projectkorra/ProjectKorra/Ability/StockAbilities.java, src/com/projectkorra/ProjectKorra/BendingManager.java, src/com/projectkorra/ProjectKorra/BendingPlayer.java, src/com/projectkorra/ProjectKorra/Commands.java, src/com/projectkorra/ProjectKorra/GeneralMethods.java, src/com/projectkorra/ProjectKorra/PKListener.java, src/com/projectkorra/ProjectKorra/ProjectKorra.java, src/com/projectkorra/ProjectKorra/airbending/AirBlast.java, src/com/projectkorra/ProjectKorra/airbending/AirBubble.java, src/com/projectkorra/ProjectKorra/airbending/AirBurst.java, src/com/projectkorra/ProjectKorra/airbending/AirCombo.java, src/com/projectkorra/ProjectKorra/airbending/AirMethods.java, src/com/projectkorra/ProjectKorra/airbending/AirPassive.java, src/com/projectkorra/ProjectKorra/airbending/AirScooter.java, src/com/projectkorra/ProjectKorra/airbending/AirShield.java, src/com/projectkorra/ProjectKorra/airbending/AirSpout.java, src/com/projectkorra/ProjectKorra/airbending/AirSuction.java, src/com/projectkorra/ProjectKorra/airbending/AirSwipe.java, src/com/projectkorra/ProjectKorra/airbending/AirbendingManager.java, src/com/projectkorra/ProjectKorra/airbending/FlightAbility.java, src/com/projectkorra/ProjectKorra/airbending/Suffocate.java, src/com/projectkorra/ProjectKorra/airbending/Tornado.java, src/com/projectkorra/ProjectKorra/configuration/Config.java, src/com/projectkorra/ProjectKorra/configuration/ConfigLoadable.java, src/com/projectkorra/ProjectKorra/configuration/ConfigManager.java, src/com/projectkorra/ProjectKorra/earthbending/Tremorsense.java
New:  
* Introduced Ability, BaseAbility, ConfigLoadable
* Ability extends ConfigLoadable
* BaseAbility implements Ability
* All abilities should extends BaseAbility
Changes:
* Fomatted AbilityModule 
* Format StockAbilities, Update getAbility()
* All Air Abilities now extends BaseAbility have implemented all missing methods
* Update BendingManager:
* BendingManager now implements ConfigLoadable
* Unused plugin reference is removed
* Add BendingManager instance variable and getter
* Change config messages to not be final and made them reloadable with reloadVariables() from ConfigLoadable
=> [Bleeding] New Ability System, Air implemented

src/com/projectkorra/ProjectKorra/airbending/AirbendingManager.java, src/com/projectkorra/ProjectKorra/firebending/FireBlast.java
* Fixes issue where FireBurst wouldn't work
* Changing AirbendingManager to use new class system
=> Attempt to fix new system

src/com/projectkorra/projectkorra/ability/api/CoreAbility.java, src/com/projectkorra/projectkorra/airbending/AirShield.java, src/com/projectkorra/projectkorra/firebending/FireJet.java, src/com/projectkorra/projectkorra/firebending/Illumination.java
* Update containsPlayer() in CoreAbility
* Removed unnecessary looping and now uses getAbilityFromPlayer() instead of looping through getAbilitiesFromPlayer()
=> [BUGFIX] Update containsPlayer() in CoreAbility, Fix NPE

src/com/projectkorra/projectkorra/BendingPlayer.java, src/com/projectkorra/projectkorra/GeneralMethods.java, src/com/projectkorra/projectkorra/ability/api/CoreAbility.java, src/com/projectkorra/projectkorra/ability/multiability/MultiAbilityManager.java, src/com/projectkorra/projectkorra/ability/multiability/MultiAbilityModule.java, src/com/projectkorra/projectkorra/airbending/Suffocate.java, src/com/projectkorra/projectkorra/earthbending/LavaFlow.java, src/com/projectkorra/projectkorra/firebending/FireMethods.java, src/com/projectkorra/projectkorra/firebending/Lightning.java, src/com/projectkorra/projectkorra/storage/Database.java, src/com/projectkorra/projectkorra/util/MetricsLite.java, src/com/projectkorra/projectkorra/util/ParticleEffect.java, src/com/projectkorra/projectkorra/util/ReflectionHandler.java, src/com/projectkorra/projectkorra/waterbending/WaterArms.java, src/com/projectkorra/projectkorra/waterbending/WaterMethods.java
* Update javadocs so ant could generate javadocs with least amount of warnings
=> Update javadocs to fix warnings

src/com/projectkorra/projectkorra/GeneralMethods.java, src/com/projectkorra/projectkorra/firebending/FireBlast.java
*Fixes FireBlast and other moves permanently removing blocks like glass panes and torches.
*Fixes benders being able to bend/use moves from other sub-elements without the subelement permission.
=> Bug Fixes 

src/com/projectkorra/projectkorra/earthbending/LavaFlow.java
LavaFlow no longer checks to allow plantbending
=> Fix LavaFlow affecting plants

src/com/projectkorra/projectkorra/util/Flight.java
Fixes most causes of the fly glitch issue.
=> Fixed most of the Fly glitch.

src/com/projectkorra/projectkorra/Commands.java, src/com/projectkorra/projectkorra/airbending/AirMethods.java, src/com/projectkorra/projectkorra/earthbending/EarthMethods.java, src/com/projectkorra/projectkorra/firebending/FireMethods.java, src/com/projectkorra/projectkorra/waterbending/WaterMethods.java
Added getElementSubColor() method to each element file (not including
chi) to easily return said elements sub element color,
getMetalbendingColor() has been marked as depreciated and will be
removed soon as it is no longer needed.
Added new staff members to /b who, kingbirdy still requires an account
and AlexTheCoder is still included.
=> Added getElementSubColor()

src/com/projectkorra/projectkorra/GeneralMethods.java, src/com/projectkorra/projectkorra/ability/api/CoreAbility.java, src/com/projectkorra/projectkorra/airbending/AirBubble.java, src/com/projectkorra/projectkorra/airbending/AirBurst.java, src/com/projectkorra/projectkorra/airbending/AirScooter.java, src/com/projectkorra/projectkorra/airbending/AirShield.java, src/com/projectkorra/projectkorra/airbending/AirSpout.java, src/com/projectkorra/projectkorra/airbending/AirSwipe.java, src/com/projectkorra/projectkorra/airbending/Suffocate.java, src/com/projectkorra/projectkorra/airbending/Tornado.java, src/com/projectkorra/projectkorra/firebending/Combustion.java, src/com/projectkorra/projectkorra/firebending/FireJet.java, src/com/projectkorra/projectkorra/firebending/FireShield.java, src/com/projectkorra/projectkorra/firebending/FireStream.java, src/com/projectkorra/projectkorra/firebending/Fireball.java, src/com/projectkorra/projectkorra/firebending/Lightning.java
* Added ComboManager to reloadPlugin()
* Cleanup GeneralMethods.java thanks to @DotDashh
* Fix speed in AirScooter
* Add getAbility to CoreAbility - To prevent unnecessary looping which could cause a thread to hang
* Update Fire and Air with getAbility
=> [BUGFIX] Add ComboManager to reloadPlugin(), Fix speed in AirScooter, GeneralMethods cleanup

src/com/projectkorra/projectkorra/chiblocking/ChiblockingManager.java
- Added fix to accumulative paralyze fall damage, does not effect fall distance after player is paralyzed.
=> Fix to accumulative paralyze fall damage

src/com/projectkorra/projectkorra/PKListener.java, src/com/projectkorra/projectkorra/airbending/FlightAbility.java, src/com/projectkorra/projectkorra/configuration/ConfigManager.java
Fixed flight ability giving fly glitch.
Fixed a missing bracket in the pk listener.
Also fixed earthblast not doing damage.
=> Fixed FlightAbility fly glitch.

src/com/projectkorra/projectkorra/earthbending/EarthColumn.java
- Added check for avatarstate so height can be modified accordingly. New version is as tall as sneak version with avatarstate.
=> Fixed RaiseEarth + AvatarState click height

src/com/projectkorra/projectkorra/GeneralMethods.java
* Add back negation which should have been in isSolid() in GeneralMethods
* Fix's abilities being broken in BETA 15
=> [URGENT] Add negation to isSolid() in GeneralMethods

src/com/projectkorra/projectkorra/ability/AvatarState.java
- Fixed NPE in avatarstate thrown when the user disconnects in avatarstate
=> Fix NPE in AvatarState

src/com/projectkorra/projectkorra/BendingManager.java
Fixed the firebending night message from not showing
=> Fixed Firebending Night Message

src/com/projectkorra/projectkorra/Commands.java, src/com/projectkorra/projectkorra/Element.java, src/com/projectkorra/projectkorra/GeneralMethods.java, src/com/projectkorra/projectkorra/SubElement.java, src/com/projectkorra/projectkorra/ability/combo/ComboManager.java
• Combos now displayed in /bending display
Fire/Water/Air/Earth/ChiCombos
• Combo usage is now displayed in /bending help ComboName
• Using /bending help <Element>Combo shows correct usage, just so people
get used to the new method (still much easier).
• GeneralMethods has 3 new methods
• GeneralMethods.getComboColor(...) - Returns ChatColor
• GeneralMethods.getComboElement(...) - Returns Element
• GeneralMethods.getAbilitySubElement(...) - Returns the sub element of
the ability specified if it has one
• The main element can now be gotten from subelements via subelement.getMainElement()
• Elements and SubElements now contain methods to get their correct ChatColor
• Overall, Elements and SubElements integrated like they should be
=> Change combo display method and revamped Elements and SubElements

src/com/projectkorra/projectkorra/Commands.java
- catch for nonexistent commands and help topics, refers the command sender to /bending help
- add help messages for check, debug, and presets
- correct some ifs to else ifs
=> Add new help messages and catch for nonexistent command

src/com/projectkorra/projectkorra/storage/DBConnection.java, src/com/projectkorra/projectkorra/util/Updater.java
- Updater would throw NPE and UnknownHostException when it could not connect to projectkorra.com
- Also cleaned up output of DB connections
=> Fix errors when starting server offline

src/com/projectkorra/projectkorra/ability/api/CoreAbility.java, src/com/projectkorra/projectkorra/ability/combo/ComboManager.java, src/com/projectkorra/projectkorra/earthbending/EarthSmash.java, src/com/projectkorra/projectkorra/firebending/FireBlast.java, src/com/projectkorra/projectkorra/waterbending/WaterMethods.java
Improve CoreAbility Efficiency
- Accessing ability instances using the getInstances method is now much faster.
- Core and Items should now run much more smoothly.
Improve ComboManager Efficiency
- ComboManager was causing immense lag if a server stayed on for too long.
Remove FireBlast and FireBurst Fire Correctly
- The fire effect caused by FireBlast was reappearing after 60 seconds, even if it was removed with HeatControl.
EarthSmash now works in AvatarState
=> Efficiency Improvements, EarthSmash Fix, Fire Revert Fix

src/com/projectkorra/projectkorra/GeneralMethods.java, src/com/projectkorra/projectkorra/airbending/AirCombo.java
- Fixed being able to bend in spectator mode.
- Redo on the fix for airsweep going through blocks.
=> Spectator Fix & AirSweep Fix (Again)

src/com/projectkorra/projectkorra/ability/combo/ComboManager.java
Made improvements to the ComboManager memory cleanup process.
=> Fix ComboManager Lag Issue

src/com/projectkorra/projectkorra/BendingManager.java, src/com/projectkorra/projectkorra/configuration/ConfigManager.java, src/com/projectkorra/projectkorra/util/Updater.java
* Fix Updater not recognizing core build
* Fix problem where update would think core builds needed to update to lower version beta eg) 1.7.0 update to 1.7.0 BETA 1 when it shouldnt
* Cleanup imports
* Fix NPE for LunarEclipseMessage that effected PKRPG
* Remove deprecated config option for TagAPI
=> [BUGFIX] 1.8.0 BETA 2

src/com/projectkorra/projectkorra/PKListener.java
- Fixes fireblast and other abilities paralyzing the hit player on contact.
=> Fix ability paralyzing

src/com/projectkorra/projectkorra/PKListener.java
- Added missing import for CoreAbility
=> Add missing import

src/com/projectkorra/projectkorra/command/AddCommand.java, src/com/projectkorra/projectkorra/command/PresetCommand.java, src/com/projectkorra/projectkorra/command/WhoCommand.java, src/com/projectkorra/projectkorra/object/Preset.java, src/com/projectkorra/projectkorra/storage/DBConnection.java
- Fix bug in /b add not saving elements
- Fix bug in /b who causing error looking up nonbenders
=> Change Preset queries to use PreparedStatements

src/com/projectkorra/projectkorra/command/WhoCommand.java
- Add grasshopperMatt to staff list
=> Fix staff titles not displaying with /b who

src/com/projectkorra/projectkorra/BendingPlayer.java, src/com/projectkorra/projectkorra/GeneralMethods.java, src/com/projectkorra/projectkorra/ProjectKorra.java, src/com/projectkorra/projectkorra/command/CheckCommand.java, src/com/projectkorra/projectkorra/command/ImportCommand.java, src/com/projectkorra/projectkorra/command/PKCommand.java, src/com/projectkorra/projectkorra/command/SubCommand.java, src/com/projectkorra/projectkorra/command/WhoCommand.java, src/com/projectkorra/projectkorra/object/Preset.java
* General cleanup:
* Remove Presets.loadPresets(player) from onEnable and reloadPlugin because PKListener.login() already calls this and login() is called when a bending player is created
* Thus fixes double loading of presets on reload
* Remove unused imports
* Rename PKCommandInterface to SubCommand to fit a proper command naming scheme
* Fix Check command displaying current version when it should be displaying latest version
=> General Cleanup, Fix Update command

src/com/projectkorra/projectkorra/GeneralMethods.java, src/com/projectkorra/projectkorra/ability/combo/ComboManager.java, src/com/projectkorra/projectkorra/ability/combo/ComboModuleManager.java, src/com/projectkorra/projectkorra/command/Commands.java, src/com/projectkorra/projectkorra/command/HelpCommand.java, src/com/projectkorra/projectkorra/earthbending/EarthPassive.java
Fixes Earthbending passive not reverting blocks back with the correct damage value.
Fixes bending help command for abilities
Fixes bending display command for combos
=> Fix Earth Passive and Commands

src/com/projectkorra/projectkorra/PKListener.java
- Fixed suffocate to make it work properly, giving slowness + blindness only, removing the total control stopping.
=> Fix suffocate

src/com/projectkorra/projectkorra/util/Updater.java
* Makes sure if the forum build release has lowercase it won't effect the updater
=> Add fail-safe for version CaSe to Updater

src/com/projectkorra/projectkorra/command/ChooseCommand.java
Fixes Internal Errors when choosing other players bending
Fixes bending not being saved when chosen by another player/console
=> Fix Choose Command Errors

src/com/projectkorra/projectkorra/ability/AbilityModuleManager.java, src/com/projectkorra/projectkorra/earthbending/Catapult.java
* Update AbilityModuleManager to handle java.lang.Error where as it was only handling Exceptions before
* Format imports and class for Catapult
* Fix line 78 in Flight where Catapult.getPlayers() didn't exist
=> Bugfixes and Cleanup

src/com/projectkorra/projectkorra/PKListener.java
- Added event (EntityDeathEvent)
- Fixed incorrect checks
- Fixed metalclips incorrect armor dropping on clipped player's death
- Fixed cooldown
=> Fix MetalClips

src/com/projectkorra/projectkorra/earthbending/MetalClips.java
- Added getOriginalHelmet(LivingEntity ent) method
- Added getOriginalChestplate(LivingEntity ent) method
- Added getOriginalLeggings(LivingEntity ent) method
- Added getOriginalBoots(LivingEntity ent) method
- Changed target variable to targetent
=> Fix MetalClips Pt. 2

src/com/projectkorra/projectkorra/earthbending/MetalClips.java
- Changed where the Iron Ingot is shot from, was feet and now it shoots from higher up. Not much difference if any.
=> Change MetalClips

.travis.yml
* Update travis config to use new system triggered by ```sudo: false```
* Update travis to post notifications on slack
=> Update travis config to new system, support Slack

src/com/projectkorra/projectkorra/PKListener.java, src/com/projectkorra/projectkorra/airbending/AirCombo.java, src/com/projectkorra/projectkorra/command/AddCommand.java, src/com/projectkorra/projectkorra/firebending/FireCombo.java, src/com/projectkorra/projectkorra/firebending/FireStream.java
Players in Spectator mode are now uneffected by bending.
Spawned fire no longer replaces glass panes.
Bending add command is no longer case sensitive.
Added Gamemode Change Event in PKListener
=> Various Fixes

src/com/projectkorra/projectkorra/waterbending/WaterPassive.java
- Fixed waterbender's taking fall damage on tempblock ice blocks.
=> Fix Water fall damage

src/com/projectkorra/projectkorra/GeneralMethods.java, src/com/projectkorra/projectkorra/PKListener.java, src/com/projectkorra/projectkorra/command/WhoCommand.java, src/com/projectkorra/projectkorra/firebending/FireMethods.java
• Fixes /bending who not working for OfflinePlayers
• OfflinePlayers supported for BendingPlayers
• Fixed Debug Spam
=> OfflinePlayer Support Fix

src/com/projectkorra/projectkorra/command/RemoveCommand.java
- Fixes remove command saying the player doesn't have permission when the player does
=> Fix remove command

src/com/projectkorra/projectkorra/command/AddCommand.java, src/com/projectkorra/projectkorra/command/ChooseCommand.java, src/com/projectkorra/projectkorra/command/Commands.java, src/com/projectkorra/projectkorra/command/DisplayCommand.java, src/com/projectkorra/projectkorra/command/HelpCommand.java, src/com/projectkorra/projectkorra/command/PermaremoveCommand.java, src/com/projectkorra/projectkorra/command/RemoveCommand.java
- Fixed capitalization problems with main command (/bending and aliases)
- Fixed capitalization problems with sub commands (Eg. /bending add)
- Fixed capitalization problems with command args (Eg. /bending ch EaRtH)
- Added a subelement list to the Error message of /bending display
- Fixed unusable abilities not being removed when player's elements are removed with /bending remove
- Fixed incorrect term chibender in commands choose and add
- Added combo and subelement display commands on the main element display messages
- Added message for if there are no abilities of a subelement installed on the server
=> Command fixes/changes

src/com/projectkorra/projectkorra/PKListener.java, src/com/projectkorra/projectkorra/airbending/AirCombo.java, src/com/projectkorra/projectkorra/configuration/ConfigManager.java, src/com/projectkorra/projectkorra/firebending/FireCombo.java, src/com/projectkorra/projectkorra/waterbending/WaterCombo.java
Fix DeathMessages not showing actual messages
Changed FireComboStream to require an ability name
Added support for more combo death messages
Fix IceBullet death message
=> Fix DeathMessages

src/com/projectkorra/projectkorra/PKListener.java, src/com/projectkorra/projectkorra/ability/combo/ComboManager.java, src/com/projectkorra/projectkorra/airbending/AirBlast.java, src/com/projectkorra/projectkorra/configuration/ConfigManager.java
- Fixed prefixes appearing in the multiples for the same player WARNING: not tested with /nick
- Fixed IceBullet steps in /b h icebullet to match the steps needed
- Fixed incorrect description of AirBubble and WaterBubble in config
- Added new config option for AirBlast, now has a push factor for self and also for others
=> General fixes

src/com/projectkorra/projectkorra/Element.java, src/com/projectkorra/projectkorra/PKListener.java, src/com/projectkorra/projectkorra/command/AddCommand.java, src/com/projectkorra/projectkorra/firebending/FireCombo.java
Fixes AddCommand not showing sender chi message.
Fixes DeathMessages not showing messages for WaterArms.
Fixes FireCombos DeathMessage colors not working.
=> Fix AddCommand & DeathMessages

src/com/projectkorra/projectkorra/util/RevertChecker.java
* Fix's the ConcurrentModificationException, by changing Sets back into Maps
=> [Urgent] Change RevertChecker Sets back into Maps

src/com/projectkorra/projectkorra/ability/AbilityModuleManager.java, src/com/projectkorra/projectkorra/chiblocking/ChiCombo.java, src/com/projectkorra/projectkorra/command/ImportCommand.java, src/com/projectkorra/projectkorra/earthbending/EarthBlast.java, src/com/projectkorra/projectkorra/earthbending/EarthPassive.java, src/com/projectkorra/projectkorra/waterbending/WaterManipulation.java, src/com/projectkorra/projectkorra/waterbending/WaterPassive.java, src/com/projectkorra/projectkorra/waterbending/WaterSpout.java, src/com/projectkorra/projectkorra/waterbending/WaterWave.java
• Fixes WaterSpout not working over packed ice
• Fixes WaterWave exception when teleporting across worlds
• Fixes compile warnings (they were annoying me!)
=> Fix WaterSpout Bugs

src/com/projectkorra/projectkorra/object/HorizontalVelocityTracker.java
- Add missing import of BlockFace
=> Add import

src/com/projectkorra/projectkorra/airbending/AirBurst.java
- Remove 2nd instance of reloadVariables()
=> Fix AirBurst

src/com/projectkorra/projectkorra/firebending/FireBlast.java
- Remove 2nd instance of reloadVariables()
=> Fix FireBlast

src/com/projectkorra/projectkorra/firebending/Fireball.java
- Removes fireblast being instantiated if a player stops sneaking whilst charging fireblast
=> Fix Charged Fireblast

src/com/projectkorra/projectkorra/earthbending/Catapult.java
- Removes 2nd instance of reloadVariables()
=> Fix Catapult

src/com/projectkorra/projectkorra/command/BindCommand.java
- Fixes element toggle caused error
=> Fix Element Toggle

src/com/projectkorra/projectkorra/ability/combo/ComboManager.java
Improves the way in which combo resources are removed
=> Update Combo Cleanup

src/com/projectkorra/projectkorra/command/ToggleCommand.java
- Fixes Element toggle message
=> Fix message

src/com/projectkorra/projectkorra/GeneralMethods.java
- Fixes element toggling not toggling passives with it
=> Fix element toggling

src/plugin.yml
- Adds bloodbending permission node to bending.water, false default.
=> Add Bloodbending node

src/com/projectkorra/projectkorra/earthbending/Catapult.java
- Fixes invincible in Catapult, removing that instance of Catapult from the invincible arraylist
=> Fix invincible Catapult

src/com/projectkorra/projectkorra/firebending/FireJet.java
- Fixes invincible in firejet, making it remove that instance of firejet from the invincible arraylist
=> Fix invincible FireJet

src/com/projectkorra/projectkorra/PKListener.java, src/com/projectkorra/projectkorra/object/HorizontalVelocityTracker.java
=> Velocity Death Message Fix

src/com/projectkorra/projectkorra/command/BendingTabComplete.java, src/com/projectkorra/projectkorra/command/Commands.java
• Tabbing now works in the bending command and all applicable
subcommands.
=> Add Autotabbing to Commands

.travis.yml, src/com/projectkorra/projectkorra/PKListener.java, src/com/projectkorra/projectkorra/airbending/AirBlast.java, src/com/projectkorra/projectkorra/airbending/AirSuction.java, src/com/projectkorra/projectkorra/command/DisplayCommand.java, src/com/projectkorra/projectkorra/event/HorizontalVelocityChangeEvent.java, src/com/projectkorra/projectkorra/object/HorizontalVelocityTracker.java, src/com/projectkorra/projectkorra/waterbending/Bloodbending.java
- Fixed display command when used in console
- Changes HorizontalVelocityTracker and HorizontalVelocityChangeEvent contructors to use Element and SubElement so Death messages use color, and Switched StockAbility with String for Addon compatibility
=> Fix display command console, Change horizontal velocity for addons

src/com/projectkorra/projectkorra/waterbending/WaterWave.java
=> WaterWave NPE Fix

src/com/projectkorra/projectkorra/command/BendingTabComplete.java
• Adds in subs for display
• Adds combos for help
• Removed subs from help
=> Fix Missing Autotab Arguments

src/com/projectkorra/projectkorra/command/AddCommand.java, src/com/projectkorra/projectkorra/command/BendingTabComplete.java, src/com/projectkorra/projectkorra/command/ChooseCommand.java, src/com/projectkorra/projectkorra/command/ClearCommand.java, src/com/projectkorra/projectkorra/command/RemoveCommand.java, src/com/projectkorra/projectkorra/command/WhoCommand.java
• Fixed Syntax
• Again fixed Autotabbing
=> Fix Commands

src/com/projectkorra/projectkorra/command/BendingTabComplete.java, src/com/projectkorra/projectkorra/waterbending/Torrent.java, src/com/projectkorra/projectkorra/waterbending/WaterManipulation.java
Add bubble particles to Torrent & WaterManipulation if they are underwater.
Also changed canBend to canBind in TabCompleter
=> Add bubbles to Torrent & WaterManip

src/com/projectkorra/projectkorra/waterbending/Bloodbending.java, src/plugin.yml
• Fixes Ops not having all bending permissions (bloodbending, etc)
• Fixes Bloodbending not moving mobs in non-solid blocks
=> Fix Bloodbending Bugs and Permissions

src/com/projectkorra/projectkorra/command/BendingTabComplete.java, src/com/projectkorra/projectkorra/command/WhoCommand.java
- Changed /bending who list version to show all elements of a player (eg; Simplicitee - A | W|) and also show staff title (eg; StrangeOne101 - ProjectKorra Developer), elements are listed alphabetically and staff title will always be the last thing listed.
- Fixed auto tab by changing two instances of canBend to canBind (as told by StrangeOne101)
=> Change /bending who, Fix Auto Tab problem

src/com/projectkorra/projectkorra/command/WhoCommand.java
- Added different display for bending/element toggled
- Commented out let go staff uuids
=> Changes to bending who

src/com/projectkorra/projectkorra/util/Updater.java
Add 30 second timeout to Updater
=> Add 30 second timeout to Updater

src/com/projectkorra/projectkorra/firebending/Fireball.java
• Fixes NPE in Fireball
• Fixes measuring distance across worlds
=> Fix Fireball NPE

src/com/projectkorra/projectkorra/GeneralMethods.java, src/com/projectkorra/projectkorra/PKListener.java
ProjectKorra absolutely needs to verify its code before publishing or compiling it...
=> Crucial typo fix

src/com/projectkorra/projectkorra/command/BendingTabComplete.java, src/com/projectkorra/projectkorra/command/WhoCommand.java, src/com/projectkorra/projectkorra/configuration/ConfigManager.java, src/com/projectkorra/projectkorra/earthbending/Catapult.java, src/com/projectkorra/projectkorra/event/PlayerCooldownChangeEvent.java, src/com/projectkorra/projectkorra/util/ActionBar.java, src/com/projectkorra/projectkorra/waterbending/WaterArmsFreeze.java
Fixes WaterArms Freeze going through ice
Fixes cooldown typos
Adds get/set cooldown in PlayerCooldownChangeEvent
Adds Shift Modifier config option for Catapult
Adds element toggle indicator to /b who <player>
Adds stock combos to autotab
Adds ActionBar Util (for future use)
=> Various additions/fixes (read desc.)

src/com/projectkorra/projectkorra/configuration/ConfigManager.java, src/com/projectkorra/projectkorra/earthbending/Collapse.java, src/com/projectkorra/projectkorra/earthbending/CompactColumn.java, src/com/projectkorra/projectkorra/earthbending/EarthArmor.java, src/com/projectkorra/projectkorra/earthbending/EarthBlast.java, src/com/projectkorra/projectkorra/earthbending/EarthColumn.java, src/com/projectkorra/projectkorra/earthbending/EarthWall.java, src/com/projectkorra/projectkorra/earthbending/LavaFlow.java, src/com/projectkorra/projectkorra/earthbending/LavaSurge.java, src/com/projectkorra/projectkorra/earthbending/LavaWall.java, src/com/projectkorra/projectkorra/earthbending/LavaWave.java, src/com/projectkorra/projectkorra/util/BlockSource.java, src/com/projectkorra/projectkorra/waterbending/IceSpike2.java, src/com/projectkorra/projectkorra/waterbending/WaterCombo.java, src/com/projectkorra/projectkorra/waterbending/WaterMethods.java, src/com/projectkorra/projectkorra/waterbending/WaterWave.java
Removes Auto/Dynamic capabilities from various moves (shouldnt have had
them)
Fixes metalbending
Fixes Dynamic Toggles not working correctly
=> Various fixes (read desc.)

src/com/projectkorra/projectkorra/PKListener.java, src/com/projectkorra/projectkorra/earthbending/EarthArmor.java, src/com/projectkorra/projectkorra/waterbending/PlantArmor.java
- Fixed EarthArmor and PlantArmor dropping the armor on death
=> Fix EarthArmor and PlantArmor

src/com/projectkorra/projectkorra/configuration/ConfigManager.java, src/com/projectkorra/projectkorra/util/BlockSource.java, src/com/projectkorra/projectkorra/waterbending/Bloodbending.java, src/com/projectkorra/projectkorra/waterbending/IceSpike2.java, src/com/projectkorra/projectkorra/waterbending/WaterWall.java
Fixes miscalculated Surge wall distance
Fixed IceSpike projectile & added cooldown
Fixed dynamic sources making super deep holes
Fixed PlantArmor not being able to auto source
Fixed Bloodbending damage jitter
=> Various Fixes (read desc)

src/com/projectkorra/projectkorra/command/BendingTabComplete.java, src/com/projectkorra/projectkorra/command/CopyCommand.java
• Adds tabbing to the new /bending copy command
• Adds tabbing to new /bending preset bind <preset> [player]
• Adds tabbing to new /bending preset bind <external> [player]
• Fixes permission problem with /bending copy
=> Add Tabbing to new commands

src/com/projectkorra/projectkorra/command/BendingTabComplete.java, src/com/projectkorra/projectkorra/command/PresetCommand.java, src/com/projectkorra/projectkorra/configuration/ConfigManager.java, src/com/projectkorra/projectkorra/object/Preset.java, src/com/projectkorra/projectkorra/waterbending/WaterArmsSpear.java, src/com/projectkorra/projectkorra/waterbending/WaterWave.java
• Fixes Tabbing for /bending copy
• Fixes weird messages when binding external presets that fail
=> Fix Tabbing + Fix Preset Messages

src/com/projectkorra/projectkorra/earthbending/EarthMethods.java, src/com/projectkorra/projectkorra/earthbending/EarthSmash.java, src/com/projectkorra/projectkorra/util/BlockSource.java, src/com/projectkorra/projectkorra/waterbending/IceSpike.java, src/com/projectkorra/projectkorra/waterbending/IceSpike2.java, src/com/projectkorra/projectkorra/waterbending/WaterCombo.java, src/com/projectkorra/projectkorra/waterbending/WaterManipulation.java, src/com/projectkorra/projectkorra/waterbending/WaterMethods.java, src/com/projectkorra/projectkorra/waterbending/WaterSpout.java, src/com/projectkorra/projectkorra/waterbending/WaterWave.java
Fixes grabbing EarthSmash after you shoot it
Fixes IceSpiking IceSpike projectiles
Fixes Selecting flowing water
Cleans unused/warnings
=> Various Fixes (read desc) / Cleanup

src/com/projectkorra/projectkorra/BendingManager.java, src/com/projectkorra/projectkorra/GeneralMethods.java, src/com/projectkorra/projectkorra/firebending/FireBurst.java, src/com/projectkorra/projectkorra/firebending/FireMethods.java, src/com/projectkorra/projectkorra/firebending/Lightning.java, src/com/projectkorra/projectkorra/waterbending/WaterArmsSpear.java, src/com/projectkorra/projectkorra/waterbending/WaterArmsWhip.java, src/com/projectkorra/projectkorra/waterbending/WaterMethods.java
- Removed all event stuff from BendingManager
- Changed the checks in effected classes to match RPG
=> ProjectKorra + RPG compatibility

src/com/projectkorra/projectkorra/chiblocking/ChiCombo.java, src/com/projectkorra/projectkorra/firebending/WallOfFire.java
Fix ChiCombo ArrayOutOfBoundsException
Change  WOF to no longer affect entities in tempblocks
Fix WOF displaying particles in solid blocks
=> Fix WOF & ChiCombo

src/com/projectkorra/projectkorra/command/HelpCommand.java, src/com/projectkorra/projectkorra/waterbending/HealingWaters.java
Stop help command from showing players commands they dont have
permissions to use
=> Fix help command

src/com/projectkorra/projectkorra/airbending/AirBlast.java, src/com/projectkorra/projectkorra/airbending/AirScooter.java, src/com/projectkorra/projectkorra/airbending/Suffocate.java, src/com/projectkorra/projectkorra/command/BendingTabComplete.java, src/com/projectkorra/projectkorra/command/Commands.java, src/com/projectkorra/projectkorra/command/CopyCommand.java, src/com/projectkorra/projectkorra/command/HelpCommand.java, src/com/projectkorra/projectkorra/command/PKCommand.java, src/com/projectkorra/projectkorra/command/PresetCommand.java, src/com/projectkorra/projectkorra/command/RemoveCommand.java, src/com/projectkorra/projectkorra/command/WhoCommand.java, src/com/projectkorra/projectkorra/configuration/ConfigManager.java, src/com/projectkorra/projectkorra/earthbending/EarthSmash.java, src/com/projectkorra/projectkorra/firebending/WallOfFire.java, src/com/projectkorra/projectkorra/object/Preset.java, src/com/projectkorra/projectkorra/util/BlockSource.java, src/com/projectkorra/projectkorra/waterbending/Bloodbending.java, src/com/projectkorra/projectkorra/waterbending/HealingWaters.java, src/com/projectkorra/projectkorra/waterbending/WaterArms.java, src/plugin.yml
Ignored most PRs relating to presets.
=> Update nearly all PRs above 357

src/com/projectkorra/projectkorra/GeneralMethods.java, src/com/projectkorra/projectkorra/waterbending/SurgeWall.java, src/com/projectkorra/projectkorra/waterbending/WaterArmsSpear.java, src/com/projectkorra/projectkorra/waterbending/WaterArmsWhip.java, src/com/projectkorra/projectkorra/waterbending/WaterReturn.java
Fix WaterArms getAugments NPE
Fix WaterReturn not returning water
Fix Surge Wall not freezing (Bugs out in creative mode)
Fix Presets appearing multiple times in preset list, when using /b reload
=> Fix Water Bugs & Preset Bug

src/com/projectkorra/projectkorra/ability/EarthAbility.java, src/com/projectkorra/projectkorra/ability/util/ComboManager.java, src/com/projectkorra/projectkorra/airbending/AirBubble.java, src/com/projectkorra/projectkorra/command/RemoveCommand.java, src/com/projectkorra/projectkorra/waterbending/IceSpikeBlast.java
Fix ComboManager click types
Fix NPE in IceSpike
Update to add https://github.com/ProjectKorra/ProjectKorra/commit/650407ac592ec382602367e5afab52311d2fed52
Fix WaterBubble not working
Fix Event NPE in Remove command
=> Update ComboManager to new ClickTypes & NPE

src/com/projectkorra/projectkorra/configuration/ConfigManager.java, src/com/projectkorra/projectkorra/waterbending/WaterManipulation.java
- Fixed error with how WaterManipulation gets the range
=> Fix WaterManipulation

src/com/projectkorra/projectkorra/Element.java
• Allows elements to be created by side-plugins
=> Made Element Protected

src/com/projectkorra/projectkorra/PKListener.java
Is there a reason why this was placed here? If such a thing is needed, it'd be nice if it were under a config option then.
=> Compatibility with other plugins' explosions; resolves #400

src/com/projectkorra/projectkorra/PKListener.java, src/com/projectkorra/projectkorra/firebending/FireCombo.java, src/com/projectkorra/projectkorra/util/ClickType.java, src/com/projectkorra/projectkorra/waterbending/Bloodbending.java, src/com/projectkorra/projectkorra/waterbending/WaterSpoutWave.java
Fix WaterSpoutWave being weird, creating new instances for each animation.
Remove the "Movement" clicktypes, as these were messing with combos.
Fix FireJet combos.
Fix Bloodbending making movement glitched.
=> Fix Combos & Bloodbending

src/com/projectkorra/projectkorra/waterbending/WaterSpout.java
- Fix removeSpouts method (needs to be tested because I couldn't test it alone)
- Fix remove setting flying and allow flight
=> Fix WaterSpout

src/com/projectkorra/projectkorra/configuration/ConfigManager.java, src/com/projectkorra/projectkorra/object/HorizontalVelocityTracker.java
- Added a config option for if the block a player hits with horizontal collisions is barrier.
=> Horizontal Collisions and Barriers

src/com/projectkorra/projectkorra/airbending/AirSwipe.java, src/com/projectkorra/projectkorra/firebending/FireCombo.java, src/com/projectkorra/projectkorra/waterbending/WaterSpout.java
- Changed where the cooldown is called in AirSwipe
- Added instances for FireDamageTimer in appropriate firecombos
- Fixed math mistake in WaterSpout
=> Various changes

src/com/projectkorra/projectkorra/PKListener.java, src/com/projectkorra/projectkorra/firebending/FireCombo.java
- Makes FireCombos cook animal meat when killing (excludes JetBlast)
=> Fix FireCombo

src/com/projectkorra/projectkorra/GeneralMethods.java, src/com/projectkorra/projectkorra/PKListener.java, src/com/projectkorra/projectkorra/airbending/AirBlast.java, src/com/projectkorra/projectkorra/airbending/AirSuction.java, src/com/projectkorra/projectkorra/airbending/AirSwipe.java, src/com/projectkorra/projectkorra/airbending/Suffocate.java, src/com/projectkorra/projectkorra/earthbending/EarthSmash.java, src/com/projectkorra/projectkorra/earthbending/LavaSurge.java, src/com/projectkorra/projectkorra/event/EntityBendingDeathEvent.java, src/com/projectkorra/projectkorra/event/HorizontalVelocityChangeEvent.java, src/com/projectkorra/projectkorra/firebending/FireBlastCharged.java, src/com/projectkorra/projectkorra/firebending/FireDamageTimer.java, src/com/projectkorra/projectkorra/object/HorizontalVelocityTracker.java, src/com/projectkorra/projectkorra/waterbending/Bloodbending.java
- change EntityBendingDeath and HorizontalVelocityChange to use Ability objects, instead of strings
- update abilities to reflect changes
=> Remove unneeded damageEntity method, update events

src/com/projectkorra/projectkorra/BendingPlayer.java, src/com/projectkorra/projectkorra/Element.java, src/com/projectkorra/projectkorra/GeneralMethods.java, src/com/projectkorra/projectkorra/chiblocking/QuickStrike.java, src/com/projectkorra/projectkorra/command/AddCommand.java, src/com/projectkorra/projectkorra/command/BendingTabComplete.java, src/com/projectkorra/projectkorra/command/ChooseCommand.java, src/com/projectkorra/projectkorra/command/DisplayCommand.java, src/com/projectkorra/projectkorra/command/RemoveCommand.java, src/com/projectkorra/projectkorra/command/ToggleCommand.java, src/com/projectkorra/projectkorra/command/WhoCommand.java
Add remove call to quickstrike
Make element & subelement public
Update API to support custom elements correctly. (Has been tested, and  theoretically everything should be fine, but could do with some extra testing).
Fix bug with toggling elements.
=> Various Changes & Fixes

src/com/projectkorra/projectkorra/PKListener.java
- Fixed fall damage animation activating for chiblockers
=> Fix fall damage animation

src/com/projectkorra/projectkorra/firebending/FireBlast.java
- Added the variable for FireBlast damage to be set
- Added getDayFactor to damage and a range variable in FireBlast
=> Fix FireBlast damage

src/com/projectkorra/projectkorra/ability/EarthAbility.java, src/com/projectkorra/projectkorra/ability/ElementalAbility.java, src/com/projectkorra/projectkorra/ability/WaterAbility.java, src/com/projectkorra/projectkorra/configuration/ConfigManager.java, src/com/projectkorra/projectkorra/earthbending/LavaSurgeWall.java, src/com/projectkorra/projectkorra/firebending/FireBlast.java, src/com/projectkorra/projectkorra/firebending/FireCombo.java, src/com/projectkorra/projectkorra/util/BlockSource.java, src/com/projectkorra/projectkorra/waterbending/OctopusForm.java, src/com/projectkorra/projectkorra/waterbending/SurgeWall.java, src/com/projectkorra/projectkorra/waterbending/SurgeWave.java, src/com/projectkorra/projectkorra/waterbending/WaterPassive.java, src/com/projectkorra/projectkorra/waterbending/WaterSourceGrabber.java
Adds Plant & Ice source list to config
Removes PackedIce option (can now be set or removed through Ice list)
Fixes being able to select through walls
Cleans up old/unused config options (grapplingHooks, bentblocks, packedIce, etc)
=> Various Fixes & Additions

src/com/projectkorra/projectkorra/BendingPlayer.java, src/com/projectkorra/projectkorra/Element.java, src/com/projectkorra/projectkorra/command/WhoCommand.java
Add documentation to Element
Add canUseSubElement() method to BendingPlayer
Fix who command to show addon subelements of official elements.
=> Add documentation and update Who command

src/com/projectkorra/projectkorra/ability/WaterAbility.java, src/com/projectkorra/projectkorra/configuration/ConfigManager.java, src/com/projectkorra/projectkorra/configuration/ConfigType.java
- Changed configtype to not be an enum
- Removed an unused import
- Edited configmanager to match ConfigType
=> Edit config for Rpg

src/com/projectkorra/projectkorra/command/WhoCommand.java, src/com/projectkorra/projectkorra/configuration/ConfigType.java
- Added new staff members to whocommand
- Removed edited out staff
- Fixed ConfigType
=> Add new staff, Fixed ConfigType

src/com/projectkorra/projectkorra/command/BendingTabComplete.java
• Added tabbing support for the avatar and worldevent commands from RPG
=> Add RPG Command Tabbing

src/com/projectkorra/projectkorra/airbending/AirFlight.java
Fixed flight disabling flying when the player is in creative or
spectator mode.
=> Fixed flight disabling creative flight

src/com/projectkorra/projectkorra/BendingPlayer.java, src/com/projectkorra/projectkorra/GeneralMethods.java, src/com/projectkorra/projectkorra/command/AddCommand.java, src/com/projectkorra/projectkorra/command/BendingTabComplete.java, src/com/projectkorra/projectkorra/command/ChooseCommand.java, src/com/projectkorra/projectkorra/command/RemoveCommand.java, src/com/projectkorra/projectkorra/configuration/ConfigManager.java, src/com/projectkorra/projectkorra/storage/DBConnection.java
• Updated all commands to treat subelements as elements in certain
circumstances (add, remove, etc)
• Updated tabbing with bug fixes
• Database will now update player's subs when they log in for the first
time (post update)
• Removed "SubElementAdded" field from config
• Fixed /b choose not taking aliases
=> Update Subelement Lingo

src/com/projectkorra/projectkorra/command/AddCommand.java, src/com/projectkorra/projectkorra/command/ChooseCommand.java
• Just added some small things that were forgotten in the last commit
=> Add Forgotten Changes

src/com/projectkorra/projectkorra/storage/DBConnection.java
=> Fix table creation

src/com/projectkorra/projectkorra/BendingPlayer.java
Fixed passives working in a disabled world.
=> Fix passives in disabled world

src/com/projectkorra/projectkorra/ProjectKorra.java, src/com/projectkorra/projectkorra/airbending/AirPassive.java, src/com/projectkorra/projectkorra/airbending/AirbendingManager.java, src/com/projectkorra/projectkorra/chiblocking/ChiPassive.java, src/com/projectkorra/projectkorra/chiblocking/ChiblockingManager.java, src/com/projectkorra/projectkorra/configuration/ConfigManager.java, src/com/projectkorra/projectkorra/earthbending/EarthPassive.java, src/com/projectkorra/projectkorra/earthbending/EarthbendingManager.java, src/com/projectkorra/projectkorra/util/PassiveHandler.java
- Fixed passives merging and becoming wonky
- Updated speed, exhaustion, and jump passives to use PassiveHandler
class.
- Added exhaustion passive to chi
=> Fix and Upgrade passive system

src/com/projectkorra/projectkorra/GeneralMethods.java
• Fixed bending being allowed in GP zones
=> Fix Bending in GriefPrevention Regions

src/com/projectkorra/projectkorra/ability/WaterAbility.java, src/com/projectkorra/projectkorra/firebending/HeatControlExtinguish.java, src/com/projectkorra/projectkorra/waterbending/IceSpikeBlast.java, src/com/projectkorra/projectkorra/waterbending/IceSpikePillar.java, src/com/projectkorra/projectkorra/waterbending/IceSpikePillarField.java, src/com/projectkorra/projectkorra/waterbending/OctopusForm.java
• Fixed OctopusForm leaving smoke trails
• OctopusForm cooldown now applied when it starts forming, not when you
select a source
• Fixed Flooding with Bottlebending
• Fixed IcePillar not working on single click
• Fixed IcePillars not working on packed ice
• Reduced sounds created by IcePillarField (no longer extremely painful)
• Fixes heatcontrol now thawing ice in liquids as well as other opaque
blocks
=> Multiple Fixes

src/com/projectkorra/projectkorra/command/AddCommand.java, src/com/projectkorra/projectkorra/command/BendingTabComplete.java, src/com/projectkorra/projectkorra/command/BindCommand.java, src/com/projectkorra/projectkorra/command/ChooseCommand.java, src/com/projectkorra/projectkorra/command/ClearCommand.java, src/com/projectkorra/projectkorra/command/CopyCommand.java, src/com/projectkorra/projectkorra/command/DisplayCommand.java, src/com/projectkorra/projectkorra/command/HelpCommand.java, src/com/projectkorra/projectkorra/command/PKCommand.java, src/com/projectkorra/projectkorra/command/PermaremoveCommand.java, src/com/projectkorra/projectkorra/command/PresetCommand.java, src/com/projectkorra/projectkorra/command/RemoveCommand.java, src/com/projectkorra/projectkorra/command/ToggleCommand.java, src/com/projectkorra/projectkorra/command/WhoCommand.java
• Every command now has its own tabbing method instead of having all
tabbing in one file. This means custom PKCommands can now also be
tabbed.
=> Command Tabbing moved to PKCommands

src/com/projectkorra/projectkorra/ability/CoreAbility.java
Added getLanguageConfig() to CoreAbility.
=> Added getLanguageConfig()

src/com/projectkorra/projectkorra/PKListener.java, src/com/projectkorra/projectkorra/ProjectKorra.java, src/com/projectkorra/projectkorra/ability/ElementalAbility.java, src/com/projectkorra/projectkorra/ability/WaterAbility.java, src/com/projectkorra/projectkorra/airbending/AirCombo.java, src/com/projectkorra/projectkorra/configuration/ConfigManager.java, src/com/projectkorra/projectkorra/earthbending/EarthArmor.java, src/com/projectkorra/projectkorra/event/PlayerJumpEvent.java, src/com/projectkorra/projectkorra/firebending/FireJet.java, src/com/projectkorra/projectkorra/util/BlockSource.java, src/com/projectkorra/projectkorra/util/PassiveHandler.java, src/com/projectkorra/projectkorra/waterbending/HealingWaters.java, src/com/projectkorra/projectkorra/waterbending/PlantArmor.java, src/com/projectkorra/projectkorra/waterbending/SurgeWave.java, src/com/projectkorra/projectkorra/waterbending/WaterManipulation.java
- Added PlayerJumpEvent
- Added JUMPS map to PKListener
- Fixed fly glitch with airspout/sandspout + firejet
- Added snowBlocks config list
- Fixed AirCombo cooldowns
- Fixed FireSpin enabled config option not appearing
- Fixed speed and jump passives, no longer requires sprinting
- Fixed HealingWaters ShiftRequired config option
- Fixed Surge select range
- Fixed WaterManipulation creating water in place of ice sources
- Added snow methods to ElementalAbility and BlockSource
- Added SNOW enum value to BlockSourceType
- Added check for snow in WaterAbility.isWaterbendable()
=> Various bug fixes + new event

src/com/projectkorra/projectkorra/configuration/ConfigManager.java, src/com/projectkorra/projectkorra/util/PassiveHandler.java
- Fixed the FOV change that happens when jumping as a sandbender on sand
=> Fix sand speed passive

src/com/projectkorra/projectkorra/BendingPlayer.java, src/com/projectkorra/projectkorra/PKListener.java, src/com/projectkorra/projectkorra/ProjectKorra.java, src/com/projectkorra/projectkorra/ability/AvatarAbility.java, src/com/projectkorra/projectkorra/ability/CoreAbility.java, src/com/projectkorra/projectkorra/command/RemoveCommand.java, src/com/projectkorra/projectkorra/configuration/ConfigManager.java, src/com/projectkorra/projectkorra/event/AbilityProgressEvent.java, src/com/projectkorra/projectkorra/util/PassiveHandler.java
• Added requireAvatar() method to AvatarAbility
• Allows moves to be created that don't require the user to be the
avatar in order to use them (adding back old functionality)
• Added AbilityProgressEvent
• Tweaked Grammar
• Fixed speed/jump passives
• Fixed incorrect tabbing with the remove command
=> Various Additions + Fixes

src/com/projectkorra/projectkorra/chiblocking/ChiCombo.java, src/com/projectkorra/projectkorra/chiblocking/SwiftKick.java, src/com/projectkorra/projectkorra/configuration/ConfigManager.java, src/com/projectkorra/projectkorra/earthbending/Catapult.java, src/plugin.yml
Config changes
Fixes catapult cooldown
Adds cobblestone to default earth blocks list
Fixes SwiftKick cooldown
Fixes SwiftKick being able to be used without jumping
=> Config changes, bug fixes

src/com/projectkorra/projectkorra/PKListener.java, src/com/projectkorra/projectkorra/ability/util/ComboManager.java, src/com/projectkorra/projectkorra/chiblocking/ChiCombo.java, src/com/projectkorra/projectkorra/chiblocking/QuickStrike.java, src/com/projectkorra/projectkorra/util/ClickType.java
Added new ClickType (LEFT_CLICK_ENTITY)
Updated Immobilize to use LEFT_CLICK_ENTITY to fix being able to do the steps of Immobilize without hitting an entity
=> New ClickType / Fixes Immobilize bug

src/com/projectkorra/projectkorra/firebending/FireBlast.java
Already been pushed onto Beta 11 but still pushing it
=> Small FireBlast Fix

src/com/projectkorra/projectkorra/earthbending/Extraction.java, src/com/projectkorra/projectkorra/firebending/WallOfFire.java, src/com/projectkorra/projectkorra/waterbending/IceBlast.java, src/com/projectkorra/projectkorra/waterbending/SurgeWall.java, src/com/projectkorra/projectkorra/waterbending/WaterManipulation.java
With the way BottleBending works, you need to make sure it is set to false for the SnowSource and BottleSource, otherwise you can select water/leaves from a really close range.
=> Fixed IceBlast Selection Bug

src/com/projectkorra/projectkorra/airbending/AirFlight.java, src/com/projectkorra/projectkorra/command/RemoveCommand.java, src/com/projectkorra/projectkorra/object/PlayerFlyData.java
Change AirFlight to use setFlying.
Change remove command as per request of: "When doing /b remove <element> <name> it removes your element. The correct use is /b remove <name> <element> however, if using the first command make it so it tells you the correct usage rather than removing your element."
=> Change AirFlight to use setFlying. Change remove command.

src/com/projectkorra/projectkorra/command/AddCommand.java, src/com/projectkorra/projectkorra/command/ChooseCommand.java, src/com/projectkorra/projectkorra/command/WhoCommand.java, src/com/projectkorra/projectkorra/configuration/ConfigManager.java
Added checks to test which element is being chosen and then based on
that outputs a certain message.
=> Fixed grammar error in adding/choosing elements

src/com/projectkorra/projectkorra/waterbending/IceSpikeBlast.java, src/com/projectkorra/projectkorra/waterbending/WaterManipulation.java
IGNORE previous PR, this one is the fixed version
=> Fixed WaterManipulation & IceBlast not changing plants to air once used as a source

src/com/projectkorra/projectkorra/firebending/FireBlastCharged.java
Sorry I created this issue with my last PR.
=> Fixed charged fireblast not dealing damage when FireGriefing was off.

src/com/projectkorra/projectkorra/PKListener.java, src/com/projectkorra/projectkorra/command/BindCommand.java, src/com/projectkorra/projectkorra/command/HelpCommand.java, src/com/projectkorra/projectkorra/configuration/ConfigManager.java, src/com/projectkorra/projectkorra/earthbending/EarthTunnel.java, src/com/projectkorra/projectkorra/waterbending/WaterArms.java
• Added a message to the bind command when you don’t have the required
elements
• Fixed combos not appearing in the tablist for /b help
• Fixed EarthTunnel using wrong config option to revert
=> Range of Fixes

src/com/projectkorra/projectkorra/GeneralMethods.java, src/com/projectkorra/projectkorra/ability/WaterAbility.java, src/com/projectkorra/projectkorra/command/BindCommand.java, src/com/projectkorra/projectkorra/configuration/ConfigManager.java, src/com/projectkorra/projectkorra/earthbending/LavaFlow.java, src/com/projectkorra/projectkorra/waterbending/PhaseChangeMelt.java, src/com/projectkorra/projectkorra/waterbending/PlantRegrowth.java
• Added new message for failing to bind abilities when the user doesn't
have the required subelements
• Fixed PhaseChange not reverting melted ice
• Fixed LavaFlow not creating lava under double plants
• Fixed double plants dropping items when used as water sources
=> Final Fixes :D

src/com/projectkorra/projectkorra/command/VersionCommand.java, src/plugin.yml
Also credits Orion in version command.
=> Adds Spirits and Probending to Version command

src/com/projectkorra/projectkorra/PKListener.java
Adds support for {ELEMENT} and {ELEMENTCOLOR} tags that can be used in
EssentialsChat formatting
=> Added EssentialsChat support for elements

src/com/projectkorra/projectkorra/BendingPlayer.java, src/com/projectkorra/projectkorra/command/VersionCommand.java, src/plugin.yml
canBend now accounts for permissions and elements
=> Adds canBind check to canBend

src/com/projectkorra/projectkorra/ability/ElementalAbility.java, src/com/projectkorra/projectkorra/configuration/ConfigManager.java, src/com/projectkorra/projectkorra/firebending/BlazeArc.java, src/com/projectkorra/projectkorra/firebending/FireBlast.java, src/com/projectkorra/projectkorra/waterbending/IceSpikeBlast.java, src/com/projectkorra/projectkorra/waterbending/OctopusForm.java, src/com/projectkorra/projectkorra/waterbending/SurgeWall.java, src/com/projectkorra/projectkorra/waterbending/SurgeWave.java, src/com/projectkorra/projectkorra/waterbending/Torrent.java, src/com/projectkorra/projectkorra/waterbending/WaterArms.java, src/com/projectkorra/projectkorra/waterbending/WaterManipulation.java, src/com/projectkorra/projectkorra/waterbending/WaterSpoutWave.java
Ignite determines whether FireBurst creates fire blocks in the world
=> Fixes Snow Regen and Adds Ignite option to FireBurst

src/com/projectkorra/projectkorra/waterbending/SurgeWave.java, src/com/projectkorra/projectkorra/waterbending/WaterSpout.java
Water maniping your own spout no longer breaks it
Frozen SurgeWave now reverts water correctly
=> Fixed WaterSpout & SurgeWave bugs

src/com/projectkorra/projectkorra/airbending/AirFlight.java, src/com/projectkorra/projectkorra/chiblocking/SwiftKick.java
ty chaos for pointing it out
ty toby for being toby
=> Fixed AirFlight Fix

src/com/projectkorra/projectkorra/earthbending/EarthTunnel.java
-Fixed EarthTunnel dropping blocks
-Fixed EarthTunnel not breaking blocks from certain moves
-Fixed EarthTunnel on RaiseEarth leaving blocks behind
=> Various EarthTunnel fixes

src/com/projectkorra/projectkorra/airbending/AirFlight.java
Added check to prevent multiple instances of Flight being created.
=> Re-PR for Flight fix

src/com/projectkorra/projectkorra/airbending/AirFlight.java, src/com/projectkorra/projectkorra/airbending/AirSwipe.java, src/com/projectkorra/projectkorra/earthbending/MetalClips.java, src/com/projectkorra/projectkorra/firebending/WallOfFire.java
AirSwipe
* Removed the ability to change slots while charging AirSwipe.
_________
MetalClips
* Cooldown time starts when the armour drops off of the entity, rather than whenever the instance is removed.
___________
WallOfFire
* Added damage knockback.
___________
=> Fixed AirSwipe, MetalClips & WallOfFire

src/com/projectkorra/projectkorra/BendingPlayer.java, src/com/projectkorra/projectkorra/ability/WaterAbility.java, src/com/projectkorra/projectkorra/earthbending/EarthPassive.java, src/com/projectkorra/projectkorra/firebending/FirePassive.java, src/com/projectkorra/projectkorra/waterbending/WaterPassive.java
• Fixed Passives not being toggled with bending when they should be
• Fixed the select range for water moves being in your face when you're
under water (again)
=> Fixed Toggling Passives & Underwater Select Range

src/com/projectkorra/projectkorra/command/BindCommand.java, src/com/projectkorra/projectkorra/configuration/ConfigManager.java
• Fixed wording of abilities not being bound due to lack of subelements/elements
=> Fixed incorrect wording for failing to bind abilities

src/com/projectkorra/projectkorra/BendingPlayer.java, src/com/projectkorra/projectkorra/command/Commands.java, src/com/projectkorra/projectkorra/configuration/ConfigManager.java
BendingPlayer
* Added null check when removing cooldown of a player.
_________________
Commands
* language.yml now stores "Commands.GeneralHelpLines" as ArrayList<String> rather than String[]
- This fixes /b not working the first time the language.yml file is loaded.
_________________
=> Fixed: NPE on dconnect with cdown & /b not working on first load

src/com/projectkorra/projectkorra/PKListener.java, src/com/projectkorra/projectkorra/ability/EarthAbility.java, src/com/projectkorra/projectkorra/ability/WaterAbility.java, src/com/projectkorra/projectkorra/earthbending/EarthBlast.java, src/com/projectkorra/projectkorra/earthbending/RaiseEarth.java, src/com/projectkorra/projectkorra/earthbending/Ripple.java, src/com/projectkorra/projectkorra/util/TempBlock.java, src/com/projectkorra/projectkorra/waterbending/SurgeWall.java, src/com/projectkorra/projectkorra/waterbending/WaterSpout.java
• Fixed Shockwave making a mess of lava (with water?)
• Fixed select range for leaves being extremely short
• Fixed EarthTunnel making a mess of sand. Sand will no longer fall when
blocks beneath it are mined out with EarthTunnel (if it reverts)
• Fixed SurgeWall (frozen) not returning water to bottles
• Fixed WaterSpout not breaking when toggling bending
• Fixed EarthBlast not selecting sand correctly
=> Enough fixes for the year

src/com/projectkorra/projectkorra/ability/EarthAbility.java, src/com/projectkorra/projectkorra/configuration/ConfigManager.java, src/com/projectkorra/projectkorra/firebending/Illumination.java
RaiseEarth
* When using Raise Earth on gravel, it pulls up stone like how sand pulls up sandstone.
____________
Illumination
* Illumination now checks the lightlevel before placing the torch, so it only works in darkness.
____________
=> RaiseEarth works on gravel, Illumination only works in darkness

src/com/projectkorra/projectkorra/airbending/AirSwipe.java
• Fixed AirSwipe being able to release more AirSwipes while charing (now
just releases the charged one)
=> Fixed AirSwipe

src/com/projectkorra/projectkorra/PKListener.java, src/com/projectkorra/projectkorra/configuration/ConfigManager.java, src/com/projectkorra/projectkorra/earthbending/Tremorsense.java, src/com/projectkorra/projectkorra/firebending/FirePassive.java, src/com/projectkorra/projectkorra/firebending/Illumination.java, src/com/projectkorra/projectkorra/waterbending/WaterArms.java
Tremorsense
* Tremorsense now takes priority over Illumination.
______________
Illumination
* Added config value "Passive", which when set to false disables Illumination as a passive ability.
______________
WaterArms Spear
* When you hit an entity with the spear in water, ice now forms underwater.
______________
=> Tremorsense now takes priority over Illumination, IceSpear sphere now forms underwater

src/com/projectkorra/projectkorra/GeneralMethods.java, src/com/projectkorra/projectkorra/chiblocking/AcrobatStance.java, src/com/projectkorra/projectkorra/chiblocking/WarriorStance.java
Stance Abilities
* Added sounds when enabling and disabling Acrobat & Warrior Stance.
* When on the slot bound with Acrobat / Warrior Stance, if the ability is enabled it will be underlined to signify this.
__________________
=> Updates for Acrobat & Warrior Stance

src/com/projectkorra/projectkorra/PKListener.java, src/com/projectkorra/projectkorra/util/ParticleEffect.java, src/com/projectkorra/projectkorra/util/PassiveHandler.java
• Fixed Earth/PlantArmor potion effects blinking
• Fixed FallingDust particle having the wrong properties
• Fixed combos recording 2 right clicks when right clicking with nothing
in your hand (fixes FireWheel combo issue)
=> Minor fixes before release

src/com/projectkorra/projectkorra/command/ChooseCommand.java, src/com/projectkorra/projectkorra/command/VersionCommand.java
Replaced 1.9.4 Spigot .jar with 1.10.2
________
Commands
Choose
* Removed /b choose avatar
Version
* Updated /pk v
________
=> 1.8.0 for Minecraft v1.10

pom.xml
Adding this pom to the repo will merely make it easier for other developers that use maven (most bukkit devs are familiar with maven) to contribute, as it will automatically setup the workspace and all dependencies. This pom __will work with your existing file structure,__ and even if you don't use maven, this pom should not cause any issues for you to include in your repo.
(Of course, change the version if you plan on maintaining that.)
=> "mavenize"

src/com/projectkorra/projectkorra/GeneralMethods.java, src/com/projectkorra/projectkorra/PKListener.java, src/com/projectkorra/projectkorra/command/RemoveCommand.java, src/com/projectkorra/projectkorra/configuration/ConfigManager.java, src/com/projectkorra/projectkorra/earthbending/CollapseWall.java, src/com/projectkorra/projectkorra/earthbending/EarthArmor.java, src/com/projectkorra/projectkorra/earthbending/LavaSurgeWall.java, src/com/projectkorra/projectkorra/earthbending/MetalClips.java, src/com/projectkorra/projectkorra/earthbending/RaiseEarth.java, src/com/projectkorra/projectkorra/firebending/BlazeArc.java, src/com/projectkorra/projectkorra/firebending/FireBlastCharged.java, src/com/projectkorra/projectkorra/firebending/FireDamageTimer.java, src/com/projectkorra/projectkorra/util/ActionBar.java, src/com/projectkorra/projectkorra/util/PassiveHandler.java, src/com/projectkorra/projectkorra/util/TempArmor.java, src/com/projectkorra/projectkorra/waterbending/IceSpikePillar.java, src/com/projectkorra/projectkorra/waterbending/PlantArmor.java, src/com/projectkorra/projectkorra/waterbending/SurgeWall.java, src/com/projectkorra/projectkorra/waterbending/SurgeWave.java, src/com/projectkorra/projectkorra/waterbending/TorrentWave.java, src/com/projectkorra/projectkorra/waterbending/WaterCombo.java, src/com/projectkorra/projectkorra/waterbending/WaterReturn.java, src/com/projectkorra/projectkorra/waterbending/WaterSourceGrabber.java, src/com/projectkorra/projectkorra/waterbending/WaterSpoutWave.java, src/plugin.yml
• Rewritten GeneralMethods.getEntitiesAroundPoint - Now more effecient
and less draining on the server
• Rewritten EarthArmor - Now gives gold hearts instead of resistance.
• Added TempArmor class - Self explanitory
• Changed bottlebending permission from bending.ability.WaterReturn to
bending.ability.Bottlebending
• Fixed syntax when removing elements from youself
• Converted more ConcurrentHashMaps to be generic map types
=> 1.9.0 Changes

src/com/projectkorra/projectkorra/GeneralMethods.java, src/com/projectkorra/projectkorra/PKListener.java, src/com/projectkorra/projectkorra/airbending/AirBlast.java, src/com/projectkorra/projectkorra/airbending/AirCombo.java, src/com/projectkorra/projectkorra/airbending/AirSuction.java, src/com/projectkorra/projectkorra/airbending/Suffocate.java, src/com/projectkorra/projectkorra/airbending/Tornado.java, src/com/projectkorra/projectkorra/configuration/ConfigManager.java, src/com/projectkorra/projectkorra/earthbending/Catapult.java, src/com/projectkorra/projectkorra/earthbending/EarthGrab.java, src/com/projectkorra/projectkorra/earthbending/EarthSmash.java, src/com/projectkorra/projectkorra/earthbending/EarthTunnel.java, src/com/projectkorra/projectkorra/earthbending/LavaSurgeWave.java, src/com/projectkorra/projectkorra/earthbending/MetalClips.java, src/com/projectkorra/projectkorra/event/HorizontalVelocityChangeEvent.java, src/com/projectkorra/projectkorra/firebending/FireBlastCharged.java, src/com/projectkorra/projectkorra/firebending/FireShield.java, src/com/projectkorra/projectkorra/firebending/Lightning.java, src/com/projectkorra/projectkorra/util/BlockSource.java, src/com/projectkorra/projectkorra/util/ParticleEffect.java, src/com/projectkorra/projectkorra/waterbending/Bloodbending.java, src/com/projectkorra/projectkorra/waterbending/HealingWaters.java, src/com/projectkorra/projectkorra/waterbending/IceSpikePillar.java, src/com/projectkorra/projectkorra/waterbending/PhaseChangeFreeze.java, src/com/projectkorra/projectkorra/waterbending/WaterArms.java, src/com/projectkorra/projectkorra/waterbending/WaterArmsWhip.java, src/com/projectkorra/projectkorra/waterbending/WaterSpout.java, src/com/projectkorra/projectkorra/waterbending/WaterSpoutWave.java
Healing Waters not only begins to heal a target and display the heal effect when the blue particles reach them.
You can use Healing Waters from a bottle.
Fixes [this distance error](http://pastebin.com/3ARLs3e8) and any errors like it.
=> Add Changes to HealingWaters and Fix for Distance bug

src/com/projectkorra/projectkorra/chiblocking/AcrobatStance.java, src/com/projectkorra/projectkorra/chiblocking/WarriorStance.java
- https://github.com/ProjectKorra/ProjectKorra/issues/634
- Fixes the issue above
=> Fix acrobat/warrior stance disabling and switching

src/com/projectkorra/projectkorra/GeneralMethods.java
- no github issue open
- fixes IllegalArgumentException in distanceSquared if the locations worlds are different
=> Fixes an IllegalArgumentException

src/com/projectkorra/projectkorra/configuration/ConfigManager.java, src/com/projectkorra/projectkorra/earthbending/EarthArmor.java
• Added Grass paths to the Earthbendable list
• Added the colors of stained clay to earth armor
=> Small touchups

.gitignore
- Added dependency-reduced-pom.xml to gitignore
=> Add dependency-reduced-pom.xml to gitignore

src/com/projectkorra/projectkorra/command/BindCommand.java, src/com/projectkorra/projectkorra/waterbending/Bloodbending.java, src/com/projectkorra/projectkorra/waterbending/WaterArmsSpear.java, src/com/projectkorra/projectkorra/waterbending/WaterSpout.java
• Fixed Bloodbending not working
• Fixed WaterArms spear not working when you set "Sphere" to 0 in the
config
• Fixed the "null" message that occurs when binding an ability from an
element that has been toggled
• Attempted to fix WaterSpout NPE (needs testing)
=> Bug fixes - Whoop Whoop :D

src/com/projectkorra/projectkorra/PKListener.java, src/com/projectkorra/projectkorra/ProjectKorra.java, src/com/projectkorra/projectkorra/ability/FireAbility.java, src/com/projectkorra/projectkorra/firebending/FirebendingManager.java, src/com/projectkorra/projectkorra/firebending/HeatControl.java, src/com/projectkorra/projectkorra/util/TempBlock.java, src/com/projectkorra/projectkorra/waterbending/Torrent.java
HeatControl
* Fixed issues when automatically switching from one HeatControlType to another.
* Changed reversion system to use the TempBlock delayed reversion system.
________________
TempBlock
* Added new system to manage reverting blocks with a delay.
* Use TempBlock.setRevertTime(time_in_millis); to set the delay on reverting blocks.
* Use TempBlock.getRevertTime(); to get the time until reversion in milliseconds.
________________
Torrent
* Converted Torrent's reversion to use the new system mentioned above.
________________
=> Updated&Fixed HeatControl, added TempBlock delayed reversion

pom.xml, src/com/projectkorra/projectkorra/ability/util/CollisionManager.java, src/com/projectkorra/projectkorra/firebending/HeatControl.java
CollisionManager
* Check to make sure locationFirst and locationSecond are in the same world.
_____________
HeatControl
* Add a random factor to change the lava into stone/cobblestone.
_____________
=> Added CollisionManager world check - HeatControl solidify stone variation

src/com/projectkorra/projectkorra/ability/ElementalAbility.java, src/com/projectkorra/projectkorra/ability/util/CollisionInitializer.java
• Fixed AirShield not blocking FireBlast, EarthBlast and WaterManip
• Fixed an NPE in RPG
=> Fixed AirShield and NPE

src/com/projectkorra/projectkorra/ability/CoreAbility.java, src/com/projectkorra/projectkorra/command/DisplayCommand.java, src/com/projectkorra/projectkorra/waterbending/WaterManipulation.java
• Fixed NPEs in `CoreAbility.setPlayer`
• Turned off blocking for WaterManipulation
• Fixed /b display showing some moves twice
=> Fixed NPE & Other New Bugs

src/com/projectkorra/projectkorra/GeneralMethods.java, src/com/projectkorra/projectkorra/PKListener.java, src/com/projectkorra/projectkorra/ability/util/ComboManager.java, src/com/projectkorra/projectkorra/chiblocking/ChiCombo.java, src/com/projectkorra/projectkorra/chiblocking/HighJump.java, src/com/projectkorra/projectkorra/chiblocking/QuickStrike.java, src/com/projectkorra/projectkorra/earthbending/EarthTunnel.java, src/com/projectkorra/projectkorra/earthbending/LavaFlow.java
`EarthTunnel` can no longer remove Lava.
`EarthTunnel` now creates `TempBlocks` for snow and plants.
`LavaFlow` lava is now reverted correctly on reload.
`LavaFlow` can no longer spawn vast amounts of particles on/in water.
`LavaFlow` now creates `TempBlock`s for snow and plants properly.
Fixes `Immobilize` (wasn't static and therefore couldn't be accessed).
Combos now respect `CanBendWithWeapons` config flag.
=> Various Fixes with LavaFlow and EarthTunnel plus some Extra

pom.xml, src/com/projectkorra/projectkorra/PKListener.java
- Implements GlowAPI as a maven resource
- Implements a credit message displayed upon player join
=> Small Update

src/com/projectkorra/projectkorra/PKListener.java
- Delay sent join message to make it more visible and avoid clutter
=> Delay sent join message

extras/eclipse/BukkitPlugin.launch, src/com/projectkorra/projectkorra/PKListener.java, src/com/projectkorra/projectkorra/airbending/AirBlast.java, src/com/projectkorra/projectkorra/airbending/AirSpout.java, src/com/projectkorra/projectkorra/airbending/AirSuction.java, src/com/projectkorra/projectkorra/airbending/AirSwipe.java, src/com/projectkorra/projectkorra/configuration/ConfigManager.java, src/com/projectkorra/projectkorra/earthbending/Catapult.java, src/com/projectkorra/projectkorra/earthbending/Collapse.java, src/com/projectkorra/projectkorra/earthbending/CollapseWall.java, src/com/projectkorra/projectkorra/earthbending/EarthArmor.java, src/com/projectkorra/projectkorra/earthbending/EarthBlast.java, src/com/projectkorra/projectkorra/earthbending/EarthGrab.java, src/com/projectkorra/projectkorra/earthbending/EarthSmash.java, src/com/projectkorra/projectkorra/earthbending/EarthTunnel.java
- Fixed abilities not working
- Adds some new AvatarState config options
=> Bug fixes, AvatarState config options

pom.xml
=> Change up shaded sources

pom.xml
=> Re-implement maven shading

src/com/projectkorra/projectkorra/configuration/ConfigManager.java, src/com/projectkorra/projectkorra/waterbending/ice/PhaseChange.java
- Fixed npe
- Added sounds
- Melting tweaks
=> PhaseChange changes

src/com/projectkorra/projectkorra/PKListener.java, src/com/projectkorra/projectkorra/waterbending/WaterSpoutWave.java
* Fixed subelement death messages pulling information from subelement rather than it's parent element
=> Fixed Subelement death messages

src/com/projectkorra/projectkorra/command/HelpCommand.java, src/com/projectkorra/projectkorra/configuration/ConfigManager.java, src/com/projectkorra/projectkorra/firebending/HeatControl.java, src/com/projectkorra/projectkorra/waterbending/ice/PhaseChange.java, src/plugin.yml
Fixes PhaseChange and HeatControl being usable in protected regions.
Fixes "Usage: " displaying in bending help if no usage exists.
Removes PlantArmor config options and permissions.
=> Various Fixes and Removals

src/com/projectkorra/projectkorra/PKListener.java, src/com/projectkorra/projectkorra/configuration/ConfigManager.java, src/com/projectkorra/projectkorra/firebending/HeatControl.java, src/com/projectkorra/projectkorra/waterbending/WaterSpoutWave.java, src/com/projectkorra/projectkorra/waterbending/ice/IceSpikePillar.java, src/com/projectkorra/projectkorra/waterbending/util/WaterbendingManager.java
• Fixed IceSpike not using TempBlocks
• Fixed IceWave not automatically thawing the ice that freezes people
• Fixed EarthPassive (Soft landing) dropping sand blocks when the sand
is broken
• Made HeatControl a harmless ability if it's the Cook ability
=> IceSpike + Water Fixes

src/com/projectkorra/projectkorra/GeneralMethods.java, src/com/projectkorra/projectkorra/waterbending/SurgeWall.java, src/com/projectkorra/projectkorra/waterbending/multiabilities/WaterArms.java
* Removed unused imports in WaterArms and GeneralMethods
* Removed warnings in SurgeWall
=> Fixed MAJOR bugs

src/com/projectkorra/projectkorra/BendingPlayer.java, src/com/projectkorra/projectkorra/PKListener.java, src/com/projectkorra/projectkorra/ability/util/PassiveManager.java, src/com/projectkorra/projectkorra/airbending/passive/AirAgility.java, src/com/projectkorra/projectkorra/chiblocking/Paralyze.java, src/com/projectkorra/projectkorra/chiblocking/passive/ChiAgility.java, src/com/projectkorra/projectkorra/configuration/ConfigManager.java, src/com/projectkorra/projectkorra/earthbending/passive/EarthPassive.java, src/com/projectkorra/projectkorra/earthbending/passive/FerroControl.java, src/com/projectkorra/projectkorra/earthbending/passive/Hodor.java, src/com/projectkorra/projectkorra/earthbending/util/EarthbendingManager.java, src/com/projectkorra/projectkorra/util/PassiveHandler.java
* Added metal door passive
* Fixed passives being permanently disabled when somebody is chiblocked
* Fixed agility passives not detecting the largest modifier and using that instead
* Fixed passives getting toggled with /b t [element]
* Renamed AirAgilityPassive.class and ChiAgilityPassive.class to AirAgility.class and ChiAgility.class respectively
=> Passive fixes

src/com/projectkorra/projectkorra/earthbending/EarthGrab.java
* Fixed NPE
* https://trello.com/c/dLxpRATs/687-npe-on-earthgrab
* Added check to make sure the player is on the ground when using EarthGrab
* https://trello.com/c/crLjfceE/704-add-check-to-make-sure-that-the-person-is-on-the-ground-when-using-earthgrab
=> EarthGrab fixes

src/com/projectkorra/projectkorra/ProjectKorra.java, src/com/projectkorra/projectkorra/ability/CoreAbility.java, src/com/projectkorra/projectkorra/airbending/AirBlast.java, src/com/projectkorra/projectkorra/airbending/AirBubble.java, src/com/projectkorra/projectkorra/airbending/AirBurst.java, src/com/projectkorra/projectkorra/airbending/AirScooter.java, src/com/projectkorra/projectkorra/configuration/ConfigManager.java, src/com/projectkorra/projectkorra/util/Attribute.java, src/com/projectkorra/projectkorra/util/attributes/AttributeModifiers.java, src/com/projectkorra/projectkorra/util/attributes/AvatarStateModifier.java
* Begins Attribute implementation
* Fixes AirScooter
* Minor config fixes
=> Attributes, AirScooter fixes, Config fixes

src/com/projectkorra/projectkorra/Element.java, src/com/projectkorra/projectkorra/GeneralMethods.java, src/com/projectkorra/projectkorra/ability/CoreAbility.java, src/com/projectkorra/projectkorra/command/DisplayCommand.java, src/com/projectkorra/projectkorra/command/ToggleCommand.java, src/com/projectkorra/projectkorra/command/WhoCommand.java, src/com/projectkorra/projectkorra/object/HorizontalVelocityTracker.java
• Fixed CoreAbility.getAbilities() not returning addon abilities
• Fixed errors spammed from /b w when the server can't fetch the staff
list
• Fixed /b d passives - now displays all possible passives
• Fixed /b t <sub> causing an internal error
• Fixed a lot of NPEs
=> Few fixes here, here and maybe there

src/com/projectkorra/projectkorra/waterbending/Torrent.java, src/com/projectkorra/projectkorra/waterbending/ice/PhaseChange.java
Thanks to PhanaticD for reporting these issues.
=> Fixed memory issues with PhaseChange and Torrent.

src/com/projectkorra/projectkorra/PKListener.java, src/com/projectkorra/projectkorra/ability/WaterAbility.java, src/com/projectkorra/projectkorra/chiblocking/QuickStrike.java, src/com/projectkorra/projectkorra/configuration/ConfigManager.java, src/com/projectkorra/projectkorra/earthbending/Catapult.java, src/com/projectkorra/projectkorra/firebending/passive/FirePassive.java, src/com/projectkorra/projectkorra/util/TempBlock.java, src/com/projectkorra/projectkorra/waterbending/OctopusForm.java, src/com/projectkorra/projectkorra/waterbending/SurgeWall.java, src/com/projectkorra/projectkorra/waterbending/Torrent.java, src/com/projectkorra/projectkorra/waterbending/WaterSpoutWave.java, src/com/projectkorra/projectkorra/waterbending/ice/IceBlast.java
Here ya go Chris:
- Fix illumination
- Fix chi moves appearing to hit twice
- Fix plants being broken before being selected as a source
- Implement catapult 2.0
=> Alex's Awesome Update

src/com/projectkorra/projectkorra/GeneralMethods.java, src/com/projectkorra/projectkorra/ability/CoreAbility.java
* Adds collision system to reload
* Adds passive system to reload
* Adds clearing of ability by class map
=> Reload changes

src/com/projectkorra/projectkorra/waterbending/OctopusForm.java, src/com/projectkorra/projectkorra/waterbending/ice/PhaseChange.java
* Fixed water under not being frozen
=> Fix OctopusForm

src/com/projectkorra/projectkorra/GeneralMethods.java
Due to plugins that depend on ProjectKorra loading in AFTER pk, when a
BendingPlayer object is created, all the external elements, subelements
or abilities the player may have are lost because they are caught in the null
checks.
To work around this, we will continuously loop every second for 30
seconds until the request times out. If any elements/abilities the user
has haven't loaded in, in that time (the side plugin has taken longer
than 30 seconds to load), then it will time out and report it in the
console.
=> Fixed external elements, subelements and abilities not loading

src/com/projectkorra/projectkorra/PKListener.java, src/com/projectkorra/projectkorra/airbending/AirBlast.java, src/com/projectkorra/projectkorra/airbending/AirBurst.java, src/com/projectkorra/projectkorra/airbending/AirScooter.java, src/com/projectkorra/projectkorra/airbending/AirShield.java, src/com/projectkorra/projectkorra/airbending/AirSpout.java, src/com/projectkorra/projectkorra/airbending/AirSuction.java, src/com/projectkorra/projectkorra/airbending/AirSwipe.java, src/com/projectkorra/projectkorra/airbending/Suffocate.java, src/com/projectkorra/projectkorra/airbending/Tornado.java, src/com/projectkorra/projectkorra/airbending/combo/AirCombo.java, src/com/projectkorra/projectkorra/airbending/flight/AirFlight.java, src/com/projectkorra/projectkorra/attribute/Attribute.java, src/com/projectkorra/projectkorra/attribute/AttributeModifier.java, src/com/projectkorra/projectkorra/attribute/Attributes.java, src/com/projectkorra/projectkorra/avatar/AvatarState.java, src/com/projectkorra/projectkorra/chiblocking/HighJump.java, src/com/projectkorra/projectkorra/chiblocking/Paralyze.java, src/com/projectkorra/projectkorra/chiblocking/QuickStrike.java, src/com/projectkorra/projectkorra/chiblocking/RapidPunch.java, src/com/projectkorra/projectkorra/chiblocking/Smokescreen.java, src/com/projectkorra/projectkorra/chiblocking/SwiftKick.java, src/com/projectkorra/projectkorra/event/AttributeModifyEvent.java, src/com/projectkorra/projectkorra/util/ParticleEffect.java
• New Attribute System (WIP)
• Fields should now be marked with @Attribute(Attribute.DAMAGE) or
whatever the relevant attribute is.
• If the Attribute you want is not there, you can provide a string
instead
• At runtime, these Attributes can be changed with
Attributes.modify(ability/element, attribute, modifier)
• Air and Chi have all been marked with @Attribute annotations
• Updated Particlelib - Fixed bug with dragonbreath and endRod particles
being wrong. AND added new 1.11 particles.
=> New Attribute System

src/com/projectkorra/projectkorra/waterbending/OctopusForm.java
- Errors discovered on my own testing
- adding blocks async causes some bad problems
=> Adding blocks to the world async is not allowed

src/com/projectkorra/projectkorra/command/ToggleCommand.java
=> fixed passives not enabling on /bend toggle all

src/com/projectkorra/projectkorra/GeneralMethods.java, src/com/projectkorra/projectkorra/PKListener.java
- https://trello.com/c/wtsHxqZN/706-torrent-spectator
- https://trello.com/c/2ZXoqjxg/764-playerinteractevent-nullpointerexception
=> Fix spectator target

src/com/projectkorra/projectkorra/BendingPlayer.java, src/com/projectkorra/projectkorra/earthbending/lava/LavaFlow.java, src/com/projectkorra/projectkorra/util/ParticleEffect.java, src/com/projectkorra/projectkorra/waterbending/Torrent.java
- https://trello.com/c/4vxyx15p/756-airscooter-error
- https://github.com/ProjectKorra/ProjectKorra/issues/651
This fixes some frequent exceptions that would occur on the server I play on.
- Fixes exception when sending particles.
- Fixes exception with LavaFlow.
- Fixes exception with Torrent.
- Fixes exception when trying to add cooldown to null player.
=> Fix exceptions

src/com/projectkorra/projectkorra/BendingPlayer.java, src/com/projectkorra/projectkorra/configuration/ConfigManager.java, src/com/projectkorra/projectkorra/earthbending/EarthArmor.java, src/com/projectkorra/projectkorra/waterbending/ice/PhaseChange.java
• Delay option changed to speed
• Fixed EarthArmor breaking when a player is paralyzed.
=> PhaseChange Speed option added

src/com/projectkorra/projectkorra/BendingPlayer.java, src/com/projectkorra/projectkorra/airbending/AirSpout.java, src/com/projectkorra/projectkorra/airbending/AirSuction.java, src/com/projectkorra/projectkorra/configuration/ConfigManager.java, src/com/projectkorra/projectkorra/earthbending/Catapult.java, src/com/projectkorra/projectkorra/firebending/Illumination.java, src/com/projectkorra/projectkorra/firebending/passive/FirePassive.java, src/com/projectkorra/projectkorra/waterbending/OctopusForm.java
* Fixed Catapult being able to activate whenever
* Fixed Catapult angle problems
* Fixed Catapult bug with double jump
* Added Catapult option to cancel jump if incorrect angle
* Fixed Illumination blinking and false passive option
* Fixed Config paths and connected Abilities
* Fixed water flooding
* Miscellaneous formatting and code cleaning
* Config values for Toby
=> Bug Fixes (Catapult, Illumination, Config)

src/com/projectkorra/projectkorra/earthbending/lava/LavaFlow.java
* Fixed "AllowNaturalFlow" for LavaFlow
=> Fix LavaFlow

pom.xml, src/com/projectkorra/projectkorra/ability/CoreAbility.java, src/com/projectkorra/projectkorra/ability/util/AbilityLoader.java, src/com/projectkorra/projectkorra/ability/util/AddonAbilityLoader.java, src/com/projectkorra/projectkorra/earthbending/lava/LavaSurge.java, src/com/projectkorra/projectkorra/earthbending/lava/LavaSurgeWall.java, src/com/projectkorra/projectkorra/earthbending/lava/LavaSurgeWave.java, src/com/projectkorra/projectkorra/waterbending/WaterBubble.java, src/com/projectkorra/projectkorra/waterbending/ice/IceBlast.java, src/com/projectkorra/projectkorra/waterbending/ice/IceSpikeBlast.java, src/com/projectkorra/projectkorra/waterbending/ice/IceSpikePillarField.java, src/com/projectkorra/projectkorra/waterbending/ice/PhaseChange.java
• Redone the (core) ability load system - The old one broke with the
Guava update in 1.12
• Fixed some WaterBubble floods
• Fixed PhaseChange melting snow super duper fast
• Fixed some other misc bugs
• Added 1.12 Spigot to classpath
=> Updated to 1.12 with bug fixes for days

src/com/projectkorra/projectkorra/GeneralMethods.java, src/com/projectkorra/projectkorra/ability/WaterAbility.java, src/com/projectkorra/projectkorra/ability/util/CollisionManager.java, src/com/projectkorra/projectkorra/configuration/ConfigManager.java, src/com/projectkorra/projectkorra/earthbending/passive/EarthPassive.java, src/com/projectkorra/projectkorra/firebending/FireManipulation.java, src/com/projectkorra/projectkorra/waterbending/ice/IceBlast.java, src/com/projectkorra/projectkorra/waterbending/ice/IceSpikeBlast.java
• Fixed selecting snow blocks as a water source not working when they
are more than 3 blocks away
• Fixed DensityShift turning lava into sand when you land softly
• Fixed IceBlast not working on TempBlocks
• Added FireManip particle options to config
• Also removed a sneaky debug message
=> 1.8.4 Fixes

src/com/projectkorra/projectkorra/airbending/AirShield.java, src/com/projectkorra/projectkorra/airbending/AirSpout.java, src/com/projectkorra/projectkorra/airbending/Tornado.java, src/com/projectkorra/projectkorra/chiblocking/AcrobatStance.java, src/com/projectkorra/projectkorra/chiblocking/WarriorStance.java, src/com/projectkorra/projectkorra/configuration/ConfigManager.java, src/com/projectkorra/projectkorra/earthbending/EarthArmor.java, src/com/projectkorra/projectkorra/earthbending/EarthTunnel.java, src/com/projectkorra/projectkorra/earthbending/sand/SandSpout.java, src/com/projectkorra/projectkorra/firebending/combo/FireSpin.java, src/com/projectkorra/projectkorra/waterbending/healing/HealingWaters.java
- Adds cooldown capability to most abilities
- Fixes FireSpin working underwater
- Fixes EarthArmor not obeying cooldowns
- Removes an extraneous remove();
- Cooldown is now applied after the ability reaches the maxDuration as to truly reflect the cooldown value.
=> Cooldowns and Bug Fixes

src/com/projectkorra/projectkorra/GeneralMethods.java, src/com/projectkorra/projectkorra/PKListener.java, src/com/projectkorra/projectkorra/ability/EarthAbility.java, src/com/projectkorra/projectkorra/earthbending/EarthSmash.java, src/com/projectkorra/projectkorra/earthbending/passive/EarthPassive.java, src/com/projectkorra/projectkorra/firebending/combo/FireWheel.java, src/com/projectkorra/projectkorra/firebending/lightning/Lightning.java
* Fixed FireWheel bugs with looking down and hit location
* Fixed Lightning paralyze
* Made BendingPlayer creation run on a separate thread
=> Fix FireWheel and Lightning, BPlayer Creation

src/com/projectkorra/projectkorra/PKListener.java, src/com/projectkorra/projectkorra/chiblocking/RapidPunch.java, src/com/projectkorra/projectkorra/waterbending/multiabilities/WaterArms.java
* Fixed WaterArms sourcing
* Fixed WaterArms water not returning to bottle
* RapidPunch cooldown change
=> WaterArms fixes, RapidPunch cooldown

src/com/projectkorra/projectkorra/airbending/AirScooter.java, src/com/projectkorra/projectkorra/airbending/flight/AirFlight.java
- Fixes Flight deactivating on first iteration of progress while on the
ground
- Fixes AirScooters bounciness and inability to go up hills
=> AirScooter and Flight Fixes

src/com/projectkorra/projectkorra/BendingPlayer.java, src/com/projectkorra/projectkorra/ProjectKorra.java, src/com/projectkorra/projectkorra/command/BindCommand.java, src/com/projectkorra/projectkorra/command/DisplayCommand.java, src/com/projectkorra/projectkorra/command/HelpCommand.java, src/com/projectkorra/projectkorra/earthbending/CollapseWall.java, src/com/projectkorra/projectkorra/earthbending/RaiseEarthWall.java, src/com/projectkorra/projectkorra/earthbending/Ripple.java, src/com/projectkorra/projectkorra/firebending/BlazeArc.java, src/com/projectkorra/projectkorra/firebending/BlazeRing.java, src/com/projectkorra/projectkorra/firebending/FireBlastCharged.java, src/com/projectkorra/projectkorra/waterbending/SurgeWall.java, src/com/projectkorra/projectkorra/waterbending/SurgeWave.java, src/com/projectkorra/projectkorra/waterbending/TorrentWave.java, src/com/projectkorra/projectkorra/waterbending/WaterSpoutWave.java, src/com/projectkorra/projectkorra/waterbending/ice/IceSpikeBlast.java, src/com/projectkorra/projectkorra/waterbending/ice/IceSpikePillar.java, src/com/projectkorra/projectkorra/waterbending/multiabilities/WaterArmsFreeze.java, src/com/projectkorra/projectkorra/waterbending/multiabilities/WaterArmsSpear.java, src/com/projectkorra/projectkorra/waterbending/multiabilities/WaterArmsWhip.java
* Fixes certain abilities with sub-functionalities not working correctly. (New issue).
> * https://trello.com/c/sw6cw7BT/833-moves-with-multiple-functionalities-split-up-among-multiple-classes-create-multiple-occurrences-of-a-single-move-in-pk-help-and
* Fixes `/pk check` command URL
> * https://trello.com/c/x3MIw4Bl/843-update-the-update-checker-to-the-new-forum-link
=> Fix Sub-Ability ability permission issues & Check command URL

src/com/projectkorra/projectkorra/BendingPlayer.java, src/com/projectkorra/projectkorra/command/ToggleCommand.java
- https://trello.com/c/BXPNheIu/809-use-b-t-then-choose-element-b-ch-w-and-then-use-b-t-again-and-passives-will-not-work-until-b-reload
=> Fixed passives breaking when choosing an element with bending toggled

src/com/projectkorra/projectkorra/waterbending/WaterBubble.java
Fixes https://trello.com/c/P7E0lklH/836-waterbubble-removes-any-blocks-after-canceling
=> Fixed WaterBubble removing blocks placed by player in bubble

src/com/projectkorra/projectkorra/PKListener.java, src/com/projectkorra/projectkorra/event/AbilityCollisionEvent.java, src/com/projectkorra/projectkorra/event/AbilityEndEvent.java
* Added missing method in AbilityCollisionEvent and AbilityEndEvent
* Made EarthArmor remove on TeleportEvent
* Fixed checks to Illumination TempBlock map
=> Event methods, EarthArmor TP, Illumination checks

src/com/projectkorra/projectkorra/ability/EarthAbility.java, src/com/projectkorra/projectkorra/configuration/ConfigManager.java
Added LavaBending sound into EarthAbility and the ConfigManager. Works
in regular code using playLavabendingSound and is present in the
config.yml file
=> Added LavaBending Sound

src/com/projectkorra/projectkorra/waterbending/passive/FastSwim.java
- Adds cooldown logic to FastSwim.java
=> FastSwim Cooldown

src/com/projectkorra/projectkorra/firebending/combo/FireComboStream.java
I am somewhat sure this fixes this nullpointer: https://pastebin.com/raw/DVvqXWcw
=> make sure the combo only affects alive entities

src/com/projectkorra/projectkorra/ability/AirAbility.java, src/com/projectkorra/projectkorra/ability/AvatarAbility.java, src/com/projectkorra/projectkorra/ability/EarthAbility.java, src/com/projectkorra/projectkorra/ability/FireAbility.java, src/com/projectkorra/projectkorra/ability/WaterAbility.java, src/com/projectkorra/projectkorra/configuration/ConfigManager.java
* Adds exception handling to the configurable `Sound` options to prevent `IllegalArgumentExcpetions`.
> * https://trello.com/c/ePnrGrCw/867-add-exception-handling-to-sound-configuration
* Fixes `Earth.LavaSound`.
=> Add exception handling to configurable Sounds

src/com/projectkorra/projectkorra/PKListener.java
check if LivingEntity before casting
=> fix cast exception errors

src/com/projectkorra/projectkorra/BendingPlayer.java
double if statement, not needed.
* Removes redundant double if statement.
=> Removed Silly double if statement

src/com/projectkorra/projectkorra/BendingPlayer.java
* Adds `isBender` to `BendingPlayer`.
=> Add isBender to BendingPlayer

src/com/projectkorra/projectkorra/BendingPlayer.java
* Fixes Cooldowns being applied even though their time is zero, also prevents the cooldown change event from being fired.
=> Updated addCooldown() Method

src/com/projectkorra/projectkorra/configuration/ConfigManager.java
* Fixed spelling error in ConfigManager.java
=> Fix spelling error

src/com/projectkorra/projectkorra/waterbending/multiabilities/WaterArmsSpear.java
fixes private issue reported in slack
=> change check for if the block is placeable to before the block is placed

src/com/projectkorra/projectkorra/airbending/AirShield.java, src/com/projectkorra/projectkorra/airbending/AirSpout.java, src/com/projectkorra/projectkorra/airbending/Tornado.java, src/com/projectkorra/projectkorra/configuration/ConfigManager.java
* Adds duration values to AirShield, AirSpout, and Tornado.
> * .
* Fixes spelling and grammar errors in ConfigManager.
* Fixes incorrect path for HydroSink.java in ConfigManager.
=> Config Changes

src/com/projectkorra/projectkorra/configuration/ConfigManager.java
* Fixes some minor grammar issues within descriptions/texts.
* Changes death messages that say `experienced kinetic damage` to  `experienced a fatal collision`.
=> Grammar Fixes/Changes

src/com/projectkorra/projectkorra/ability/util/CollisionInitializer.java
* Changes AirShield to permit AirSwipe to pass through it.
> * https://trello.com/c/B4CdAfNV/876-airshield-blocks-airswipe
=> AirShield Change

src/com/projectkorra/projectkorra/BendingPlayer.java, src/com/projectkorra/projectkorra/ability/CoreAbility.java, src/com/projectkorra/projectkorra/ability/util/PassiveManager.java, src/com/projectkorra/projectkorra/airbending/passive/AirAgility.java, src/com/projectkorra/projectkorra/chiblocking/passive/ChiAgility.java, src/com/projectkorra/projectkorra/earthbending/passive/FerroControl.java, src/com/projectkorra/projectkorra/waterbending/passive/FastSwim.java
• Fixed the passives that weren't working (and cleaned up a lot of broken code for passive progression too). This includes FerroControl, FastSwim, AirAgility and ChiAgility
=> Fixed Passives

src/com/projectkorra/projectkorra/configuration/ConfigManager.java, src/com/projectkorra/projectkorra/firebending/FireManipulation.java
* Adds enable/disable option.
* Fixes FireManipulation being able to go through blocks.
> * https://trello.com/c/4kwGik0t/768-firemanip-bugs
=> FireManipulation edits and fixes

src/com/projectkorra/projectkorra/ability/EarthAbility.java, src/com/projectkorra/projectkorra/ability/WaterAbility.java, src/com/projectkorra/projectkorra/configuration/ConfigManager.java, src/com/projectkorra/projectkorra/util/BlockSource.java
https://trello.com/c/VCNbl9UR/897-add-water-earth-dynamic-sourcing-config-options
=> Added Water and Earth dynamic sourcing configurability

src/com/projectkorra/projectkorra/airbending/AirSuction.java
* Added mechanics to AirSuction to close doors
=> Finish airbending mechanics

src/com/projectkorra/projectkorra/GeneralMethods.java
no need to add a player to results if they are dead and will respawn (probably in some other location)
=> dont try to target dead players

src/com/projectkorra/projectkorra/earthbending/EarthTunnel.java
self explanatory, earth tunnel was not checking for protected regions
=> add protection checks to earthtunnel

src/com/projectkorra/projectkorra/airbending/AirBlast.java, src/com/projectkorra/projectkorra/earthbending/combo/EarthPillars.java, src/com/projectkorra/projectkorra/firebending/FireBlast.java, src/com/projectkorra/projectkorra/firebending/FireShield.java, src/com/projectkorra/projectkorra/firebending/combo/FireWheel.java
* AirBlast and FireBlast no longer go through diagonal walls
* EarthPillars:
> * User and targets must be on ground
> * Pillar must raise before affecting the target
> * Config mistakes
* FireShield duration less than or equal to 0 is infinite, and fire ticks
* FireWheel usability checks
=> Various bug fixes

src/com/projectkorra/projectkorra/PKListener.java, src/com/projectkorra/projectkorra/command/StatsCommand.java, src/com/projectkorra/projectkorra/command/WhoCommand.java, src/com/projectkorra/projectkorra/util/DamageHandler.java, src/com/projectkorra/projectkorra/util/Statistic.java
* Statistics
* Renamed KILLS to PLAYER_KILLS
* Renamed DAMAGE to PLAYER_DAMAGE
* Added TOTAL_KILLS
* Added TOTAL_DAMAGE
* Added name and displayName variables to Statistic enum
* name is used to identify the statistic from a command argument
* displayName is used when sending users statistic 
* Updated the staff URL in /b who to now use HTTPS
=> New statistics, fixed /b who

src/com/projectkorra/projectkorra/airbending/AirSpout.java, src/com/projectkorra/projectkorra/util/FlightHandler.java
* Removed unnecessary remove() call in AirSpout constructor
* Fixed NPE in FlightHandler
=> Fixed FlightHandler NPE

src/com/projectkorra/projectkorra/ProjectKorra.java, src/com/projectkorra/projectkorra/util/Updater.java
• Fixed the updater to make it work on the new forums
=> Fixed Updater

src/com/projectkorra/projectkorra/airbending/AirSwipe.java, src/com/projectkorra/projectkorra/util/FlightHandler.java
* Fixed flyglitch instances
* Changed FlightHandler to handle durations individually by the identifiers to prevent overlapping of separate duration (Eg. AirSpout and AirSwipe)
* Reduced AirSwipe Flight duration from 5000ms to 1000ms to prevent unnecessary Flight access
=> Fixed more flyglitch instances

src/com/projectkorra/projectkorra/firebending/combo/FireWheel.java, src/com/projectkorra/projectkorra/waterbending/multiabilities/WaterArms.java, src/com/projectkorra/projectkorra/waterbending/multiabilities/WaterArmsWhip.java
* Fixes FireWheel not always damaging
* Changed WaterArms to not go through tempblocks
=> WaterArms and FireWheel fixes

src/com/projectkorra/projectkorra/ability/CoreAbility.java, src/com/projectkorra/projectkorra/ability/WaterAbility.java, src/com/projectkorra/projectkorra/waterbending/SurgeWall.java, src/com/projectkorra/projectkorra/waterbending/WaterManipulation.java
* Fixes ability redirection breaking bottlebending for that player until server restart.
* Fixes WaterManipulation not working with bottles.
* Fixes Surge not working with bottles.
The Surge changes aren't great, but it seems to work. We have been using it on our server for a long time now with no problems. I would definitely recommend recoding Surge in the future though.
=> Fix bottlebending

src/com/projectkorra/projectkorra/GeneralMethods.java
* Fixes Passives not being removed when a player has their bending changed.
* Fixes MultiAbility instances not being removed when a player has their bending changed.
* Fixes player binds not being filtered properly if they are using a MultiAbility.
* https://trello.com/c/xdbB8gG4/922-generalmethodsremoveunusableabilities-method-does-not-function-properly
=> Fix removeUnusableAbilities() in GeneralMethods.

src/com/projectkorra/projectkorra/GeneralMethods.java, src/com/projectkorra/projectkorra/chiblocking/QuickStrike.java
* Fixes QuickStrike causing an endless chain of itself that never stops chiblocking and does no damage.
> * https://trello.com/c/FGK9TSmD/933-quickstrike-activates-an-endless-chain-of-itself-that-never-stops-and-deals-no-damage
=> Fixes QuickStrike causing an endless chain of itself

src/com/projectkorra/projectkorra/PKListener.java, src/com/projectkorra/projectkorra/ProjectKorra.java, src/com/projectkorra/projectkorra/configuration/ConfigManager.java, src/com/projectkorra/projectkorra/util/StatisticsManager.java, src/com/projectkorra/projectkorra/util/StatisticsMethods.java
* Adds a boolean under "Properties.Statistics" which can be used to disable the statistics system
* This has been implemented as statistics are still in alpha, and in the instance of issues occurring, we want to allow server administrators to disable the system
* More formatting changes because people don't know how to use the PK formatter apparently
=> Added config option for statistics

src/com/projectkorra/projectkorra/BendingManager.java, src/com/projectkorra/projectkorra/PKListener.java, src/com/projectkorra/projectkorra/earthbending/EarthArmor.java, src/com/projectkorra/projectkorra/earthbending/EarthGrab.java, src/com/projectkorra/projectkorra/earthbending/metal/MetalClips.java, src/com/projectkorra/projectkorra/util/TempArmor.java
* Fixes TempArmor concurrency duplication bugs
* Changes EarthGrab armor pieces to only appear if there isn't already armor on the entity for legs and feet
=> TempArmor fixes

src/com/projectkorra/projectkorra/chiblocking/AcrobatStance.java, src/com/projectkorra/projectkorra/chiblocking/WarriorStance.java, src/com/projectkorra/projectkorra/configuration/ConfigManager.java
* Adds duration value to AcrobatStance and WarriorStance.
=> Adds duration values to AcrobatStance and WarriorStance

src/com/projectkorra/projectkorra/ability/CoreAbility.java, src/com/projectkorra/projectkorra/airbending/combo/AirStream.java, src/com/projectkorra/projectkorra/airbending/combo/AirSweep.java, src/com/projectkorra/projectkorra/airbending/combo/Twister.java, src/com/projectkorra/projectkorra/chiblocking/combo/Immobilize.java, src/com/projectkorra/projectkorra/configuration/ConfigManager.java, src/com/projectkorra/projectkorra/earthbending/combo/EarthDomeSelf.java, src/com/projectkorra/projectkorra/earthbending/combo/EarthPillars.java, src/com/projectkorra/projectkorra/firebending/combo/FireKick.java, src/com/projectkorra/projectkorra/firebending/combo/FireSpin.java, src/com/projectkorra/projectkorra/firebending/combo/FireWheel.java, src/com/projectkorra/projectkorra/firebending/combo/JetBlast.java, src/com/projectkorra/projectkorra/firebending/combo/JetBlaze.java, src/com/projectkorra/projectkorra/waterbending/combo/IceBullet.java, src/com/projectkorra/projectkorra/waterbending/combo/IceWave.java
• Moved all hardcoded values to the config
• Changed default getInstructions() method to change the path if it's a combo to get the correct configuration value
=> Made Combos Translatable

src/com/projectkorra/projectkorra/PKListener.java, src/com/projectkorra/projectkorra/earthbending/EarthTunnel.java, src/com/projectkorra/projectkorra/earthbending/util/EarthbendingManager.java
* Made changes to earthtunnel to properly use TempBlock
=> earthtunnel changes

src/com/projectkorra/projectkorra/hooks/WorldGuardFlag.java, src/com/projectkorra/projectkorra/util/TempBlock.java
* Changes exception for worldguard bending flag
* Skip jukeboxes for tempblocks
=> catch any exception for custom worldguard flag register

src/com/projectkorra/projectkorra/BendingPlayer.java, src/com/projectkorra/projectkorra/firebending/FireBlast.java
* Fixes FireBlast not using it's FlameParticleRadius and SmokeParticleRadius config values.
=> fixes FireBlast ignoring config values

src/com/projectkorra/projectkorra/GeneralMethods.java
* Fixes infinite recursion in `GeneralMethods#getTargetedLocation(Player, int)`
=> Fix GeneralMethods#getTargetedLocation(Player, int)

src/com/projectkorra/projectkorra/firebending/FireBlastCharged.java
* Fixes Charged FireBlast radius being too big
* Fixes Charged FireBlast cooldown happening without using the ability
=> Fix Charged FireBlast radius and cooldown

src/com/projectkorra/projectkorra/ability/EarthAbility.java, src/com/projectkorra/projectkorra/earthbending/Collapse.java
* Fixes recursive calls to `EarthAbility#revertBlock(Block)`
=> Remove revertBlock recursive calls in EarthAbility and Collapse

src/com/projectkorra/projectkorra/attribute/AttributeModifier.java, src/com/projectkorra/projectkorra/firebending/FireBlast.java, src/com/projectkorra/projectkorra/firebending/FireBurst.java
Fill in whatever sections apply, feel free to remove any others. :thumbsup:
* Fixed FireBurst to appear as a single blast rather than multiple FireBlasts
* Changed AttributeModifierMethod division by zero check to not use Validate
=> Fix FireBurst Particles Fragmenting

src/com/projectkorra/projectkorra/command/HelpCommand.java, src/com/projectkorra/projectkorra/configuration/ConfigManager.java
* Fixes NPE in help command by removing unnecessary side-plugin usage strings.
=> Fix NPE in Help Command

pom.xml, src/plugin.yml
* Changes/Updates API versions.
=> updated API versions

src/com/projectkorra/projectkorra/PKListener.java
* Fixes some left-click abilities being triggered by dropping an item.
> * #1048
=> Fix abilities being triggered by dropping items

src/com/projectkorra/projectkorra/PKListener.java, src/com/projectkorra/projectkorra/ability/ElementalAbility.java, src/com/projectkorra/projectkorra/airbending/AirBlast.java, src/com/projectkorra/projectkorra/command/PresetCommand.java, src/com/projectkorra/projectkorra/configuration/ConfigManager.java, src/com/projectkorra/projectkorra/earthbending/EarthGrab.java
* Fixes AirBlast same origin & destination erroring.
* Fixes invalid preset name throwing NPE
* Fixes Phasechange duplication glitch
* Fixes EarthGrab duplication glitch
* Fixes ChatPrefix not correctly displaying Avatar for those w/ multiple
elements.
=> 1.16.1 Release Bug Fixes

src/com/projectkorra/projectkorra/GeneralMethods.java, src/com/projectkorra/projectkorra/PKListener.java, src/com/projectkorra/projectkorra/airbending/AirBlast.java, src/com/projectkorra/projectkorra/airbending/Suffocate.java, src/com/projectkorra/projectkorra/hooks/PlaceholderAPIHook.java, src/com/projectkorra/projectkorra/hooks/WorldGuardFlag.java, src/com/projectkorra/projectkorra/waterbending/multiabilities/WaterArmsSpear.java
* Fixes the `/pk debug` command causing `ClassNotFoundException` and `NoClassDefFoundError` due to missing hook dependencies in the compiled jar.
Credit goes to the authors of all of the changes below. I simply copy pasted them so that they can be directly committed to master rather than have to re-align the wip and master branches due to them not being synched.
* https://github.com/ProjectKorra/ProjectKorra/commit/e4f2f4fc8f4e73e1726dffbc830ae15f48292a4c
* https://github.com/ProjectKorra/ProjectKorra/commit/3cc64a22466d65931f364bc391705fddee4d46fe
* https://github.com/ProjectKorra/ProjectKorra/commit/b15374874184dfd9612cac7ff654c9ab2972c995
* https://github.com/ProjectKorra/ProjectKorra/commit/964de778d9eb943e826ae157594bda59d423aab2
=> Synchronizes master with wip and fixes debug command

src/com/projectkorra/projectkorra/GeneralMethods.java, src/com/projectkorra/projectkorra/PKListener.java, src/com/projectkorra/projectkorra/earthbending/EarthGrab.java, src/com/projectkorra/projectkorra/earthbending/metal/MetalClips.java, src/com/projectkorra/projectkorra/util/TempArmor.java
* Adds new methods to GeneralMethods involving armor Material checks.
* Fixes TempArmor duping glitches
=> Fix TempArmor Dupe

src/com/projectkorra/projectkorra/PKListener.java, src/com/projectkorra/projectkorra/command/WhoCommand.java, src/com/projectkorra/projectkorra/earthbending/Tremorsense.java, src/com/projectkorra/projectkorra/firebending/Illumination.java
* Fix Illumination torch duplication
* Fix Tremorsense activating on slabs
* Fix WhoCommand not displaying Blue Fire
=> PART 5: Golden Pull Request

src/com/projectkorra/projectkorra/PKListener.java, src/com/projectkorra/projectkorra/ability/ElementalAbility.java, src/com/projectkorra/projectkorra/command/WhoCommand.java, src/com/projectkorra/projectkorra/earthbending/Tremorsense.java, src/com/projectkorra/projectkorra/firebending/Illumination.java
* Fixes isFullMoon being off by 1
=> Fix isFullMoon

src/com/projectkorra/projectkorra/ability/CoreAbility.java
* Adds `GeneralMethods::getMovePreviewWithoutCooldownTimer(Player)`
=> Add getMovePreviewWithoutCooldownTimer

src/com/projectkorra/projectkorra/GeneralMethods.java, src/com/projectkorra/projectkorra/airbending/AirBlast.java, src/com/projectkorra/projectkorra/airbending/AirSwipe.java, src/com/projectkorra/projectkorra/configuration/ConfigManager.java, src/com/projectkorra/projectkorra/firebending/FireBlast.java
* Fix AirBlast, FireBlast, and AirSwipe going through walls
* Fix FireBurst not doing damage.
* Fix GeneralMethods#dropItems not checking for invalid drops.
* Reduce collision radii for most abilities..
=> Fix Outstanding Bugs

pom.xml
* Changes project version to 1.9 in pom.xml
=> Update pom.xml project version to 1.9

src/com/projectkorra/projectkorra/firebending/FireBlast.java
- Fixed an issue with FireBlast in which it ignores water and lava blocks, passing through them
- Closes #1098
=> Fix FireBlast going through liquids

src/com/projectkorra/projectkorra/earthbending/EarthGrab.java
=> Fix NPE in EarthGrab

src/com/projectkorra/projectkorra/board/BendingBoardInstance.java, src/com/projectkorra/projectkorra/command/ChooseCommand.java
* Fixes bending board not updating properly after the choose command
* Changes "Slot" bending board header to "Abilities"
* Changes board line color from GRAY to DARK_GRAY
=> Fix board update issue with choose command

pom.xml, src/com/projectkorra/projectkorra/GeneralMethods.java
* Updates Towny dependency in accordance with the TownyAdvanced plugin's specifications, which can be found here: https://github.com/TownyAdvanced/Towny/wiki/TownyAPI#checking-if-a-player-can-builddestroy-somewhere
* People who have the Towny Build permission will be able to bend in Towny land
=> Update Towny dependency

src/com/projectkorra/projectkorra/board/BendingBoardInstance.java, src/com/projectkorra/projectkorra/command/ChooseCommand.java, src/com/projectkorra/projectkorra/firebending/combo/FireComboStream.java
* Fixes FireStreamCombo causing IllegalArgumentException in GeneralMethods by indirectly calling getNearbyEntities with an infinite value.
=> Fix FireComboStream going infinite

src/com/projectkorra/projectkorra/firebending/FireBlast.java, src/com/projectkorra/projectkorra/firebending/FireBlastCharged.java, src/com/projectkorra/projectkorra/firebending/WallOfFire.java
* Fixes issue with damage modifiers being truncated to 0 due to being integer types.
> * Fixes #1108
=> Fix modifiers not being applied

src/com/projectkorra/projectkorra/ability/FireAbility.java, src/com/projectkorra/projectkorra/firebending/FireBlast.java, src/com/projectkorra/projectkorra/firebending/FireBlastCharged.java, src/com/projectkorra/projectkorra/firebending/WallOfFire.java
* Fixes getDayFactor()
* Resolves an issue with daytime not being checked before applying the modifier
* Resolves issue of always returning 1 instead of the original value.
Credit to @Aztlon for pointing this out to me.
=> Fix getDayFactor() always applying incorrectly

src/com/projectkorra/projectkorra/board/BendingBoardManager.java
* Reloads no longer affect BoardManager's disabled players.
=> Cleanup board manager

src/com/projectkorra/projectkorra/waterbending/ice/PhaseChange.java
* Fixes snow melting throwing invalid argument exception in PhaseChange's melt function due to improper setting of block data.
> * Fixes #1115
=> Fix issue w/ snow layers

src/com/projectkorra/projectkorra/configuration/ConfigManager.java, src/com/projectkorra/projectkorra/earthbending/EarthSmash.java
* Adds a collision radius for EarthSmash `default: 2.5`
=> Add EarthSmash Hit Radius

src/com/projectkorra/projectkorra/BendingPlayer.java
* Fixes passive ability permissions not being verified for bendability of passive abilities.
> * Fixes #1091
=> Add ability permission to canBendPassive()

pom.xml, src/com/projectkorra/projectkorra/GeneralMethods.java
* **Updated KingdomsX** to latest version as of June 1, 2021: 1.10.19.1
* Unfortunately the previous version, 1.10.12.1, was just defective or something. @ChristopherWMM scratched our heads on trying to fix a ClassNotFoundException for hours, and it was just the version. Anyways, this one works!!
* **Refactored main config path** "Properties.RegionProtection.RespectKingdoms" to reflect earlier changes in ConfigManager.
* There were a few issues resulting from not fully updating this path everywhere it occurred, including those in GeneralMethods#isRegionProtectedFromBuildPostCache and GeneralMethods#runDebug
* **Updated invasion code** to reflect recent changes in KingdomsX's API.
* Land#getInvasion, which returned an Invasion object, has been changed to Land#getInvasions, a Map<UUID, …
=> Fix KingdomsX ClassNotFoundException

pom.xml, src/com/projectkorra/projectkorra/GeneralMethods.java
* Shaded in one class that seems to have been causing problems, KingdomPermission
* Removed some documentation blunders that showed up as errors on IntelliJ
=> Fix KingdomsX ClassNotFoundException (again)

pom.xml
=> Bump plugin version to 1.9.1

src/com/projectkorra/projectkorra/command/DisplayCommand.java
* Fixed the display command showing hidden combos and passives
=> Fix display command showing hidden combos and passives

.gitignore, pom.xml, src/com/projectkorra/projectkorra/util/DamageHandler.java
* Changes the noDamageTicks check in `DamageHandler#damageEntity(...)` to follow minecraft logic
=> Follow Minecraft DamageTicks Logic

src/com/projectkorra/projectkorra/command/DisplayCommand.java
* Fixes https://github.com/ProjectKorra/ProjectKorra/issues/1169
=> Fix passives not showing up in /b display

pom.xml
* Bumps version number from 1.9.2 to 1.9.3.
=> Update build version number

src/com/projectkorra/projectkorra/board/BendingBoard.java
* Fixes an issue with clearing the misc. slots on the BendingBoard where something in the extras section being removed from the board wouldn't properly move the slots below it, causing issues with further cooldowns added to that section.
=> Fix BendingBoard Misc Slot Clearing Issue

src/com/projectkorra/projectkorra/firebending/WallOfFire.java
* Fixed WallOfFire using its cooldown as its duration, and set it to properly utilize the duration variable.
* Removed the 'active' field variable and its associated getters/setters.
=> WallOfFire Cooldown/Duration fixes

pom.xml, src/com/projectkorra/projectkorra/PKListener.java, src/com/projectkorra/projectkorra/airbending/AirBlast.java, src/com/projectkorra/projectkorra/configuration/ConfigManager.java, src/com/projectkorra/projectkorra/earthbending/metal/Extraction.java
- Adds ability for AirBlast to extinguish campfires, candles, candle cakes.
- Changes Extraction to output raw ores and adds deepslate ores.
- Updates to 1.17 Spigot API.
- Fixes small issue with fall damage cancellation.
- Fixes Extraction not being cancelable.
- Fixes #1177.
=> Update Extraction and AirBlast functions for 1.17 and 1.18

pom.xml, src/com/projectkorra/projectkorra/GeneralMethods.java, src/com/projectkorra/projectkorra/configuration/ConfigManager.java, src/plugin.yml
- Adds protection support for [GriefDefender](https://www.spigotmc.org/resources/68900/).
=> Add GriefDefender support.

pom.xml, src/com/projectkorra/projectkorra/BendingManager.java, src/com/projectkorra/projectkorra/BendingPlayer.java, src/com/projectkorra/projectkorra/Element.java, src/com/projectkorra/projectkorra/GeneralMethods.java, src/com/projectkorra/projectkorra/Manager.java, src/com/projectkorra/projectkorra/OfflineBendingPlayer.java, src/com/projectkorra/projectkorra/PKListener.java, src/com/projectkorra/projectkorra/ProjectKorra.java, src/com/projectkorra/projectkorra/ability/PlantAbility.java, src/com/projectkorra/projectkorra/ability/util/PassiveManager.java, src/com/projectkorra/projectkorra/command/ToggleCommand.java, src/com/projectkorra/projectkorra/configuration/ConfigManager.java, src/com/projectkorra/projectkorra/event/AbilityDamageEntityEvent.java, src/com/projectkorra/projectkorra/event/EntityBendingDeathEvent.java, src/com/projectkorra/projectkorra/firebending/FireBlast.java, src/com/projectkorra/projectkorra/firebending/FireShield.java, src/com/projectkorra/projectkorra/firebending/WallOfFire.java, src/com/projectkorra/projectkorra/firebending/combo/FireComboStream.java, src/com/projectkorra/projectkorra/firebending/combo/FireWheel.java, src/com/projectkorra/projectkorra/firebending/util/FireDamageTimer.java, src/com/projectkorra/projectkorra/util/DamageHandler.java, src/com/projectkorra/projectkorra/waterbending/plant/PlantTether.java
Fill in whatever sections apply, feel free to remove any others. :thumbsup:
> Passive Toggling
> Plant Particle util
> FireDamage timer/wrong data being sent to events.
> Outdated maven dependencies
> Small syntactic changes.
=> Tyson update

src/com/projectkorra/projectkorra/GeneralMethods.java
* Updates deg -> radians conversion in GeneralMethods#getLeftSide() and GeneralMethods#getRightSide()
=> Fix radians conversion in GeneralMethods.java

src/com/projectkorra/projectkorra/OfflineBendingPlayer.java
Fix issue when bendingPlayer has only custom element not loading correctly from DB (#1228)
* Fixes
> * [Link to GitHub Issue(s)](https://github.com/ProjectKorra/ProjectKorra/issues/1228)
=> Fix (#1228)

src/com/projectkorra/projectkorra/waterbending/combo/IceWave.java
=> Fix IceWave remove() method.

jitpack.yml, src/com/projectkorra/projectkorra/BendingPlayer.java, src/com/projectkorra/projectkorra/OfflineBendingPlayer.java, src/com/projectkorra/projectkorra/ability/FireAbility.java, src/com/projectkorra/projectkorra/command/WhoCommand.java
- Fixes blue fire abilities causing errors
- Fixes the who command not showing chi passives
=> Fire and Who Command fixes

src/com/projectkorra/projectkorra/GeneralMethods.java
- Fixed missing cast when converting to radians.
=> Added missing cast when getting player sides

src/com/projectkorra/projectkorra/util/TempBlock.java, src/com/projectkorra/projectkorra/waterbending/ice/PhaseChange.java
Addition:
- PhaseChange now updates the state of Snowable blocks once melted
Fixes:
- [https://github.com/ProjectKorra/ProjectKorra/issues/1215](url)
=> PhaseChange now updates the state of Snowable blocks once melted

src/com/projectkorra/projectkorra/board/BendingBoardManager.java
Should fix 1240, untested as my Intellij just doesn't agree with PK
Fixes - https://github.com/ProjectKorra/ProjectKorra/issues/1240
=> Don't show bending board if the Player lacks Permission Node

pom.xml, src/com/projectkorra/projectkorra/GeneralMethods.java, src/com/projectkorra/projectkorra/ability/WaterAbility.java, src/com/projectkorra/projectkorra/command/WhoCommand.java, src/com/projectkorra/projectkorra/util/BlockSource.java, src/com/projectkorra/projectkorra/waterbending/OctopusForm.java, src/com/projectkorra/projectkorra/waterbending/SurgeWall.java, src/com/projectkorra/projectkorra/waterbending/SurgeWave.java, src/com/projectkorra/projectkorra/waterbending/Torrent.java, src/com/projectkorra/projectkorra/waterbending/WaterManipulation.java, src/com/projectkorra/projectkorra/waterbending/WaterSpoutWave.java, src/com/projectkorra/projectkorra/waterbending/healing/HealingWaters.java, src/com/projectkorra/projectkorra/waterbending/ice/IceSpikeBlast.java, src/com/projectkorra/projectkorra/waterbending/multiabilities/WaterArms.java, src/staff.txt
* Bendable water and powdered snow cauldrons.
> * In 1.16, isCauldron(block) should be used, as WATER_CAULDRON and POWDERED_SNOW_CAULDRON is not added until 1.17, and water data in cauldrons is checked using Levelled in 1.16
* New staff.txt
=> Cauldron bending and staff.txt

src/com/projectkorra/projectkorra/GeneralMethods.java, src/com/projectkorra/projectkorra/configuration/ConfigManager.java, src/com/projectkorra/projectkorra/waterbending/blood/Bloodbending.java
* Adds new config option to restricts Bloodbending against certain entities
* Configurable bloodless entities
* Bloodbending#getBloodlessEntities() returns an Iterable of bloodless entities
* Bloodbending#loadBloodlessFromConfig() reloads BLOODLESS_ENTITIES with current config
=> Bloodless bloodbending restriction

src/com/projectkorra/projectkorra/util/TempArmorStand.java
* Fixes TempArmorStand not adding instances to the static structure used to ensure they revert.
=> Fix TempArmorStand not tracking instances

src/com/projectkorra/projectkorra/BendingPlayer.java, src/com/projectkorra/projectkorra/GeneralMethods.java, src/com/projectkorra/projectkorra/PKListener.java, src/com/projectkorra/projectkorra/ability/ElementalAbility.java, src/com/projectkorra/projectkorra/command/WhoCommand.java, src/com/projectkorra/projectkorra/configuration/ConfigManager.java, src/com/projectkorra/projectkorra/firebending/Illumination.java, src/plugin.yml
- Added new illumination for 1.17+ using light blocks
- Old illumination still works on 1.16
- Added GeneralMethods#getOffHandLocation
- Fixed illumination passive not starting on login
- Fixed GeneralMethods#getMainHandLocation
- Removes `bending.donor` permission and display in `/pk who`
=> Add new Illumination and remove donor permission

src/staff.txt
* Changes the UUID for Sammycocobear to my UUID (bbakaa)
=> Updating staff.txt to fix my UUID and username

src/com/projectkorra/projectkorra/firebending/lightning/Lightning.java
- Fixes lightning being used on a waterlogged copper slab creating infinite water arcs. This pertains to #1311
=> Fix Lightning/copper crash interaction

core-legacy/pom.xml, core/pom.xml, core/src/com/projectkorra/projectkorra/ability/CoreAbility.java, jitpack.yml
* Adds `/..` to the local repo path in module `core` (Fixes core building)
* it was targeting the local module path instead of the parent path
* Removes the aikar repo from module `core` and the timings dependency from module `core-legacy`
* also removes unused imports from `CoreAbility` in `core` module, as they were the only usage of the depend
* depend was not actually used anywhere and was just causing build to fail
* Removes the incorrect comments in module `core-legacy`
=> Fix Build (And therefor jitpack)

core/src/com/projectkorra/projectkorra/BendingPlayer.java
=> addCooldown should use event.getCooldown()

core/src/com/projectkorra/projectkorra/configuration/ConfigManager.java
* Added `#terracotta` and `COAL_BLOCK` to the default config for Earthbendables
* Added `BAMBOO` and `BAMBOO_SAPLING` to the default config for Plantbendables
=> Update default bendables config

.gitignore, core/pom.xml, core/src/com/projectkorra/projectkorra/ProjectKorra.java, core/src/com/projectkorra/projectkorra/util/Metrics.java
- Updated bStats Metrics
- Fixed missing JSON dependency issue
- Updated PAPI dependency in the pom.xml
- Added settings.xml to gitignore
=> Updated bStats Metrics

core/pom.xml, core/src/com/projectkorra/projectkorra/event/AbilityRecalculateAttributeEvent.java
Updates Java to 21 and Minecraft to 1.20
=> Java 21, Minecraft 1.20

core/src/com/projectkorra/projectkorra/ability/AirAbility.java
* Refactored AirAbility.java to load airbending particle settings from config dynamically, replacing hard-coded if statements.
=> Make Airbending particles more configurable

core/pom.xml, core/src/com/projectkorra/projectkorra/configuration/ConfigManager.java, core/src/com/projectkorra/projectkorra/region/HuskTowns.java, core/src/com/projectkorra/projectkorra/region/RegionProtection.java, core/src/plugin.yml, jitpack.yml
* Added HuskTowns region protection compat.
> * Created a new class - HuskTowns.java - which hooks into the HuskTownsAPI to check whether an operation (ie. PvP or Block Break) is allowed within a town claim.
* Updated files to register/enable the new hook
> * Added a new default config line in CongfigManager for HuskTowns in the format of the other region protection hooks
> * Added HuskTowns to RegionProtection in the same format as the other region protection hooks
> * Added HuskTowns as a soft depend in plugin.yml
> * Added HuskTowns' Maven to the pom file
=> [Addition] HuskTowns Compat

core/src/com/projectkorra/projectkorra/waterbending/WaterManipulation.java
* WaterManipulation not applying damage while in AvatarState
> * https://github.com/ProjectKorra/ProjectKorra/issues/1352
=> Fix Damage not applying by WaterManip while in AvatarState
