ProjectKorra/ProjectKorra

src/com/projectkorra/ProjectKorra/Utilities/ParticleEffect.java
src/com/projectkorra/ProjectKorra/firebending/Cook.java
src/com/projectkorra/ProjectKorra/firebending/FireBlast.java
src/com/projectkorra/ProjectKorra/firebending/FireJet.java
src/com/projectkorra/ProjectKorra/firebending/FireShield.java
src/com/projectkorra/ProjectKorra/firebending/Fireball.java
src/com/projectkorra/ProjectKorra/firebending/WallOfFire.java
src/com/projectkorra/ProjectKorra/waterbending/Torrent.java

Updated the ParticleLib to account for high ranges:
- The particle library previously only allowed players within a 16 block radius to see a particle. The new version of the library lets us extend the range beyond that.  
- After some testing, the particle library only seems to have "16 blocks or less", or as far as the player has their render distance set. For now I set the range to be the latter option, but if it seems to cause intense FPS lag then we can lower it back down to the 16 block range.
- As a note: Minecraft has a maximum particle per chunk limit, which is why in the past we noticed weird (non fps, non tps) lag issues with Charged AirBurst. The AirBurst would just seem to freeze up an entire chunk of a server, but players outside of that chunk were completely unaffected. I …

Updated the ParticleLib to allow for increased render distance

---

src/com/projectkorra/ProjectKorra/ConfigManager.java
src/com/projectkorra/ProjectKorra/Methods.java
src/com/projectkorra/ProjectKorra/ProjectKorra.java
src/com/projectkorra/ProjectKorra/airbending/AirBlast.java
src/com/projectkorra/ProjectKorra/firebending/Lightning.java
src/com/projectkorra/ProjectKorra/waterbending/OctopusForm.java
src/config.yml

Major Performance Improvement:
*IMPORTANT If you are a server owner please read*
- A new config option has been added called CacheBlockTime (default 5 seconds). If your server has specific regions that toggle bending off and on multiple times within the span of a few minutes, such as a custom ProBendingArena or Agni Kai Arena, you will probably want to keep the CacheBlockTime less than 3 seconds. If you disable bending in an area it will take up to CacheBlockTime to update.
- If your server does not have any of these areas that constantly deny or allow bending then you should increase the CacheBlockTime to 30 seconds or so.
- The Block Cache makes it so the server does not have to keep processing the same block multiple times in a row. For example, imagine you used PhaseChange, the block …

Performance Block Cache, AirBlast bug fix, Lightning Water Arc Fix

---

src/com/projectkorra/ProjectKorra/Ability/AbilityModuleManager.java

* Surrounded AbilityModule loading with a try catch of AbstractMethodError
* This error is caused by the update on AbilityModule 7684931 . All Custom Abilities are forced to update, if not they will cause AbstractMethodError
* This PR address's that issue and instead disables the Custom Ability providing an error message of
"The ability " + ab.getName() + " is either broken or outdated. Please remove it!"
* A delayed task is used to prevent ConcurrentModificationException while removing ability from maps and lists
* Plugin will continue to work while totally ignoring broken plugins
* UPDATE - removed printstacktrace to prevent spam

Stops ProjectKorra from not working due to broken custom abilities

---

src/com/projectkorra/ProjectKorra/ConfigManager.java
src/com/projectkorra/ProjectKorra/Methods.java
src/com/projectkorra/ProjectKorra/PKListener.java
src/com/projectkorra/ProjectKorra/airbending/AirCombo.java
src/com/projectkorra/ProjectKorra/airbending/FlightAbility.java
src/com/projectkorra/ProjectKorra/airbending/Suffocate.java
src/com/projectkorra/ProjectKorra/chiblocking/ChiblockingManager.java
src/com/projectkorra/ProjectKorra/earthbending/EarthSmash.java
src/com/projectkorra/ProjectKorra/earthbending/Extraction.java
src/com/projectkorra/ProjectKorra/firebending/FireCombo.java
src/com/projectkorra/ProjectKorra/firebending/Lightning.java
src/com/projectkorra/ProjectKorra/waterbending/WaterCombo.java
src/config.yml

WorldGuard Fix:
- A backward conditional was causing problems with Lightning, Combustion, FireBlast, and Blaze, in the isRegionProtectedFromBuild Method.
Reworked Ability: Suffocate
* Note * Delete the old Suffocate entry from your config.yml
- Suffocate has been replaced by the addon version: Suffocate2
- The main difference between the two versions is that the new Suffocate applies a configurable Blind and Slow potion effect, as well as the normal damage.
Methods - isRegionProtectedByBuild BlockCache now considers the ability name:
- A problem was occuring with the BlockCache due to the fact that passive abilities are always allowed to be used. The Cache now checks and saves the name of the ability that was sent to the isRegionProtectedByBUild Method.
- This fixed the problem that was …

Suffocation Rework and Bug Fixes

---

.gitignore
out/production/ProjectKorra/plugin.yml
src/com/projectkorra/ProjectKorra/Ability/Combo/ComboAbilityModule.java
src/com/projectkorra/ProjectKorra/Ability/Combo/ComboModuleManager.java
src/com/projectkorra/ProjectKorra/ComboManager.java
src/com/projectkorra/ProjectKorra/Commands.java
src/com/projectkorra/ProjectKorra/ConfigManager.java
src/com/projectkorra/ProjectKorra/Methods.java
src/com/projectkorra/ProjectKorra/Objects/HorizontalVelocityTracker.java
src/com/projectkorra/ProjectKorra/PKListener.java
src/com/projectkorra/ProjectKorra/ProjectKorra.java
src/com/projectkorra/ProjectKorra/Utilities/HorizontalVelocityChangeEvent.java
src/com/projectkorra/ProjectKorra/airbending/AirBlast.java
src/com/projectkorra/ProjectKorra/waterbending/Bloodbending.java

Added a `distance` variable to the `HorizontalVelocityChangedEvent`, and thus also in `HorizontalVelocityTracker` to refer to the distance traveled in the air.
Also added a check to cancel velocity tracking should the entity come into contact with water.
Finally, rewrote the wall damage equation to implement a minimum distance to be traveled as well as overall distance traveled. The equation is now: 
```Java
double minimumDistance = plugin.getConfig().getDouble("Properties.HorizontalCollisionPhysics.WallDamageMinimumDistance");
double damage = ((e.getDistanceTraveled() - minimumDistance) < 0 ? 0 : e.getDistanceTraveled() - minimumDistance) / (e.getDifference().length());
Methods.damageEntity(e.getInstigator(), e.getEntity(), damage);
```
This equation's typical output for Airblast is 4 to …

Added a ComboAddonAPI and fixed some bugs with HorizontalCollision Damage

---

src/com/projectkorra/ProjectKorra/Commands.java

Line 792 was causing SQLException: "Before start of result set". Fixed by placing the call to result set in the for loop, which insures that the string calling of "uuid" will work.

Updated Commands.java

---

src/com/projectkorra/ProjectKorra/Methods.java
src/com/projectkorra/ProjectKorra/airbending/Tornado.java
src/com/projectkorra/ProjectKorra/earthbending/EarthPassive.java
src/com/projectkorra/ProjectKorra/earthbending/EarthTunnel.java
src/com/projectkorra/ProjectKorra/earthbending/Extraction.java
src/com/projectkorra/ProjectKorra/firebending/Extinguish.java
src/com/projectkorra/ProjectKorra/firebending/HeatControl.java
src/com/projectkorra/ProjectKorra/firebending/Lightning.java
src/com/projectkorra/ProjectKorra/waterbending/IceSpike.java
src/com/projectkorra/ProjectKorra/waterbending/Melt.java
src/com/projectkorra/ProjectKorra/waterbending/WaterManipulation.java
src/com/projectkorra/ProjectKorra/waterbending/WaterSourceGrabber.java
src/com/projectkorra/ProjectKorra/waterbending/WaterWall.java
src/com/projectkorra/ProjectKorra/waterbending/WaterWave.java

* Change ```HashSet<Byte> null``` to ```HashSet<Material> null``` to remove deprecation caused by 9f969f1
* Remove annotations caused by 9f969f1
* Add unused annotation to ```full``` in Extinguish

Fix deprecation from 9f969f1, small clean up

---

src/com/projectkorra/ProjectKorra/ComboManager.java
src/com/projectkorra/ProjectKorra/PKListener.java
src/com/projectkorra/ProjectKorra/Utilities/BlockSource.java
src/com/projectkorra/ProjectKorra/Utilities/BlockSourceInformation.java
src/com/projectkorra/ProjectKorra/Utilities/ClickType.java
src/com/projectkorra/ProjectKorra/airbending/AirCombo.java
src/com/projectkorra/ProjectKorra/earthbending/Collapse.java
src/com/projectkorra/ProjectKorra/earthbending/CompactColumn.java
src/com/projectkorra/ProjectKorra/earthbending/EarthBlast.java
src/com/projectkorra/ProjectKorra/earthbending/EarthColumn.java
src/com/projectkorra/ProjectKorra/earthbending/EarthMethods.java
src/com/projectkorra/ProjectKorra/earthbending/EarthSmash.java
src/com/projectkorra/ProjectKorra/earthbending/EarthWall.java
src/com/projectkorra/ProjectKorra/earthbending/LavaFlow.java
src/com/projectkorra/ProjectKorra/earthbending/LavaSurge.java
src/com/projectkorra/ProjectKorra/earthbending/LavaWall.java
src/com/projectkorra/ProjectKorra/earthbending/LavaWave.java
src/com/projectkorra/ProjectKorra/firebending/FireCombo.java
src/com/projectkorra/ProjectKorra/waterbending/IceBlast.java
src/com/projectkorra/ProjectKorra/waterbending/IceSpike2.java
src/com/projectkorra/ProjectKorra/waterbending/OctopusForm.java
src/com/projectkorra/ProjectKorra/waterbending/Torrent.java
src/com/projectkorra/ProjectKorra/waterbending/WaterCombo.java
src/com/projectkorra/ProjectKorra/waterbending/WaterManipulation.java
src/com/projectkorra/ProjectKorra/waterbending/WaterMethods.java
src/com/projectkorra/ProjectKorra/waterbending/WaterWall.java
src/com/projectkorra/ProjectKorra/waterbending/WaterWave.java
src/com/projectkorra/ProjectKorra/waterbending/Wave.java

Dynamic Water, Earth, and Lava Source Selection:
- Source selection has been reworked to be more adaptable in certain situations. For example, a Water bender does not need to reselect sources just to use the same ability.
- Once a block is selected as a source, it will be saved until the player selects a different source for that particular element. If the user has multiple elements then they would be able to have a different source for each element.
- Sources now transfer between abilities. For example, if a user selects a block with WaterManipulation then switches to Torrent they can still use the same source block.
* Note: Although the Player does not have to reselect a source, they must perform the same sneak/left click actions that they normally would. For example, if a Player wants …

Dynamic Source Selection

---

src/com/projectkorra/ProjectKorra/Utilities/BlockSource.java
src/com/projectkorra/ProjectKorra/earthbending/EarthMethods.java
src/com/projectkorra/ProjectKorra/earthbending/EarthSmash.java

Improved earth dynamic sourcing:
- If an Earth source could not directly be found then dynamic sourcing will attempt to search for a nearby valid earth block to use instead.
EarthSmash no longer uses dynamic sourcing:
- EarthSmash was behaving weirdly with dynamic sourcing because it requires the user to release shift to activate the ability. EarthSmash has been reverted to its previous version.
BlockSource distance error fix:
- Fixed a bug that was causing errors with distance()

Earth Dynamic Sourcing Improvements

---

src/com/projectkorra/ProjectKorra/Ability/AbilityModuleManager.java
src/com/projectkorra/ProjectKorra/Ability/StockAbilities.java
src/com/projectkorra/ProjectKorra/ConfigManager.java
src/com/projectkorra/ProjectKorra/Flight.java
src/com/projectkorra/ProjectKorra/PKListener.java
src/com/projectkorra/ProjectKorra/earthbending/EarthMethods.java
src/com/projectkorra/ProjectKorra/earthbending/EarthbendingManager.java
src/com/projectkorra/ProjectKorra/earthbending/SandSpout.java
src/com/projectkorra/ProjectKorra/waterbending/IceBlast.java
src/plugin.yml

New sandbending move: SandSpout
Requires the user to have the sandbending subelement.
SandSpoutis slower and lower then AirSpout and WaterSpout by default.
Requires the player to be above sand/sandstone to use (like how waterspout relies on a water source)
Any players caught in the spout will be dealt small amounts of damage over time and will be blinded from standing in the whirlwind of sand.
Config options:
Height - Max height the spout can achieve. 
BlindnessTime - How long a player will be blinded for standing in a spout. (in seconds)
Spout Damage - How much damage the spout does over time for standing in it.
Slight Iceblast rework
Added default cooldown of 1.5 seconds.
Iceblast is now much less laggy and looks/acts nicer.
Added an on collision sound and effect.

Added SandSpout and made IceBlast less laggy!

---

src/com/projectkorra/ProjectKorra/Ability/AbilityModuleManager.java
src/com/projectkorra/ProjectKorra/Ability/StockAbilities.java
src/com/projectkorra/ProjectKorra/Flight.java
src/com/projectkorra/ProjectKorra/PKListener.java
src/com/projectkorra/ProjectKorra/configuration/ConfigManager.java
src/com/projectkorra/ProjectKorra/earthbending/EarthMethods.java
src/com/projectkorra/ProjectKorra/earthbending/EarthbendingManager.java
src/com/projectkorra/ProjectKorra/earthbending/SandSpout.java
src/com/projectkorra/ProjectKorra/waterbending/IceBlast.java
src/plugin.yml

New sandbending move: SandSpout
Requires the user to have the sandbending subelement.
SandSpoutis slower and lower then AirSpout and WaterSpout by default.
Requires the player to be above sand/sandstone to use (like how
waterspout relies on a water source)
Any players caught in the spout will be dealt small amounts of damage
over time and will be blinded from standing in the whirlwind of sand.
Config options:
Height - Max height the spout can achieve.
BlindnessTime - How long a player will be blinded for standing in a
spout. (in seconds)
Spout Damage - How much damage the spout does over time for standing in
it.
Slight Iceblast rework
Added default cooldown of 1.5 seconds.
Iceblast is now much less laggy and looks/acts nicer.
Added an on collision sound and effect.

Re-added Sandspout and IceBlast fixes

---

src/com/projectkorra/ProjectKorra/waterbending/WaterArms.java
src/com/projectkorra/ProjectKorra/waterbending/WaterArmsSpear.java
src/com/projectkorra/ProjectKorra/waterbending/WaterArmsWhip.java
src/com/projectkorra/ProjectKorra/waterbending/WaterManipulation.java

Fixed WaterArms causing flooding, a more thorough version of Runefist's fix.
Attempted to fix the WaterManipulation water being left on occasion, some blocks may be left but it's far less than it used to be.

Fixed WaterArms flooding and WaterManipulation bugs.

---

src/com/projectkorra/ProjectKorra/Commands.java
src/com/projectkorra/ProjectKorra/GeneralMethods.java
src/com/projectkorra/ProjectKorra/Objects/Preset.java
src/com/projectkorra/ProjectKorra/airbending/AirSwipe.java
src/com/projectkorra/ProjectKorra/earthbending/Catapult.java
src/com/projectkorra/ProjectKorra/earthbending/EarthArmor.java
src/com/projectkorra/ProjectKorra/earthbending/EarthBlast.java
src/com/projectkorra/ProjectKorra/earthbending/LavaWave.java
src/com/projectkorra/ProjectKorra/earthbending/Tremorsense.java
src/com/projectkorra/ProjectKorra/firebending/FireShield.java
src/com/projectkorra/ProjectKorra/firebending/Illumination.java
src/com/projectkorra/ProjectKorra/waterbending/WaterArms.java
src/com/projectkorra/ProjectKorra/waterbending/WaterManipulation.java
src/com/projectkorra/ProjectKorra/waterbending/WaterReturn.java
src/com/projectkorra/ProjectKorra/waterbending/Wave.java

* After further discussion it was decided that all == that were being used to compare worlds should be changed to .equals
* sqlite does not have the command "ON DUPLICATE KEY UPDATE" which is what presets is currently using to save
* Add check to see if database is sqlite, if so run different command
* Add some color to some of the messages in commands to emphasize the messages
* Change Bukkit.getPlayer(bPlayer.playerName) to Bukkit.getPlayer(bPlayer.uuid)
* Add missing .equalsIgnoreCase("null") to /bend display
READY TO BE PULLED

[BugFix] World compare, Preset, Illumination and minor fixes (Merge ready)

---

src/com/projectkorra/ProjectKorra/configuration/ConfigManager.java
src/com/projectkorra/ProjectKorra/earthbending/EarthMethods.java
src/com/projectkorra/ProjectKorra/earthbending/EarthPassive.java
src/com/projectkorra/ProjectKorra/earthbending/EarthbendingManager.java
src/com/projectkorra/ProjectKorra/earthbending/SandSpout.java

Added a spiral to the SandSpout ability, which can be turned on and off in the config file. The option can be found at "spiral" under SandSpout. Also added a boolean to the .displaySandParticle method. If set to true, it will spawn red sand and red sandstone particles instead of the normal yellow ones.

SandSpout + EarthMethods

---

src/com/projectkorra/ProjectKorra/DBConnection.java
src/com/projectkorra/ProjectKorra/GeneralMethods.java
src/com/projectkorra/ProjectKorra/ProjectKorra.java
src/com/projectkorra/ProjectKorra/Utilities/Updater.java
src/com/projectkorra/ProjectKorra/configuration/ConfigManager.java

* Remove config.options().copyDefaults(true); since it is already called when config.saveConfig() is called
* Fix spacing error in Updater
* Updated reloadPlugin()
* Now attempts to reload everything in the correct order
* Has safety checks where necessary and will disable the plugin upon failure
* Logs reloading messages
* Now reloads Presets
* Checks for update upon reload
* Generates a BendingReloadEvent upon the call of the method (was in an incorrect position before)
* Now reloads MultiAbilities
* Moved stopPlugin() to GeneralMethods and made it static

[BUGFIX] Remove extra code, Update reloadPlugin(), stopPlugin()

---

src/com/projectkorra/projectkorra/PKListener.java

- Added check for if player has a chi ability bound before chiblocking (as suggested by Loony), fixes abilities like WaterManipulation and others causing the hit player to be chiblocked.

Bug fix in chiblocking

---

src/com/projectkorra/projectkorra/earthbending/EarthBlast.java

Dynamic sourcing allowed earthblast to use blocks outside the prepare
range as a source

Fix EarthBlast using blocks outside range

---

src/com/projectkorra/projectkorra/GeneralMethods.java

Instead of outputting abilities in the order they're loaded, the command now outputs them alphabetically, first stock and then unofficial. This is to improve the readability of the command's output.

change /b debug output for readability

---

src/com/projectkorra/projectkorra/configuration/ConfigManager.java
src/com/projectkorra/projectkorra/firebending/Fireball.java

• Changed config option "Power" to "ExplosionRadius" for charged
fireblasts.
• Added new config option "DamageBlocks" for charged fireblasts
• Charged fireblasts can now set fire to more than one mob
• Fixed setting explosion radius to 0 still destroys blocks

FireBlast changes + Bug fix

---

src/com/projectkorra/projectkorra/airbending/AirBlast.java
src/com/projectkorra/projectkorra/configuration/ConfigManager.java
src/com/projectkorra/projectkorra/waterbending/Bloodbending.java

• Adds a CanFlickLever, CanOpenDoors, CanPushButtons and CanCoolLava options to AirBlast in the config. All of which default to true.
• Adds a CanBloodbendOtherBloodbenders option for Bloodbending in the config. Defaults to false.
• Fixes issues where AirBlast could flick levers, etc, in regions without explicit permission

Adds config options for Bloodbending and AirBlast

---

src/com/projectkorra/projectkorra/waterbending/WaterManipulation.java

When switching to a slot with no ability equipped while a WaterManip was active, the water would stop moving in mid air.

Fix WaterManipulation stalling on slot change

---

src/com/projectkorra/projectkorra/ability/AbilityModuleManager.java

* Instead of make the ability module manager handle specific errors have it handle all exceptions and remove it from system if stopped by an error on load
* This will cause the plugin to function normally if an addon fails to load or breaks

Make AbilityModuleManager handle all exceptions

---

src/com/projectkorra/projectkorra/PKListener.java
src/com/projectkorra/projectkorra/configuration/ConfigManager.java
src/com/projectkorra/projectkorra/firebending/FireBlast.java
src/com/projectkorra/projectkorra/firebending/FireJet.java
src/com/projectkorra/projectkorra/firebending/FireMethods.java
src/com/projectkorra/projectkorra/firebending/FireStream.java
src/com/projectkorra/projectkorra/firebending/Fireball.java
src/com/projectkorra/projectkorra/firebending/FirebendingManager.java

Fire has a new temporary block system that reverts back after the fire
either dissipates or is destroyed.
• New Config Setting: Properties.Fire.FireGriefing
• Fire will no longer replace blocks with this setting on, but instead
reverts as soon as the fire dissipates or is destroyed
• Defaults to false
• New Config Setting: Properties.Fire.RevertTicks
• Fire will automatically revert after so many ticks. This only applies
if FireGriefing is false, however.
• Fixed fire destroying blocks for good this time

Redone Temporary Fire

---

src/com/projectkorra/projectkorra/GeneralMethods.java
src/com/projectkorra/projectkorra/PKListener.java
src/com/projectkorra/projectkorra/airbending/AirBlast.java
src/com/projectkorra/projectkorra/airbending/AirShield.java
src/com/projectkorra/projectkorra/airbending/AirSuction.java
src/com/projectkorra/projectkorra/configuration/ConfigManager.java
src/com/projectkorra/projectkorra/earthbending/LavaFlow.java
src/com/projectkorra/projectkorra/firebending/Combustion.java
src/com/projectkorra/projectkorra/firebending/FireBlast.java
src/com/projectkorra/projectkorra/firebending/FireShield.java
src/com/projectkorra/projectkorra/firebending/Fireball.java
src/plugin.yml

Adds RemoveAroundPoint method for AirBlast and AirSuction.
Fixs what AirShield should be blocking.
Adds the ability for AirShield to put out all fire within it.
Reworks the amount of particles displayed by LavaFlow
Adds particles on LavaFlow shift charge
Reworks how combustion looks (more beamy, less bloby)
Fixs distance check so it can actually hit stuff
Reworks how FireBlast looks (more beamy, less bloby)
Reworks how charged FireBlast looks (little less bloby)
Fixs what FireShield should be blocking.
Adds Quarts Ore as an earthbendable block.
Adds the ability for FireShield to put out all fire within it.
Adds WallDamageCap config option (default at 4 dmg)
Enables full WaterArms by default.
Enables BloodBending on full moon by default.
Rebalances various config options (look for …

Various Changes/Fixes

---

src/com/projectkorra/projectkorra/PKListener.java
src/com/projectkorra/projectkorra/ability/AbilityModuleManager.java
src/com/projectkorra/projectkorra/command/ClearCommand.java
src/com/projectkorra/projectkorra/configuration/ConfigManager.java
src/com/projectkorra/projectkorra/earthbending/MetalClips.java
src/plugin.yml

- Fixes MetalClips errors:
- Only being able to metalclip one entity, even when hitting other
entities
- MetalClips stops working after killing targeted entity
- Removes unused imports and suppresswarnings
- Adds MetalClips throwing config option and permission, both false by default. Used when the
player is controlling an entity and clicks. (Recommended: Delete the
MetalClips description line in the config, then reload server)

MetalClips fix and miscellaneous

---

src/com/projectkorra/projectkorra/GeneralMethods.java

The /b debug command will now display the size of collections and maps for both public and private fields. Previously it only displayed public fields.

Update /b debug to display more variables

---

src/com/projectkorra/projectkorra/chiblocking/ChiPassive.java
src/com/projectkorra/projectkorra/chiblocking/QuickStrike.java
src/com/projectkorra/projectkorra/chiblocking/SwiftKick.java
src/com/projectkorra/projectkorra/configuration/ConfigManager.java
src/com/projectkorra/projectkorra/object/HorizontalVelocityTracker.java

- Removed unused Bukkit import in HorizontalVelocityTracker
- Fixed AcrobatStance config options
- Fixed ChiPassive config options
- Made SwiftKick and QuickStrike "ChiBlockChance" into passive augments
- Fixed willChiBlock method in ChiPassive, incorrect way of checking percent
- Add SwiftKick and QuickStrike augments to willChiBlock()
- Change SwiftKick and QuickStrike to use willChiBlock()

Fix ChiBlocking and Configurations, Remove import

---

src/com/projectkorra/projectkorra/GeneralMethods.java
src/com/projectkorra/projectkorra/PKListener.java
src/com/projectkorra/projectkorra/airbending/AirShield.java
src/com/projectkorra/projectkorra/airbending/AirSwipe.java
src/com/projectkorra/projectkorra/command/BendingTabComplete.java
src/com/projectkorra/projectkorra/command/PermaremoveCommand.java
src/com/projectkorra/projectkorra/command/ToggleCommand.java
src/com/projectkorra/projectkorra/firebending/FireStream.java
src/com/projectkorra/projectkorra/firebending/FirebendingManager.java
src/com/projectkorra/projectkorra/object/HorizontalVelocityTracker.java
src/plugin.yml

- Fixed AirShield not blocking earth and water abilities.
- Fixed AirSwipe stopping when it hit a non living entity
- Fixed AutoTab not allowing player names with who command
- Fixed Permaremove command permissions
- Fixed Enflamed instances being managed
- Fixed FireStream dissipation being managed
- Fixed HorizontalVelocity:
- Entity not being removed from instances when landing and not hitting
wall
- Still adding entities to instances when disabled
- Fixed toggle element command working for everyone, see below:
- Added bending.admin.toggle permission, used for toggling elements of
another player (need to add other player bending toggling but Chris
rushed me)
- Changed getBendingPlayer to be more exact with uuids

Major fixes to Toggle command, Firebending instances fixes

---

src/com/projectkorra/projectkorra/command/RemoveCommand.java
src/com/projectkorra/projectkorra/command/ToggleCommand.java
src/com/projectkorra/projectkorra/earthbending/EarthMethods.java
src/com/projectkorra/projectkorra/earthbending/EarthSmash.java

- Remove command:
- Fixed element aliases not working
- Added argument /b remove <element> which only removes a single element
from you if you have it. Tells you if you don't
- Fixed toggle command aliases and message messing up
- EarthMethods:
- Added isMetalbendable(Player player, Material mat)
- Checks for the material being in the metalblocks list in config and if
the player has metalbending permission
- Added check for metal blocks in getEarthSourceBlock()
- Fixed EarthSmash having problems with metal blocks

Fix commands, Fix EarthSmash bug

---

src/com/projectkorra/projectkorra/PKListener.java

- Fixed players without elements chat appearing as "null<playername>". Now says [Nonbender] in white.
- Removed unnecessary bending.avatar permission check on login.

Fix chat error

---

src/com/projectkorra/projectkorra/BendingManager.java
src/com/projectkorra/projectkorra/PKListener.java
src/com/projectkorra/projectkorra/command/PresetCommand.java
src/com/projectkorra/projectkorra/earthbending/EarthMethods.java
src/com/projectkorra/projectkorra/earthbending/EarthSmash.java
src/com/projectkorra/projectkorra/object/Preset.java
src/com/projectkorra/projectkorra/util/BlockSource.java
src/com/projectkorra/projectkorra/util/RevertChecker.java

Fixes exceptions reloading the plugin
Fixes Presets (now work full as intended)
Fixes EarthSmash reacting with metal
Fixes Suffocation cancelling all shift events
Fixed disable error in RevertChecker
Removes isEarthbendable(material)
Adds isEarth(block) method to replace isEarthbendable(material), returns
true if block is in Earthbendables config list
Adds isEarthbendable(block), returns true if block is on the
Earthbendable, Sandbendable, or Metalbendable config lists
Adds metalbending capabilities to EarthSmash
Adds reloadPresets(player) method
Changes bindPreset(player, string) to bindPreset(player, Preset)
Changes save() to save(player)

Various Fixes (read desc)

---

src/com/projectkorra/projectkorra/GeneralMethods.java
src/com/projectkorra/projectkorra/ProjectKorra.java
src/com/projectkorra/projectkorra/command/PresetCommand.java
src/com/projectkorra/projectkorra/configuration/ConfigManager.java
src/com/projectkorra/projectkorra/configuration/ConfigType.java
src/com/projectkorra/projectkorra/earthbending/EarthSmash.java
src/com/projectkorra/projectkorra/object/Preset.java
src/com/projectkorra/projectkorra/util/ActionBar.java
src/plugin.yml

Adds ./b p b [external] <player> command to assign external presets to
yourself or another player
Adds presets.yml, used to define external presets
Adds "bending.command.preset.bind.external" node to determine whether
players can bind external presets to themselves, default: op
Adds "bending.command.preset.bind.external.other" node to determine
whether players can bind external presets to others, default: op
Adds loadExternalPresets() method to register all external presets
Adds bindExternalPresets(player, name) method to bind an external preset
Adds GrabRange config option to EarthSmash, used to determine how close
you must be to grab a smash
Adds SelectRange config option to EarthSmash, used to determine how
close you must select to create a smash
Fixes EarthSmash damage when blocks are …

Adds External Presets/Fixes EarthSmash & Updater

---

src/com/projectkorra/projectkorra/command/Commands.java
src/com/projectkorra/projectkorra/command/CopyCommand.java
src/com/projectkorra/projectkorra/command/PresetCommand.java
src/com/projectkorra/projectkorra/earthbending/EarthSmash.java
src/com/projectkorra/projectkorra/object/Preset.java
src/plugin.yml

Adds new /b copy [player] <player> command, allows you to copy the binds
of [player] onto yourself or <player>
Adds "bending.command.copy" node to use base command, default: true
Adds "bending.command.copy.assign" node to assign players binds to other
players, default: op
Fixes presets being cleared if you attempt to bind them with no elements
Fixes EarthSmash cooldown, now only effects shooting new earthsmashes
and raising new earthsmashes, not grabbing/redirecting

Adds Copy command/Fixes Earthsmash & Presets

---

src/com/projectkorra/projectkorra/airbending/AirBlast.java
src/com/projectkorra/projectkorra/airbending/AirBurst.java
src/com/projectkorra/projectkorra/airbending/AirScooter.java
src/com/projectkorra/projectkorra/command/PresetCommand.java
src/com/projectkorra/projectkorra/configuration/ConfigManager.java
src/com/projectkorra/projectkorra/earthbending/Shockwave.java
src/com/projectkorra/projectkorra/util/BlockSource.java
src/com/projectkorra/projectkorra/waterbending/Bloodbending.java
src/com/projectkorra/projectkorra/waterbending/IceSpike.java
src/com/projectkorra/projectkorra/waterbending/IceSpike2.java
src/com/projectkorra/projectkorra/waterbending/WaterSpout.java
src/com/projectkorra/projectkorra/waterbending/WaterWave.java
src/plugin.yml

Fixes AirBurst deathmessage
Fixes IceSpike deathmessage
Fixes Bloodbending deathmessage
Fixes AirScooter randomly ending
Fixes AirScooter taking players meant to fly out of fly mode
Fixes ShockWave/AirBurst cooldown not influencing fall induced
ShockWaves/AirBursts
Fixes WaterSpout sometimes not working
Adds "bending.command.preset.bind.assign" node which allows players to
assign their presets onto other players, default: op
Adds /b p b [preset] <player> capabilities for player presets
Adds "CanBendFromSpout" config option for Water, determines whether
players can use water from their spout to bend, default: false

Various Fixes (read desc) / Adds assign Preset

---

src/com/projectkorra/projectkorra/PKListener.java
src/com/projectkorra/projectkorra/ability/CoreAbility.java
src/com/projectkorra/projectkorra/ability/util/AbilityLoader.java
src/com/projectkorra/projectkorra/ability/util/ComboManager.java
src/com/projectkorra/projectkorra/airbending/AirFlight.java
src/com/projectkorra/projectkorra/command/DisplayCommand.java
src/com/projectkorra/projectkorra/firebending/FireBlastCharged.java
src/com/projectkorra/projectkorra/firebending/FireCombo.java

AirFlight sneak (release) now causes AirFlight to be removed
Removed FireCombo debug messages
/b display was causing hiddenAbilities to be displayed if they extended AvatarAbility
AvatarState Charged FireBlast was exponentially bigger than it should have been
Old pre-refactor AddonAbilities were causing the plugin to crash while loading up

CoreAbility Improvements and Bug Fixes

---

src/com/projectkorra/projectkorra/firebending/FireDamageTimer.java

The EntityBendingDeathEvent will now trigger when an entity is killed by fire originating from a bending ability

- EntityBendingDeathEvent now triggers from fire-related deaths

---

src/com/projectkorra/projectkorra/airbending/AirBlast.java

The many airblasts that are generated from airburst were causing sound glitches by triggering doors levers and buttons at extremely fast rates

- AirBurst no longer triggers doors/buttons/levers

---

build.xml

Unless this was intended to be left out, the plugin, when built via ant, does not contain a plugin.yml file. This change will include the plugin.yml file when using `ant` to compile.

Include plugin.yml when building plugin

---

src/com/projectkorra/projectkorra/avatar/AvatarState.java
src/com/projectkorra/projectkorra/command/RemoveCommand.java

• Fixed AvatarState resetting the cooldown when a player logs out
• Fixed SubElements not being removed when a player isn't specified (and
related message errors)

Various Fixes

---

src/com/projectkorra/projectkorra/command/RemoveCommand.java

Fixed the bending remove message when a player removed another player's
element. It was sending the "your element has been removed by {sender}"
to the sender, instead of the target.

Fixed /b remove message.

---

src/com/projectkorra/projectkorra/PKListener.java

If fall damage is disabled via another plugin like WorldGuard, abilities like Shockwave can't function upon landing. Plus, there's already a lot of checks for event.isCancelled, so don't see a reason to do a check for the entire event.

Don't blindly check cancel status for all damage

---

src/com/projectkorra/projectkorra/util/ParticleEffect.java

The new 1.10 version looks like version 0 to the version check in ParticleEffect. Instead of just grabbing the last char, grab the last part of the string (after the .) and parseInt that. Then the numeric version compares will return the right class.

Fix ParticleEffect in version 1.10

---

src/com/projectkorra/projectkorra/airbending/AirSpout.java
src/com/projectkorra/projectkorra/earthbending/RaiseEarthWall.java
src/com/projectkorra/projectkorra/util/TempBlock.java
src/com/projectkorra/projectkorra/waterbending/WaterSpout.java

- Fixed a NullPointerException in OctopusForm
- Updated WaterSpout and AirSpout so that a user cannot use the ability if they are higher than the maximum height
- Made improvements to RaiseEarth so that it better reflects the "width" config option

Spout Max Height, RaiseEarth Config Options

---

src/com/projectkorra/projectkorra/airbending/AirBubble.java
src/com/projectkorra/projectkorra/waterbending/WaterManipulation.java
src/com/projectkorra/projectkorra/waterbending/WaterSpout.java
src/plugin.yml

WaterSpouts are now removed correctly when hit by a move or when a
bubble move is used underneath them.

Fixes WaterSpout flood and remove issues

---

src/com/projectkorra/projectkorra/PKListener.java
src/com/projectkorra/projectkorra/configuration/ConfigManager.java
src/com/projectkorra/projectkorra/earthbending/MetalClips.java

- Fixed bug where shooting at a block spawned two clips
- Added ShootCooldown and CrushCooldown
- ShootCooldown only applies to shooting clips, default of 1500 (1.5 seconds)
- Changed how crushing works: (current system is unreliable)
- - Removed old style and variables
- + When controlling an entity with 4 clips, the controller can click to
cause the armor to "crush" and damage the entity.
- + Has own cooldown, default of 2000 (2 seconds)
- + Added CrushDamage option
- Changed launching:
- + Works with all clip amounts except 4
- + When the user releases sneak, the entity will be launched at varying
power depending on how many clips were attached.
- Changed ability cooldown to activate only after the ability is
finished.
- Edited default cooldown, now 6000 (6 seconds)
- Edited damage for …

Improve MetalClips

---

src/com/projectkorra/projectkorra/configuration/ConfigManager.java
src/com/projectkorra/projectkorra/earthbending/MetalClips.java

-Metal Clips no longer deletes iron ingots upon instance removal.
-Metal Clips shoot cooldown now 0 by default

Metal Clips fixes

---

src/com/projectkorra/projectkorra/configuration/ConfigManager.java
src/com/projectkorra/projectkorra/earthbending/Tremorsense.java

Tremorsense
* Ignores if they have Tremorsense bound. The passive is now enabled by default, and can still be toggled by binding it and using sneak.
________________
WaterArms
* Default config value for "AllowPlantSource" has been set to true. Plants can now be used as a source for WaterArms by default.
________________

Fixed Tremorsense, WaterArms AllowPlantSource config

---

src/com/projectkorra/projectkorra/GeneralMethods.java
src/com/projectkorra/projectkorra/storage/DBConnection.java
src/com/projectkorra/projectkorra/storage/Database.java

Fixes an SQL error where the bending player is attempted to be created before DBConnection#init has completed

Make DBConnection#init sync and remove async from bending player creation

---

src/com/projectkorra/projectkorra/BendingPlayer.java
src/com/projectkorra/projectkorra/GeneralMethods.java
src/com/projectkorra/projectkorra/PKListener.java
src/com/projectkorra/projectkorra/airbending/AirBubble.java
src/com/projectkorra/projectkorra/chiblocking/Paralyze.java
src/com/projectkorra/projectkorra/firebending/FirePassive.java
src/com/projectkorra/projectkorra/firebending/Illumination.java
src/com/projectkorra/projectkorra/waterbending/WaterArmsWhip.java
src/com/projectkorra/projectkorra/waterbending/WaterPassive.java

Paralyze
* Paralyze cooldown system has been updated.
- MovePreview now displays Paralyze while on cooldown correctly.
____________
WaterArms
* You can no longer FastSwim while having WaterArms enabled.
Water Arms (Grapple)
* Fix/Improvement to launching yourself in the air. May need more tweaking in the future (Loony says it's alright so I'm PRing it wasnt me blameloony ty)
____________
AirBubble
* AirBubble no longer gets WaterBubble's night factor.
____________
Illumination
* Illumination now works correctly as a passive ability. It is automatically enabled for all firebenders and can be toggled by clicking with the ability bound.
____________

Changes: Paralyze, WaterArms, AirBubble, Illumination

---

src/com/projectkorra/projectkorra/airbending/Tornado.java
src/com/projectkorra/projectkorra/firebending/FirePassive.java
src/com/projectkorra/projectkorra/waterbending/SurgeWave.java
src/com/projectkorra/projectkorra/waterbending/WaterReturn.java

Tornado
* Tornado no longer works on barriers.
_________
Illumination
* Fixed Illumination not correctly being disabled via config.
_________
SurgeWave
* Surge wave no longer returns bottlebending water.
* This prevents bottlebending getting permanently disabled if a Surge wave doesn't get reverted.
_________

Changes: Tornado, Illumination, SurgeWave

---

src/com/projectkorra/projectkorra/earthbending/MetalClips.java
src/plugin.yml

WaterReturn
* bending.ability.WaterReturn is now in bending.player in plugin.yml to fix permission problems with bottlebending.
_______________
MetalClips
* If you have already shot a metal clip at someone and then hit someone else with one it will remove the ability instance, fixing duplicated armour.
_______________

Fixed WaterReturn permission & MetalClips duplication

---

src/com/projectkorra/projectkorra/PKListener.java
src/com/projectkorra/projectkorra/earthbending/MetalClips.java
src/com/projectkorra/projectkorra/firebending/HeatControlCook.java
src/com/projectkorra/projectkorra/firebending/Lightning.java
src/com/projectkorra/projectkorra/util/ParticleEffect.java
src/com/projectkorra/projectkorra/waterbending/WaterReturn.java

• Fixed all deprecated player.getItemInHand methods
• Death messages not working at all (only the default bending death
message would show)
• Fixed BLOCK_CRACK particles being unable to spawn block particles with
metadata
• Fixed bottlebending breaking in 1.9/1.10
Thanks to jedk1 for bottlebending fix as it was orignally his.

1.9/1.10 Tweaks

---

src/com/projectkorra/projectkorra/waterbending/PhaseChangeFreeze.java

Makes the `ConcurrentHashMap<Block, Byte>` in `PhaseChangeFreeze` a Generic `Map<Block, Byte>` type in order to allow for Java 7 / Java 8 compatibility.

Generi-size PhaseChangeFreeze

---

src/com/projectkorra/projectkorra/PKListener.java
src/com/projectkorra/projectkorra/configuration/ConfigManager.java
src/com/projectkorra/projectkorra/earthbending/EarthGrab.java

- Move now has travel time.
- Added particles that travel along the ground, to represent the travel
time.
- Changed the functions of the move to be: Shift + click = grab other -
entity, left click ground = self-grab.
- Edited the default config for the description.
- Edited the default range of the move, changed from 14 to 20.
- Edited the default cooldown time, it is now set to 2 seconds by
default.

Redo of my last pr, everything should be up to date now.

---

src/com/projectkorra/projectkorra/PKListener.java
src/com/projectkorra/projectkorra/chiblocking/AcrobatStance.java
src/com/projectkorra/projectkorra/chiblocking/WarriorStance.java
src/com/projectkorra/projectkorra/util/logging/LogFilter.java

Flight
* Fixed users being able to move around while hovering when they sprint.
____________
Acrobat & Warrior Stance
* When paralyzed, the effects from either stance would be removed, but move preview and sounds wouldn't update.
* Disable effects now play on remove().
* When remove() is called, it now removes the potion effects so they don't remain for a few seconds.
____________
LogFilter
* Added a '!' to line 62
____________

Flight, Chi Stance & Chris' life

---

src/com/projectkorra/projectkorra/util/DamageHandler.java

I'm assuming this was a typo? 
As an aside (and also why I found this), I'm currently working on a "NoKnockback" feature in my plugin, but trying to avoid canceling knockback due to bending abilities. Also, it seems that Entity.damage(damage, source) will call its own EntityDamageByEntity event, as if the player melee'd the entity (with `ENTITY_ATTACK` as the cause, etc.). Not sure if this is avoidable, but at least if you either call this custom damage event or if I hook into ProjectKorra and watch the other event, I can have it ignore other damage events within that tick for that player I suppose.

Call the final damage event

---

src/com/projectkorra/projectkorra/configuration/ConfigManager.java
src/com/projectkorra/projectkorra/waterbending/Bloodbending.java
src/com/projectkorra/projectkorra/waterbending/Torrent.java

Torrent
* Added `Revert` config option. Set to false to disable reverting.
* Added `RevertTime` config option. Set to the delay in milliseconds for reverting Torrent ice. Only works if `Revert` is set to true.
https://trello.com/c/CcTB1Fuq/582-torrent-s-ice-revert-doesn-t-work-ice-stays-forever
_________________
Bloodbending
* Fixed `ConcurrentModificationException`
https://trello.com/c/vLLl8d3m/579-bloodbending-error
_________________

Added option for Torrent revert & fixed Bloodbending NPE

---

src/com/projectkorra/projectkorra/command/BindCommand.java
src/com/projectkorra/projectkorra/waterbending/Torrent.java

BindCommand
* Fixed error when specifying a slot which is not an integer.
* Eg. /b b FireBlast t4geg
* https://trello.com/c/bJOuadPV/602-when-binding-an-ability-if-you-do-not-specify-an-integer-for-the-3rd-argument-it-gives-this-error-eg-b-b-fireblast-test
__________
Torrent
* Added variation to the revert times to play an effect  like WaterArms' ice revert.
__________

Fix Error with /b bind, added Torrent ice revert effect

---

src/com/projectkorra/projectkorra/util/DamageHandler.java

Firing this tricks other plugins into believing this entity was damaged.
In addition, Entity#damage also fires a damage event (and as such, applies the appropriate damage changes), so no need to fire a fake, duplicate one.
It doesn't seem `getLastDamageCause` is used anywhere in ProjectKorra, so I imagine this is for death message plugins.

use a damage event only for setting last damage cause

---

src/com/projectkorra/projectkorra/ability/CoreAbility.java
src/com/projectkorra/projectkorra/waterbending/IceSpikeBlast.java
src/com/projectkorra/projectkorra/waterbending/WaterManipulation.java

• Fixed Bottlebending breaking (needs testing)
• Fixed CoreAbility not returning all abilities with
`CoreAbility.getAbilities()`
• Added new `ability.setPlayer(…)` method that is used for moves that
change who created the ability (used for redirection)

Minor fixes

---

src/com/projectkorra/projectkorra/BendingPlayer.java
src/com/projectkorra/projectkorra/PKListener.java

Adds `canCurrentlyBendWithWeapons()` to `BendingPlayer`. Returns true if the player is able to bend their current move with a weapon.

Fixes bending combos

---

src/com/projectkorra/projectkorra/airbending/AirFlight.java
src/com/projectkorra/projectkorra/configuration/ConfigManager.java

https://trello.com/c/DO48r2co/669-add-maxduration-config-value-to-flight-to-limit-how-long-users-can-use-the-ability-for
https://trello.com/c/G8E1tv4V/670-add-cooldown-config-value-for-flight-if-maxduration-is-hit

Added Cooldown & MaxDuration to Flight

---

src/com/projectkorra/projectkorra/waterbending/OctopusForm.java

- http://projectkorra.com/support-tickets/npe-issues-with-octopus-form.190/
- when this .remove() is called nothing has happened with this instance, so the old tempblocks/phasechange never actually get removed, and we get nullpointers trying to remove the ones for this instance since they were never even created

should fix some issues with octopusform

---

src/com/projectkorra/projectkorra/ability/EarthAbility.java

- Set the source block to air after setting the target block to the new
type. This will eliminate temporary holes, which minimizes major lighting
updates.
This fixes a vulnerability that allows players to create massive lag by using Collapse/Shockwave. Using either of these abilities on a single layer plane up in the air will cause massive lighting updates, freezing the entire server.

Change block set order when moving earth

---

.gitignore
src/com/projectkorra/projectkorra/configuration/ConfigManager.java
src/com/projectkorra/projectkorra/earthbending/EarthTunnel.java

Added the ability to choose whether or not EarthTunnel drops loot when revert for EarthTunnel is off. This commit also includes gitignores for IntellJ Idea.

EarthTunnel - DropLootIfNotRevert

---

src/com/projectkorra/projectkorra/util/DamageHandler.java

Closes #314, closes #320, closes #321
Exempts various PvP-related checks in NCP when an entity receives damage from a bending ability (since the way PK deals damage due to an ability is similar to melee attack instead of as a projectile):
- Direction: A player can use an ability (e.g. earthblast, watermanipulation) and then decide to look elsewhere (check fails as player isn't looking at entity being attacked).
- NoSwing: Especially evident on abilities that require no left-clicking (e.g. suffocation).
- Speed and Improbable: Usually for AoE attacks (e.g. fireburst, earthsmash) cause this, since the player can damage multiple entities around themself at the same time.

Some NCP compatibility

---

.travis.yml

Changed channel from #development which is now archived to #devs

Update notification rooms for Travis

---

src/com/projectkorra/projectkorra/GeneralMethods.java

- https://trello.com/c/dP0WWu8t/781-elements-for-a-player-returning-null-in-the-database-causes-plugin-to-break
Abilities aren't allowed to be null because ConcurrentHashMaps are used everywhere, which throw an exception when a null value is added. The default insert would set the slots to null in the database. The only reason why new player abilities would be changed from null to 'null' in the database is because onPlayerJoin calls GeneralMethods.removeUnusableAbilities 5 ticks later. If a player would leave before that's called then their database values would be null instead of 'null', and it would cause ConcurrentHashMap to throw an exception.
Before this pull request, player insertion and all the set slot inserts …

Insert new players into database atomically

---

src/com/projectkorra/projectkorra/GeneralMethods.java
src/com/projectkorra/projectkorra/ability/util/CollisionManager.java

- Fix a bug where collision detection would be aborted if two abilities were in different worlds.
- Fix a bug where the old CollisionManager collision detection task wasn't aborted when creating a new manager.
- Improve performance by removing unnecessary work that's done before detecting collisions.
The detectCollisions method would return early if two abilities were in different worlds. This would cancel all collision detection for any other abilities that haven't been processed in the loop.
The CollisionManager would create new tasks every time the plugin is reloaded without stopping the previous one. This is both bad for performance and for addons that have configuration options for collisions.
The detectCollisions method was unnecessarily looping through all the active instances …

Fix collision manager bugs

---

src/com/projectkorra/projectkorra/ability/CoreAbility.java
src/com/projectkorra/projectkorra/ability/util/PassiveManager.java

Fixed Addon Passive abilities throwing an exception when registering the ability.
* `Class<?> clazz = Class.forName(ability.getClass().getName());` would not work with addons because it is an external jar file.
* Fixed by storing the ability classes in PassiveManager#PASSIVE_CLASSES, which is then pulled when registering the instance.

Fixed addon passive abilities

---

src/com/projectkorra/projectkorra/BendingPlayer.java
src/com/projectkorra/projectkorra/command/DisplayCommand.java
src/com/projectkorra/projectkorra/command/WhoCommand.java
src/com/projectkorra/projectkorra/earthbending/CollapseWall.java
src/com/projectkorra/projectkorra/earthbending/RaiseEarthWall.java
src/com/projectkorra/projectkorra/earthbending/Ripple.java
src/com/projectkorra/projectkorra/firebending/BlazeArc.java
src/com/projectkorra/projectkorra/firebending/BlazeRing.java
src/com/projectkorra/projectkorra/firebending/FireBlastCharged.java
src/com/projectkorra/projectkorra/waterbending/SurgeWall.java
src/com/projectkorra/projectkorra/waterbending/TorrentWave.java
src/com/projectkorra/projectkorra/waterbending/WaterSpoutWave.java
src/com/projectkorra/projectkorra/waterbending/ice/IceSpikeBlast.java
src/com/projectkorra/projectkorra/waterbending/ice/IceSpikePillar.java
src/com/projectkorra/projectkorra/waterbending/multiabilities/WaterArmsFreeze.java
src/com/projectkorra/projectkorra/waterbending/multiabilities/WaterArmsSpear.java
src/com/projectkorra/projectkorra/waterbending/multiabilities/WaterArmsWhip.java
src/plugin.yml

* Fixes multiple instances of the same `CoreAbility` being present in auto tabbing due to certain move functionalities being split up between files.
> * https://trello.com/c/sw6cw7BT/833-moves-with-multiple-functionalities-split-up-among-multiple-classes-create-multiple-occurrences-of-a-single-move-in-pk-help-and
* Fixes passives and passives showing up in `/pk bind <Ability>` auto tabbing.
> * https://trello.com/c/STJ0AR1f/834-combos-and-passives-appear-in-pk-bind-auto-tabbing

Fix multiple abilities in Autotab & combos/passives in bind

---

src/com/projectkorra/projectkorra/BendingPlayer.java
src/com/projectkorra/projectkorra/command/BindCommand.java
src/com/projectkorra/projectkorra/command/DisplayCommand.java
src/com/projectkorra/projectkorra/command/WhoCommand.java
src/com/projectkorra/projectkorra/earthbending/CollapseWall.java
src/com/projectkorra/projectkorra/earthbending/RaiseEarthWall.java
src/com/projectkorra/projectkorra/earthbending/Ripple.java
src/com/projectkorra/projectkorra/firebending/BlazeArc.java
src/com/projectkorra/projectkorra/firebending/BlazeRing.java
src/com/projectkorra/projectkorra/firebending/FireBlastCharged.java
src/com/projectkorra/projectkorra/util/DamageHandler.java
src/com/projectkorra/projectkorra/waterbending/SurgeWall.java
src/com/projectkorra/projectkorra/waterbending/SurgeWave.java
src/com/projectkorra/projectkorra/waterbending/TorrentWave.java
src/com/projectkorra/projectkorra/waterbending/WaterSpoutWave.java
src/com/projectkorra/projectkorra/waterbending/ice/IceSpikeBlast.java
src/com/projectkorra/projectkorra/waterbending/ice/IceSpikePillar.java
src/com/projectkorra/projectkorra/waterbending/ice/IceSpikePillarField.java
src/com/projectkorra/projectkorra/waterbending/multiabilities/WaterArmsFreeze.java
src/com/projectkorra/projectkorra/waterbending/multiabilities/WaterArmsSpear.java
src/com/projectkorra/projectkorra/waterbending/multiabilities/WaterArmsWhip.java
src/plugin.yml

* Fixes multiple instances of the same `CoreAbility` being present in auto tabbing due to certain move functionalities being split up between files.
> * https://trello.com/c/sw6cw7BT/833-moves-with-multiple-functionalities-split-up-among-multiple-classes-create-multiple-occurrences-of-a-single-move-in-pk-help-and
* Fixes passives and passives showing up in `/pk bind <Ability>` auto tabbing.
> * https://trello.com/c/STJ0AR1f/834-combos-and-passives-appear-in-pk-bind-auto-tabbing
* Fixes `WaterWave` and `WaterSpout` cohesive movement.
> * https://trello.com/c/ZEAAW9fU/807-waterwave-any-spout-does-not-allow-for-the-cohesive-movement-of-waterwave
* Fixes `DamageHandler` applying `DamageModifier.ARMOR` where it is not applicable.
> * https://trello.com/c/JrC35la8/828-damaging-creatures-without- …

Fix WaterWave and WaterSpout behavior & DamageHandler error

---

src/com/projectkorra/projectkorra/PKListener.java

Fixes #790
Also revises the listener to check event#isCancelled once before continuing.

Check event#iscancelled before handling fire damage

---

src/com/projectkorra/projectkorra/util/DamageHandler.java

It is possible for the player to hit themselves with their own abilities - largely due to AoE attacks (e.g. lightning)
Also changed to just unexempt the checks we added

exempt NCP selfhit check

---

src/com/projectkorra/projectkorra/ability/CoreAbility.java

- none
- if a move errors, print the error then attempt to call the remove method for it
- this allows other moves that didnt error to continue, preventing one move from breaking the whole server of players bending

dont break all bending if a move errors

---

src/com/projectkorra/projectkorra/earthbending/EarthGrab.java

Fixes an infinite loop that can happen when selecting an entity that's standing near an air column that goes down to the void.

Fix EarthGrab infinite loop

---

src/com/projectkorra/projectkorra/airbending/AirBlast.java
src/com/projectkorra/projectkorra/airbending/AirScooter.java

- Makes AirScooter disable itself on player sneak
- Changes AirBlast obsidian and cobblestone to tempblocks.
- https://trello.com/c/nwkmFj3Z/723-make-pressing-sneak-while-using-airscooter-disable-the-ability
- https://trello.com/c/d6WoIjjb/844-when-airblast-cools-lava-the-obsidian-should-be-a-tempblock

AirScooter, AirBlast

---

src/com/projectkorra/projectkorra/PKListener.java
src/com/projectkorra/projectkorra/command/HelpCommand.java

* Fixes `AirScooter` cancelling on shift.
* Adds the result of an Addon's `getVersion()` to its `/pk help` description.

Add version to Addon help, fix AirScooter shift

---

src/com/projectkorra/projectkorra/PKListener.java

* Removes approx 30 redundant if checks from the PKListener.   These If Checks will never fire because ignoreCancelled=true is set in the @EventHandler line.   Thus they just serve to make the listener longer.

Removed redundant if checks

---

src/com/projectkorra/projectkorra/BendingPlayer.java
src/com/projectkorra/projectkorra/configuration/ConfigManager.java
src/com/projectkorra/projectkorra/util/BlockSource.java

* Added Dynamic Sourcing config option
* Removed SpiritPlayer checks in BendingPlayer#canBind(CoreAbility ability)
* Due to recent changes to PK Spirits, this isn't needed anymore

Added Dynamic Sourcing config option

---

src/com/projectkorra/projectkorra/earthbending/EarthTunnel.java

* Fixed Earth tunnel so that it will work through tall grass and other transparent blocks.

Fix EarthTunnel not ignoring grass

---

src/com/projectkorra/projectkorra/BendingPlayer.java

* Prevents cooldownChangeEvent from being fired on moves with a zero cooldown.

Updated addCooldown() Method

---

src/com/projectkorra/projectkorra/PKListener.java
src/com/projectkorra/projectkorra/chiblocking/WarriorStance.java
src/com/projectkorra/projectkorra/configuration/ConfigManager.java
src/com/projectkorra/projectkorra/earthbending/Tremorsense.java

• Added a "Sticky" feature to tremorsense (passive).
• Now when an earthbender moves onto a block they can't bend, the light will remain on the last bendable block
• After they go out of range (3 blocks; configurable), then the light goes out. Change to 0 to disable.
• Fixed WarrierStance NPE (from #830)
• Fixed being able to remove the EarthArmor armor items from their slots
• Fixed DensityShift softening your landing while you are an Airbender (and with optimizations to the if statements)

Fixes, Added sticky feature to tremorsense

---

src/com/projectkorra/projectkorra/GeneralMethods.java
src/com/projectkorra/projectkorra/waterbending/blood/Bloodbending.java

AcrobatStance NullPointerException
* Caused by players disconnecting while having AcrobatStance active
* Fixed by adding null check on bPlayer
> * https://trello.com/c/wYVhu6IG/894-error-on-wip
Bloodbending ConcurrentModificationException
* Caused by players unintentionally (or intentionally!) trying to bloodbend a non-LivingEntity
* Fixed by using an Iterator to remove the non-LivingEntity from the entities ArrayList
> * https://trello.com/c/58OTgYW7/896-another-another-error-on-wip

Fixed AcrobatStance and Bloodbending errors

---

src/com/projectkorra/projectkorra/earthbending/EarthTunnel.java
src/com/projectkorra/projectkorra/util/TempBlock.java

* EarthTunnel bug
> * https://trello.com/c/O1zvQT0N/831-earthtunnel-cant-be-used-on-gravel-sand-red-sand-blocks-that-are-fell
This bug was caused by blocks with gravity (sand, gravel, etc) falling into already existing TempBlocks and attempting to use EarthTunnel on these blocks. Previously it would result in nothing happening, and the block would be stuck.
This issue was caused by TempBlock not correctly checking the material type (and data!) of the already existing TempBlock when attempting to create a new instance on a pre-existing TempBlock.
This was fixed by instead of checking if `newtype` and `newdata` on the old and new TempBlock are different, it checks the actual type of the block by using `temp.block.getType()`, to get the actual values. This is because the already created …

Fixed EarthTunnel bug

---

.gitignore
src/com/projectkorra/projectkorra/PKListener.java
src/com/projectkorra/projectkorra/earthbending/metal/MetalClips.java

> **Note**: more information is contained in the description of each commit.
* A `ClassCastException` in `PKListener.java:onEntityDamageEvent()` would occur when a non-Living Entity took damage.
* Ingots on the ground would disappear when their `ItemStack` merged with MetalClips', and the latter is removed upon colliding with an Entity.
* A small vertical push was given to items affected by the *magnetize* functionality of MetalClips, so that they no longer get stuck when being pulled upwards.
* Added a `gitignore` entry to omit IntelliJ's out/ directory, which contains compiled code.
> **Note**: more information is contained in the description of each commit.

Fixed bug with MetalClips and misc errors.

---

src/com/projectkorra/projectkorra/BendingPlayer.java
src/com/projectkorra/projectkorra/ProjectKorra.java
src/com/projectkorra/projectkorra/avatar/AvatarState.java
src/com/projectkorra/projectkorra/command/ChooseCommand.java
src/com/projectkorra/projectkorra/storage/DBConnection.java
src/com/projectkorra/projectkorra/util/Cooldown.java

**Overview**
In order for cooldowns to be saved through server restarts, a new database table has been introduced (pk_cooldowns) which will hold information for specific player's who have abilities on cooldown. This data will be saved onDisable and loaded back in onEnable.
**Utilising the API**
To create a cooldown for a player which will be saved in this database table, simply provide an extra boolean argument to the end of BendingPlayer#addCooldown(...) defining this feature. A couple new BendingPlayer#addCooldown(...) methods have been introduced to take this extra argument, leaving it false for all the previous addCooldown methods.

Added database cooldowns

---

src/com/projectkorra/projectkorra/PKListener.java
src/com/projectkorra/projectkorra/airbending/AirBlast.java
src/com/projectkorra/projectkorra/command/StatsCommand.java
src/com/projectkorra/projectkorra/util/StatisticsManager.java
src/com/projectkorra/projectkorra/util/StatisticsMethods.java
src/com/projectkorra/projectkorra/util/TimeUtil.java
src/com/projectkorra/projectkorra/waterbending/multiabilities/WaterArmsWhip.java

* Fixed bug when pulling categorised statistics information resulting in mixed statistic type searches.
* Fixed bad code when storing statistics information.
* Fixed AirBlast damageEntity call not using correct AirBurst instance.
* Changed StatsCommand#getLeaderboard(...) to run asynchronously to prevent halting the server when making multiple OfflinePlayer calls.
* Fixed bug with statistic leaderboard pages.
* Fixed pk_statKeys table not generating statistic keys for foreign abilities.

Statistics fixes & optimisations

---

src/com/projectkorra/projectkorra/earthbending/metal/Extraction.java

we are checking 3 specific ores hardcoded, so its not necessary to check, also by default they arent in the list anymore. Makes it possible to use extraction while not allowing the ores to be used in other moves. If you didn't want this then you would just disable the move entirely

remove metalbendable check for extraction

---

src/com/projectkorra/projectkorra/ability/ElementalAbility.java

The console was being spammed with nullpointerexceptions when a player tries to use any ability inside a world with nether and the end environment. The exception was being thrown by the methods that checked the marker of ProjectKorraRPG, and prevented the players to use many abilities in this worlds (one player said he could still use some abilities).
I saw that the problem was that Nether and The End worlds don't get added to the marker, so when trying to use marker.get(world).equals method a null pointer exception was thrown because of .get(world) returned null. I fixed it checking if get(world) returns null before trying to access it.
After the fix the exception is not being thrown, and players can use abilities in this worlds.
This is the stacktrace I obtained after fixing ONLY …

Now checking if world in ProjectKorraRPG marker attribute.

---

src/com/projectkorra/projectkorra/configuration/ConfigManager.java
src/com/projectkorra/projectkorra/waterbending/OctopusForm.java
src/com/projectkorra/projectkorra/waterbending/WaterSpout.java

* Adds duration to OctopusForm and WaterSpout, defaults to 0 which results in infinite usage.
* Fixes OctopusForm adding the cooldown immediately after creation.
* Fixes WaterSpout not reading/adding its cooldown correctly.

Add duration and proper cooldown to WaterSpout and OctopusForm

---

src/com/projectkorra/projectkorra/GeneralMethods.java

Fixed players being able to use passives of elements they no longer possess.
-     Trello Card: https://trello.com/c/xdbB8gG4
-     The method removeUnusableElements in GeneralMethods takes care of this now
(Seems I accidentally messed with a few imports too, oops)

Fixed players keeping passives after they no longer possess the respective element

---

pom.xml
src/com/projectkorra/projectkorra/ability/util/CollisionInitializer.java
src/com/projectkorra/projectkorra/ability/util/CollisionManager.java
src/com/projectkorra/projectkorra/command/ChooseCommand.java
src/com/projectkorra/projectkorra/util/FlightHandler.java
src/plugin.yml

Bumped version from 1.8.6 to 1.8.7
* Adds `bending.choose.ignorecooldown`
> * Allows the player in question to bypass the choose command cooldown if it is enabled
* Adds overriding capabilities to CollisionManager
> * Redefining an existing collision will override the pre-existing one
* Adds ignoreAbils array to CollisionInitializer.
> * Abilities in this array will not collide with any Abilties
* Fixes FlightHandler issues causing fly glitches
* Fixes choose command cooldown being applied to players even if they can bypass it with `bending.admin.choose`

Add cooldown ignore perm, change collisions, fix fly glitches in FlightHandler

---

src/com/projectkorra/projectkorra/GeneralMethods.java

* GeneralMethods#getTargetedEntity will now only loop through entities within the specified range instead of all entities in the world
> * https://trello.com/c/OOSVwZVj/911-generalmethodsgettargetedentities-unnecessarily-checks-through-all-entities-in-the-world

Optimized GeneralMethods#getTargetedEntity

---

src/com/projectkorra/projectkorra/GeneralMethods.java
src/com/projectkorra/projectkorra/airbending/AirSwipe.java
src/com/projectkorra/projectkorra/airbending/combo/AirSweep.java
src/com/projectkorra/projectkorra/firebending/lightning/Lightning.java

* Adds HorizontalVelocityTracker to AirSweep
* Adds `GeneralMethods#getMainHandLocation(final Player player)`
* Changed AirSweep and AirSwipe to originate from a Player's main hand location
* Changed the knockback caused by AirSweep more consistent in the air and on the ground
* Disable Lightning use when using FireJet

Change AirSweep and FireJet + Lightning

---

src/com/projectkorra/projectkorra/GeneralMethods.java
src/com/projectkorra/projectkorra/firebending/FireJet.java
src/com/projectkorra/projectkorra/firebending/WallOfFire.java
src/com/projectkorra/projectkorra/firebending/combo/JetBlast.java
src/com/projectkorra/projectkorra/firebending/combo/JetBlaze.java
src/com/projectkorra/projectkorra/waterbending/SurgeWall.java

* Fixes getClosestEntity to not rely on a distance check for if the entity is returned, but instead purely get the closest entity from getEntitiesAroundPoint
* Fixes SurgeWall to not do that new diagonal check, fixes Ice wall glitching out
* Changes JetBlaze hitbox size, was way too big
* Changes FireJet, WallOfFire, and the FireJet Combos cooldowns to activate when the move completes

Fix cooldowns of fire abilities with a duration, getClosestEntity, and Surge Wall diagonal check

---

src/com/projectkorra/projectkorra/waterbending/util/WaterReturn.java

Static Function that returns the slot id of the first water bottle found, -1 if none found. Used to not repeat code that should be the same (hasWaterBottle and emptyWaterBottle start finding this index, but they don't use the same code).
Fixes an error in hasWaterBottle function. In the former version of the WaterReturn.java file, hasWaterBottle only tests if the first item with Material.POTION in the inventory is of type PotionType.WATER. Having a random potion in the inventory in any slot before a Water Bottle makes this to return false, instead of checking all the potions in the Player Inventory. This causes the player to be unable to use the bottle as a water source. The new code checks all the potions.
Since the items in an inventory aren't usually sorted (players don't sort items by …

Fix WaterReturn not finding bottles after potions

---

src/com/projectkorra/projectkorra/airbending/AirBlast.java
src/com/projectkorra/projectkorra/airbending/AirBurst.java
src/com/projectkorra/projectkorra/configuration/ConfigManager.java

* Removes `AirBurst#getAffectedEntities()`, shouldn't allow direct access to the list
* Lowers "friction" in AirBlast knockback for entities on the ground
* Ignore "friction" in AirBlast when the AirBurst source isn't null
* Changes entity velocity comparison to only add vectors angled > pi/3 from push vector
* Increase default AirBurst push option

AirBlast and AirBurst Changes

---

src/com/projectkorra/projectkorra/command/PresetCommand.java

* Fixes listing preset pages. Previously doing "/b preset list 2" would just return the help message

Fix Preset command not being able to list page numbers higher than 1

---

src/com/projectkorra/projectkorra/earthbending/Catapult.java
src/com/projectkorra/projectkorra/earthbending/metal/MetalClips.java

* Fixes catapult launching player with invincible toggled or protected region
* Fixes metalclip working on players with invincible toggled

patch catapult and metalclips not respecting invincible or region protection

---

src/com/projectkorra/projectkorra/hooks/PlaceholderAPIHook.java

* unnecessary leftover from copy paste that I just never noticed

Remove leftover debug chat formatting for PlaceholderAPI

---

src/com/projectkorra/projectkorra/command/DisplayCommand.java

Just a personal suggestion.
* Synchronizes the display command header for a more clean, uniform look.

synchronize display command headers

---

src/com/projectkorra/projectkorra/chiblocking/Smokescreen.java
src/com/projectkorra/projectkorra/configuration/ConfigManager.java

* Made the particle amount for Smokescreen configurable.
> * [Trello link](https://trello.com/c/V8UMd6Qj/942-add-config-option-or-something-else-to-low-amount-of-particles-of-smokescreen)
* Cleaned up the smoke particle code, gave them more dimension.

added configurable particle amounts for Smokescreen

---

src/com/projectkorra/projectkorra/waterbending/multiabilities/WaterArmsSpear.java

* Fixes WaterArms Spear being able to go through certain blocks (like ice) as if they aren't there.
> * [Trello link](https://trello.com/c/LCsd8Ed2/742-waterarms-bugs)

fixes waterarms spear going through blocks

---

src/com/projectkorra/projectkorra/airbending/Suffocate.java

This contains some of my edits/fixes to Suffocate without the new animation (which wasn't very well executed before).
* Fixed being able to use Suffocate on armor stands.
* Removed an unnecessary LivingEntity variable.
* Moved a for loop out of the animate method and placed it inside of the progress method. This was used to separate the different animations (under and above water) in my old PR and can be used for the same thing when an underwater animation gets worked on.

some of my suffocate edits without the new animation

---

src/com/projectkorra/projectkorra/GeneralMethods.java
src/com/projectkorra/projectkorra/earthbending/Tremorsense.java
src/com/projectkorra/projectkorra/earthbending/lava/LavaFlow.java
src/com/projectkorra/projectkorra/earthbending/lava/LavaSurge.java
src/com/projectkorra/projectkorra/earthbending/lava/LavaSurgeWall.java
src/com/projectkorra/projectkorra/earthbending/lava/LavaSurgeWave.java
src/com/projectkorra/projectkorra/waterbending/TorrentWave.java
src/com/projectkorra/projectkorra/waterbending/WaterManipulation.java
src/com/projectkorra/projectkorra/waterbending/WaterSpout.java
src/com/projectkorra/projectkorra/waterbending/WaterSpoutWave.java
src/com/projectkorra/projectkorra/waterbending/combo/IceBullet.java
src/com/projectkorra/projectkorra/waterbending/healing/HealingWaters.java
src/com/projectkorra/projectkorra/waterbending/ice/PhaseChange.java
src/com/projectkorra/projectkorra/waterbending/multiabilities/WaterArms.java
src/com/projectkorra/projectkorra/waterbending/multiabilities/WaterArmsWhip.java
src/com/projectkorra/projectkorra/waterbending/util/WaterReturn.java
src/com/projectkorra/projectkorra/waterbending/util/WaterSourceGrabber.java

Update some deprecated calls
* Fixes a bug which caused the server to load the legacy material API the first time a player used tremorsense's passive.
* Added boundaries to Levelled block data in GeneralMethods.getWaterData and GeneralMethods.getLavaData to avoid future bugs

Fix deprecated calls

---

src/com/projectkorra/projectkorra/PKListener.java
src/com/projectkorra/projectkorra/airbending/combo/AirSweep.java
src/com/projectkorra/projectkorra/configuration/ConfigManager.java
src/com/projectkorra/projectkorra/waterbending/passive/FastSwim.java

* Added a configurable AirSweep hit radius called "Radius" with a default of 1
* Added a configurable option to enable/disable WaterArms bound messages that are independent of the BendingPreview option, called "DisplayBoundMsg" under the WaterArms config, with a default of false
* Added a configurable option to allow/prohibit FastSwim while WaterArms is in use, called "AllowWaterArms" under the FastSwim config, with a default of false

Various config options

---

src/com/projectkorra/projectkorra/ability/CoreAbility.java

Small bugfix for abilities' running ticks.
Method signatures (getStartTick and getCurrentTick) have remained the same to maintain compatibility (even though CoreAbility::getStartTick is unnecessary).
* Fixes #1084

Fix ability bug with gamerule doDaylightCycle

---

src/com/projectkorra/projectkorra/BendingPlayer.java

- Changes `BendingPlayer.getBendingPlayer(Player player)` to redirect to `BendingPlayer.getBendingPlayer(OfflinePlayer player)` instead of `BendingPlayer.getBendingPlayer(String playerName)`
- Redirecting to `BendingPlayer.getBendingPlayer(String playerName)` (current behaviour) makes lots of pointless calls to bukkit to fetch the player object again when one was already originally provided. This fixes that and optimizes it so there are no longer any pointless calls to Bukkit.

Fixed pointless waste of execution time

---

src/com/projectkorra/projectkorra/util/TempBlock.java

* Fixes a duplication bug caused by the TempBlock class, the block was still added to the revert queue even if the state never ended up being changed because it is a Container, this meant that taking out items before the revert would allow players to duplicate items as they were re-added when the revert happens.

Fixes duplication bug in TempBlocks

---

src/com/projectkorra/projectkorra/BendingPlayer.java
src/com/projectkorra/projectkorra/GeneralMethods.java
src/com/projectkorra/projectkorra/PKListener.java
src/com/projectkorra/projectkorra/ProjectKorra.java
src/com/projectkorra/projectkorra/ability/CoreAbility.java
src/com/projectkorra/projectkorra/ability/util/MultiAbilityManager.java
src/com/projectkorra/projectkorra/board/BendingBoardInstance.java
src/com/projectkorra/projectkorra/board/BendingBoardManager.java
src/com/projectkorra/projectkorra/chiblocking/AcrobatStance.java
src/com/projectkorra/projectkorra/chiblocking/WarriorStance.java
src/com/projectkorra/projectkorra/command/BoardCommand.java
src/com/projectkorra/projectkorra/command/Commands.java
src/com/projectkorra/projectkorra/command/CopyCommand.java
src/com/projectkorra/projectkorra/configuration/ConfigManager.java
src/com/projectkorra/projectkorra/configuration/ConfigType.java
src/com/projectkorra/projectkorra/event/PlayerStanceChangeEvent.java
src/com/projectkorra/projectkorra/object/Preset.java
src/com/projectkorra/projectkorra/storage/DBConnection.java
src/plugin.yml

* Adds bending board, feature is disabled by default
* Serverwide option to enable/disable board.
* Players can use BoardCommand to toggle visibility for themselves.
* Creates a new board.yml config file with an option to enable the board. It stores a lists of players that have turned the board off.
* Bending Board respects worlds where bending is disabled. It also supports binds set by Presets or CopyCommand.
Things to add in the future: Add support for MultiAbilities' binds

Add bending board

---

src/com/projectkorra/projectkorra/GeneralMethods.java
src/com/projectkorra/projectkorra/ability/EarthAbility.java
src/com/projectkorra/projectkorra/earthbending/EarthArmor.java
src/com/projectkorra/projectkorra/earthbending/EarthBlast.java
src/com/projectkorra/projectkorra/earthbending/EarthSmash.java
src/com/projectkorra/projectkorra/earthbending/RaiseEarth.java
src/com/projectkorra/projectkorra/util/BlockSource.java

* DensityShift sand blocks are now "bendable earth TempBlocks," similar to water's PhaseChange and Torrent ice
* This is to allow those who want sand blocks to be earthbendable and not just sandbendable to use the full range of earth abilities with DensityShift sand
* The main culprits were EarthBlast and RaiseEarth, which both prevented sourcing from TempBlocks, so now there's an exception for bendable TempBlocks
* A lot of people have been asking for this feature, so I thought I would try to add it to the plugin by the next release
* If you ever need bendable earth TempBlocks in the future, you will be able to use this and just add the blocks in question to the new boolean in EarthAbility

Add bendable earth TempBlocks

---

src/com/projectkorra/projectkorra/ability/util/MultiAbilityManager.java

This method causes problems because it doesn't actually determine whether it's the same ability.
If the player has WaterArms bound and we want to know if they have PlantArmor bound, this will return true:
- !playerBoundAbility.get(player).equals(multiAbility) is TRUE if they're not the same ability, which is working properly
- bPlayer.getBoundAbility() != null returns FALSE because multiabilities clear binds.
- The whole boolean on line 138 is then false, meaning the method doesn't return false if they're different multiabilities
- So it defaults to returning true. Therefore WaterArms is the same ability as PlantArmor, which is problematic for addons
The solution is to get rid of the second part of that boolean. Been using this on my server for a while, but figured I would PR because it's …

Fix MultiAbilityManager#hasMultiAbilityBound

---

src/com/projectkorra/projectkorra/ability/util/MultiAbilityManager.java

* Fixes a compiler error caused by an extra parenthesis in MultiAbilityManager

Fix typo in MultiAbilityManager

---

src/com/projectkorra/projectkorra/attribute/AttributeModifier.java

* Adding attribute modifiers to abilities sometimes results in an IllegalArgumentException due to flawed logic in this class.
* Tested back in February I think, and it has worked well for me ever since.

Fix AttributeModifier throwing IllegalArgumentException

---

src/com/projectkorra/projectkorra/GeneralMethods.java
src/com/projectkorra/projectkorra/attribute/AttributeModifier.java
src/com/projectkorra/projectkorra/earthbending/EarthArmor.java

Co-authored with @ChristopherWMM 
* ClassDefNotFoundError resulted from net.minecraft.server.1_17_R1.EntityHuman being moved and renamed during the 1.17 Minecraft update
* Instead of using the new name and location, we're using the methods in Bukkit's Damageable interface for the absorption hearts used in EarthArmor, which probably didn't exist when the original EarthArmor was written
* Removed unused static variables and imports
* Marked the GeneralMethods absorption methods as deprecated
* Changed EarthArmor method calls to the preferred Player#setAbsorptionAmount
* Changed EarthArmor's goldHearts field to a double since that is what the new method returns and it makes sense not to have to cast it
(Also, I'm sorry about the two extra commits in this PR; I'm not sure why they're there …

Fix error resulting from NMS's EntityHuman being moved and renamed

---

src/com/projectkorra/projectkorra/configuration/ConfigManager.java
src/com/projectkorra/projectkorra/earthbending/EarthSmash.java

* Adds new `"Abilities.Earth.EarthSmash.Lift.Knockup"` configuration option to control the velocity applied to players standing where an EarthSmash is created.
* Adds new `"Abilities.Earth.EarthSmash.Lift.Range"` configuration option to control the range in which entities need to be standing in relation to where an EarthSmash is created to get the Knockup applied.
* Fixes players sometimes "falling through" their EarthSmash if they try to create it underneath themselves. Fixes #1120
* Reduces the overall push so it feels more natural.
* Expands the push radius so it can affect entities within one block of the location.

Fix players falling through lifting EarthSmash

---

src/com/projectkorra/projectkorra/command/WhoCommand.java

* Adds vanished player support to the `/pk who <Player>` command. Resolves #1130
* Should work with most common vanishing plugins, tested using Essentials vanish.
* Affects `/pk who` and `/pk who <Player>`.

Add vanish support to the who command

---

src/com/projectkorra/projectkorra/waterbending/WaterSpoutWave.java
src/com/projectkorra/projectkorra/waterbending/combo/IceWave.java

* Fixed IceWave activating when PhaseChange wasn't clicked
* The problem was due to an earlier WaterWave shift up and PhaseChange left click instantiating IceWave even when WaterSpoutWave wasn't active. Adding a check in IceWave's constructor to account for this solves the problem.
* Fixed IceWave users getting stuck on the ice midair
* The ice was being placed faster than the player could move, and when it gets towards the end of the combo (and therefore slower), the ice is being placed right on/beneath the player, so they get stuck. Adding water instead of ice when the player is close enough solves this problem. I chose 1.6 because after testing 2, 1, and 1.5 I found 1.6 to be smooth. It can easily be changed.

Fix IceWave activation and mobility problems

---

src/com/projectkorra/projectkorra/command/DisplayCommand.java

* Fixes passive abilities not being shown by the `/pk display <element>passives` command.
* This issue was caused by unnecessarily filtering out hidden passives.

Fix passives not being shown by display command

---

src/com/projectkorra/projectkorra/configuration/ConfigManager.java
src/com/projectkorra/projectkorra/earthbending/Tremorsense.java

* Adds a new `"Abilities.Earth.Tremorsense.ClickRequiresDarkness"` configuration option to TremorSense allowing the click functionality to be used without needing to be in darkness.
* TremorSense click no longer requires darkness to activate anymore, this change can be reverted using the implemented configuration option.

Add config option to TremorSense click without being in darkness

---

src/com/projectkorra/projectkorra/configuration/ConfigManager.java

* Fixes a typo in the volume and pitch config values for plantbending sounds.
* `"Properties.Water.PlantSound.Volume"` should now work properly.
* `"Properties.Water.PlantSound.Pitch"` should now work properly.

Fix PlantBending volume and pitch config options

---

src/com/projectkorra/projectkorra/PKListener.java
src/com/projectkorra/projectkorra/util/DamageHandler.java

* Fixes AbilityDamageEntityEvent being called unnecessarily
* Fixes ignoreArmor param for `DamageHandler#damageEntity`
* Cleans up `DamageHandler#damageEntity` code

Fix AbilityDamageEntityEvent Being Called Unnecessarily

---

src/com/projectkorra/projectkorra/configuration/ConfigManager.java
src/com/projectkorra/projectkorra/earthbending/EarthTunnel.java
src/com/projectkorra/projectkorra/firebending/FireManipulation.java
src/com/projectkorra/projectkorra/waterbending/blood/Bloodbending.java

- Adds separate revert time for EarthTunnel. In general, on servers, you want a small revert time for arena's, but you can't do that because people get trapped in EarthTunnel in survival because it resets so quickly.
- Fixes cooldown on Bloodbending not activating. The previous implementation would allow a user to constantly spam shift to Bloodbend without going on cooldown.
- Fixes FireManipulation stream cooldown not being applied.

Cooldown bug fixes, earth tunnel revert time

---

.gitignore
pom.xml
src/com/projectkorra/projectkorra/GeneralMethods.java
src/com/projectkorra/projectkorra/PKListener.java
src/com/projectkorra/projectkorra/ability/util/MultiAbilityManager.java
src/com/projectkorra/projectkorra/board/BendingBoard.java
src/com/projectkorra/projectkorra/board/BendingBoardInstance.java
src/com/projectkorra/projectkorra/board/BendingBoardManager.java
src/com/projectkorra/projectkorra/command/BoardCommand.java
src/com/projectkorra/projectkorra/configuration/ConfigManager.java
src/com/projectkorra/projectkorra/event/PlayerBindChangeEvent.java
src/com/projectkorra/projectkorra/waterbending/multiabilities/WaterArmsFreeze.java
src/com/projectkorra/projectkorra/waterbending/multiabilities/WaterArmsSpear.java
src/com/projectkorra/projectkorra/waterbending/multiabilities/WaterArmsWhip.java

* Adds `BendingBoardManager#isDisabled(Player)` to check if a Player has the BendingBoard disabled.
* Adds much needed documentation to BendingBoardManager
* Adds `element` option for the BendingBoard prefix colors
* Fixes board flickering.
* Fixes WaterArms showing up under ice abilities and as an ice ability in some displays
* Changes prefix to have main and alternate color config options for the active and non-active slots respectively
* Changes miscellaneous section to work more effectively.
* Cleans up some SQL statements to follow proper syntax casing conventions.
* Optimizes board code in general.
* Changes `BendingBoardInstance` to `BendingBoard`
* Updates documentation for `BendingBoardManager`
* Merges `BendingBoardManager#toggleBoard(Player)` and …

Improve BendingBoard

---

src/com/projectkorra/projectkorra/chiblocking/RapidPunch.java

* Fixes RapidPunch adding cooldown before it starts. With this fix, addon developers will be able to prevent the ability from getting activated without getting it on cooldown.

Fix RapidPunch adding cooldown before start

---

src/com/projectkorra/projectkorra/PKListener.java
src/com/projectkorra/projectkorra/board/BendingBoard.java
src/com/projectkorra/projectkorra/board/BendingBoardManager.java

* Adds `BendingBoard#show()` to make that bendingboard visible and update it
* Adds `BendingBoard#hide()` to make that bendingboard invisible
* Adds `BendingBoard#destroy()` to unregister the Scoreboard it has (bendingboard object should not be used after destruction, and it's package visibility)
* Adds `BendingBoard#isVisible()` and `BendingBoard#setVisible(boolean)` for more general visibility conditions
* Fixes bending boards toggling on any world switch
* Removes `BendingBoard#disableScoreboard()`, hiding the scoreboard should not delete the bendingboard object

Minor BendingBoard Fixes and Added Methods

---

src/com/projectkorra/projectkorra/ability/ElementalAbility.java
src/com/projectkorra/projectkorra/configuration/ConfigManager.java

Also change to strings for material names in ConfigManager instead of Material values. Adds DIRT_PATH for 1.17+, and leaves GRASS_PATH for 1.16.
Thank you for pointing out the isEmpty issue Emily (https://github.com/emilyy-dev)
If I need to remove the ConfigManager changes to avoid conflicts, let me know.

Remove unneeded check in ElementalAbility

---

src/com/projectkorra/projectkorra/util/ParticleEffect.java

Remove BARRIER ParticleEffect for 1.16, 1.17, and 1.18 compatibility

---

src/com/projectkorra/projectkorra/waterbending/multiabilities/WaterArms.java

* Removed the ``external.contains()`` check from the ``canPlaceBlock()`` method and moved it into ``addBlock()``. This fixes behavior in the ``displayRightArm()`` and ``displayLeftArm()`` where they would sometimes return false when attempting to place a new block over a pre-existing block. This change will fix responsiveness issues that players have been experiencing while using WaterArms Spear or Whip.

Fix for WaterArms responsiveness issues

---

src/com/projectkorra/projectkorra/PKListener.java

* Fixes bug in which someone who is both an earthbender and a waterbender can take fall damage on ice. This was due to some logical flaws in the way fall damage cancellation was handled.
* Fixes #1201

Fix fall damage cancellation logic

---

src/com/projectkorra/projectkorra/configuration/ConfigManager.java
src/com/projectkorra/projectkorra/earthbending/EarthSmash.java
src/com/projectkorra/projectkorra/firebending/FireBlastCharged.java

* Adds minimum and maximum damage values to EarthSmash and ChargedFireBlast, as well as logic to utilize them.
* Adds config options to specify minimum and maximum damage.
This comes from this suggestion: https://discord.com/channels/292809844803502080/752662625984184460/867492947943751740

Add EarthSmash and ChargedFireBlast min/max damage options

---

src/com/projectkorra/projectkorra/ability/FireAbility.java
src/com/projectkorra/projectkorra/firebending/BlazeArc.java

* Fixes Blaze placing Fire blocks in water and potentially other places it should not.
* Resolves issue with `FireAbility#isIgnitable(Block)` where it was not respecting liquids.
* Changes `FireAbility#createFireState(Block, boolean)` to avoid placing floating Soul Fire.
* Now, regular fire side blocks will be placed where a full Soul Fire block cannot be supported from below.

Fix Blaze Fire placement

---

src/com/projectkorra/projectkorra/waterbending/multiabilities/WaterArmsSpear.java

* Fixes WaterArmsSpear spear ice not reverting when the ability ends or the plugin reloads.

Fix WaterArmsSpear Ice not reverting

---

src/com/projectkorra/projectkorra/PKListener.java
src/com/projectkorra/projectkorra/earthbending/Tremorsense.java

- Fixed issue #1010 
- Player breaks the Glowstone, that gets cancelled and the correct block shows up.
- Player breaks the block again, and this time the block get properly broken.
- As an addition, if the player stays within the same X and Z coords, the glowstone doesn't show up. This enables digging straight down without breaking the Glowstone again and again.

Fix TremorSense makes mining faster

---

src/com/projectkorra/projectkorra/configuration/ConfigManager.java
src/com/projectkorra/projectkorra/firebending/lightning/Lightning.java

* Lightning affects entities the same way vanilla lightning affects entities.
* Adds new configurable options to transform all entities (`Abilities.Fire.Lightning.TransformMobs`) and charge creepers (`Abilities.Fire.Lightning.ChargeCreeper`) separately. If TransformMobs is false, but ChargeCreeper is true, only creepers are affected. If TransformMobs is true, but ChargeCreepers is false, only transformable mobs (in addition to turtles) are affected. If both are false, entities are not affected.
* Creepers become charged, villagers turn into witches, pigs turn into zombified piglins, mushroom cows change color variants, and turtles die in one hit and drop bowls
* Lightning conducts copper blocks within a radius specified by the new `Abilities.Fire.Lightning.ConductivityRange` config …

Add Lightning + Copper and Entity interactions

---

src/com/projectkorra/projectkorra/PKListener.java
src/com/projectkorra/projectkorra/earthbending/lava/LavaFlow.java
src/com/projectkorra/projectkorra/firebending/util/FireDamageTimer.java
src/com/projectkorra/projectkorra/util/DamageHandler.java
src/com/projectkorra/projectkorra/util/TempBlock.java

* When dealt fire damage (or lava damage) from TempBlocks that are lava blocks, a FireDamageTimer instance will be created. To do this, you will need to assign an ability whenever you create a new TempBlock (see 3rd point). See LavaFlow changes.
* Proper death message from death by lava from an ability.
* TempBlocks can now have an Ability attached to them (Optional) if needed. Available parameter during object instantiation to add the ability to the TempBlock. Can be accessed through TempBlock#getAbility (this returns an Optional<Ability>, as some TempBlocks may not have an attached ability). Can be useful for developers.
* FireDamageTimer damage no longer does unnecessary knockback.
* DamageHandler now supports sourceless LivingEntity#damage calls. This lets abilities provide damage …

FireDamageTimer can be applied to lava tempblocks

---

src/com/projectkorra/projectkorra/PKListener.java

* Fixes NullPointerException caused by disabling Fire Combos
<html>
<body>
[02:36:58] [Server thread/ERROR]: Could not pass event EntityDeathEvent to ProjectKorra v1.10.2
--
285 | java.lang.NullPointerException: Cannot invoke "com.projectkorra.projectkorra.ability.CoreAbility.getName()" because "fireCombo" is null
286 | at com.projectkorra.projectkorra.PKListener.onEntityDeath(PKListener.java:599) ~[ProjectKorra-1.10.2.jar:?]
287 | at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor146.execute(Unknown Source) ~[?:?]
288 | at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
289 | at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:git-Paper-379]
290 …

Fix PKListener FireCombo Issue

---

src/com/projectkorra/projectkorra/board/BendingBoard.java

* Fixes BendingBoard warning "java.lang.IllegalStateException: Unregistered scoreboard component"
This warning was very common and only needed one condition to be valid for it to screw up someone's bending board and continue throwing the warning for every further combo/misc ability cooldown. It was due to an incorrect linkage of the Optional<BoardSlot> "next" which you can read about on the PK Discord here https://discord.com/channels/292809844803502080/612873490709741577/1055965952677777429. My solution was to add a "prev" so the slots are doubly linked. This is also how @Simplicitee did it in his rework. I have fully tested my changes and have been using this on my server for weeks with no problems.

Fix BendingBoard warning

---

src/com/projectkorra/projectkorra/command/DisplayCommand.java
src/com/projectkorra/projectkorra/command/HelpCommand.java
src/com/projectkorra/projectkorra/configuration/ConfigManager.java

Discord Suggestion for Rewrite of the Command
Including hover text and /help and /display commands being run when clicking various parts of the messages
Video showcasing the changes: https://www.youtube.com/watch?v=3x9bnfx6CTo
Fixes various issues with the Display command
Dealing with the showing and categorizing of combos, sub elements and their combos passives, etc
Removes the need of 2 separate methods for SubElements and normal Elements _and also removes a lot of the original code because its a rewrite lol_

Rewrite Display Command

---

pom.xml
src/com/projectkorra/projectkorra/BendingManager.java
src/com/projectkorra/projectkorra/BendingPlayer.java
src/com/projectkorra/projectkorra/Element.java
src/com/projectkorra/projectkorra/GeneralMethods.java
src/com/projectkorra/projectkorra/OfflineBendingPlayer.java
src/com/projectkorra/projectkorra/PKListener.java
src/com/projectkorra/projectkorra/ProjectKorra.java
src/com/projectkorra/projectkorra/ability/CoreAbility.java
src/com/projectkorra/projectkorra/board/BendingBoard.java
src/com/projectkorra/projectkorra/configuration/ConfigManager.java
src/com/projectkorra/projectkorra/firebending/combustion/Combustion.java
src/com/projectkorra/projectkorra/region/FactionsUUID.java
src/com/projectkorra/projectkorra/region/GriefDefender.java
src/com/projectkorra/projectkorra/region/GriefPrevention.java
src/com/projectkorra/projectkorra/region/LWC.java
src/com/projectkorra/projectkorra/region/Lands.java
src/com/projectkorra/projectkorra/region/RedProtect.java
src/com/projectkorra/projectkorra/region/RegionProtectionBase.java
src/com/projectkorra/projectkorra/region/Residence.java
src/com/projectkorra/projectkorra/region/SaberFactions.java
src/com/projectkorra/projectkorra/region/Towny.java
src/com/projectkorra/projectkorra/region/WorldGuard.java
src/com/projectkorra/projectkorra/util/ChatUtil.java
src/com/projectkorra/projectkorra/util/DamageHandler.java
src/com/projectkorra/projectkorra/util/TempBlock.java
src/com/projectkorra/projectkorra/waterbending/SurgeWall.java
src/com/projectkorra/projectkorra/waterbending/WaterSpoutWave.java
src/com/projectkorra/projectkorra/waterbending/ice/PhaseChange.java
src/staff.txt

Contains the bug fixes:
- Muted paper timing spam
- Fixed BendingBoard slowly disappearing as more combos are used over time
- Fixed Temp Lava not doing damage to entities if it doesn't belong to any ability. (#1280)
- Fixed passives not working in region protection (#1278)
- Fixed dynamic sourcing being weird for left click moves. This would require double clicking for a lot of moves, like RaiseEarth and Torrent. (#1277)
- Fixed OctopusForm ice not reverting if you log out
- Fixed placing blocks in Surge shield (SurgeWall) deleting blocks (#1216)
- Fixed day/night messages being the wrong way around
- Fixed damaging ArmorStands with bending causing errors
- Fixed StackOverFlow when using a certain damageEntity method
- Made Combustion work better when FireGrief is false
- Fixed sourcing …

1.11.2 - More bug fixes

---

src/com/projectkorra/projectkorra/ability/util/MultiAbilityManager.java

> * Adds a new additional constructor to the MultiAbilityInfoSub class with one new ChatColor parameter that allows for the MutliAbilities sub-abilities to have a custom color.
> * Slightly changes the logic inside of the `getAbilityColor()` function to allow for the implementation of the new constructor. My logic is (hopefully) correct so it should have no side effects.
Here is an attached image of this in effect.
My `getMultiAbilities` function looks like this
```java
@Override
public ArrayList<MultiAbilityManager.MultiAbilityInfoSub> getMultiAbilities() {
ArrayList<MultiAbilityManager.MultiAbilityInfoSub> multiAbilityInfoSubs = new ArrayList<>();
multiAbilityInfoSubs.add(new MultiAbilityManager.MultiAbilityInfoSub("Test1", Element.FIRE));
multiAbilityInfoSubs.add(new …
```

Added another constructor to MultiAbilityInfoSub

---

src/com/projectkorra/projectkorra/command/HelpCommand.java

- Adds missing spaces between the ability name and the (Addon Passive) or (Passive)

Add missing space between ability name and <passive / addon passive>

---

src/com/projectkorra/projectkorra/configuration/ConfigManager.java
src/com/projectkorra/projectkorra/waterbending/Torrent.java

* Adds a duration setting to Torrent. Defaults to zero, which is the current behavior of infinite duration. Duration refers to the amount of time water can circle the player before the ability ends. The motivation behind this change is that Torrent allows players to afk at mob grinders by holding down shift or using a weight. Now server owners can limit this if they choose to.

Add duration setting to Torrent

---

src/com/projectkorra/projectkorra/region/RegionProtection.java

* Changes RegionProtection cache cleanup to prevent a potential memory leak on public servers that serve a large number of players. (Dereference players with no cached blocks so that their Map<> can be garbage collected.)
* Changes the logic for getting the player's Map to avoid Null Pointer Exceptions if the cleanup task gets called during the isRegionProtected check.
* I am not a Minecraft developer, these changes were made without testing, do not merge/deploy them solely on the basis of code review.

Addressed potential memory leak in RegionProtection.

---

src/com/projectkorra/projectkorra/BendingManager.java
src/com/projectkorra/projectkorra/BendingPlayer.java
src/com/projectkorra/projectkorra/Element.java
src/com/projectkorra/projectkorra/PKListener.java
src/com/projectkorra/projectkorra/ability/CoreAbility.java
src/com/projectkorra/projectkorra/ability/util/MultiAbilityManager.java
src/com/projectkorra/projectkorra/ability/util/PassiveManager.java
src/com/projectkorra/projectkorra/airbending/AirBlast.java
src/com/projectkorra/projectkorra/airbending/flight/FlightMultiAbility.java
src/com/projectkorra/projectkorra/command/CooldownCommand.java
src/com/projectkorra/projectkorra/configuration/ConfigManager.java
src/com/projectkorra/projectkorra/earthbending/Tremorsense.java
src/com/projectkorra/projectkorra/earthbending/metal/Extraction.java
src/com/projectkorra/projectkorra/firebending/Illumination.java
src/com/projectkorra/projectkorra/region/GriefPrevention.java
src/com/projectkorra/projectkorra/storage/Database.java
src/com/projectkorra/projectkorra/util/DamageHandler.java
src/com/projectkorra/projectkorra/util/TempArmor.java
src/com/projectkorra/projectkorra/util/TempBlock.java
src/com/projectkorra/projectkorra/waterbending/OctopusForm.java
src/com/projectkorra/projectkorra/waterbending/SurgeWall.java
src/com/projectkorra/projectkorra/waterbending/SurgeWave.java
src/com/projectkorra/projectkorra/waterbending/Torrent.java
src/com/projectkorra/projectkorra/waterbending/WaterSpoutWave.java
src/com/projectkorra/projectkorra/waterbending/combo/IceBullet.java
src/com/projectkorra/projectkorra/waterbending/ice/IceBlast.java
src/com/projectkorra/projectkorra/waterbending/ice/IceSpikeBlast.java
src/com/projectkorra/projectkorra/waterbending/ice/PhaseChange.java
src/com/projectkorra/projectkorra/waterbending/multiabilities/WaterArmsFreeze.java
src/com/projectkorra/projectkorra/waterbending/multiabilities/WaterArmsSpear.java

- Fixed Flight not checking perms for the different slot abilities
- Fixed the cooldown command not respecting permissions
- Fixed short_grass material on 1.20.3+
- Fixed illumination digging into the ground in 1.16
- Fixed bending damage that bypasses armor not bypassing protection enchantments
- Fixed TempArmor duping things
- Fixed waterbending ice suffocating players (https://github.com/ProjectKorra/ProjectKorra/issues/1309)
- Fixed IceSpike and IceBlast working when the source is removed before you click
- Fixed Multiability slots not updating when they start/end
- Fixed Extraction turning deepslate ores into stone when used
- Fixed MythicLib causing you to use abilities when mobs are hit
- Fixed passives being toggled with bending when Properties.TogglePassivesWithAllBending is …

1.11.3 Fixes + TempBlock Optimization

---

core/src/com/projectkorra/projectkorra/configuration/ConfigManager.java
core/src/com/projectkorra/projectkorra/earthbending/metal/Extraction.java
core/src/com/projectkorra/projectkorra/earthbending/metal/MetalClips.java
core/src/com/projectkorra/projectkorra/waterbending/SurgeWall.java
core/src/com/projectkorra/projectkorra/waterbending/SurgeWave.java

> Part One here: https://github.com/ProjectKorra/ProjectKorra/pull/1329
- Surge bubble particles. ***Suggested by member: `.blackxlight`***
- When `SurgeWave` or `SurgeWall` interacts with water blocks (e.g., if used underwater), bubble particles are displayed--similarly to `Torrent` and `WaterManipulation`.
- `MetalClips`' shoot speed and cooldown can be configurable now. ***Suggested by member: `.blackxlight`***
- `SurgeWall` select range configurability. ***Suggested by member: `prusakovaleksandr`***
- `Extraction` viability on **IRON GOLEMS**. ***Suggested by member: `.blackxlight`***
- `Extraction` drops **IRON NUGGETS** when used on **IRON GOLEMS**. Players may configure the amount dropped in the config.
> [!NOTE]
> *Will manually resolve merge conflicts from either pull request …

Implementing suggestions 2: Surge bubble particles, configuration, Extraction iron golem viability

---

core/src/com/projectkorra/projectkorra/GeneralMethods.java
core/src/com/projectkorra/projectkorra/PKListener.java
core/src/com/projectkorra/projectkorra/ability/AvatarAbility.java
core/src/com/projectkorra/projectkorra/ability/EarthAbility.java
core/src/com/projectkorra/projectkorra/ability/ElementalAbility.java
core/src/com/projectkorra/projectkorra/ability/FireAbility.java
core/src/com/projectkorra/projectkorra/ability/WaterAbility.java
core/src/com/projectkorra/projectkorra/configuration/ConfigManager.java
core/src/com/projectkorra/projectkorra/firebending/FireBlast.java
core/src/com/projectkorra/projectkorra/firebending/FireBlastCharged.java
core/src/com/projectkorra/projectkorra/firebending/FireManipulation.java
core/src/com/projectkorra/projectkorra/firebending/FireShield.java
core/src/com/projectkorra/projectkorra/firebending/HeatControl.java
core/src/com/projectkorra/projectkorra/firebending/WallOfFire.java
core/src/com/projectkorra/projectkorra/firebending/combo/FireComboStream.java
core/src/com/projectkorra/projectkorra/util/BlockSource.java
core/src/com/projectkorra/projectkorra/waterbending/OctopusForm.java
core/src/com/projectkorra/projectkorra/waterbending/SurgeWall.java
core/src/com/projectkorra/projectkorra/waterbending/SurgeWave.java
core/src/com/projectkorra/projectkorra/waterbending/Torrent.java
core/src/com/projectkorra/projectkorra/waterbending/WaterManipulation.java
core/src/com/projectkorra/projectkorra/waterbending/WaterSpoutWave.java
core/src/com/projectkorra/projectkorra/waterbending/ice/IceSpikeBlast.java
core/src/com/projectkorra/projectkorra/waterbending/multiabilities/WaterArms.java
core/src/com/projectkorra/projectkorra/waterbending/multiabilities/WaterArmsFreeze.java
core/src/com/projectkorra/projectkorra/waterbending/multiabilities/WaterArmsWhip.java

Implementing suggestions from Discord.
* Added mudbending viability for waterbending and earthbending. ***Suggested by member: `.pan_daniel`***
- ProjectKorra water abilities that use mud as a source will turn them into dirt (muddy mangrove roots turn to mangrove roots) upon activation.
- Mudbending sounds, configurable:
-  Earthbenders hear `BLOCK_MUD_PLACE`; `EarthAbility.playMudbendingSound()` plays this sound. 
- Waterbenders hear `BLOCK_MUD_STEP`; `WaterAbility.playMudbendingSound()` plays this sound.
* AvatarState sound change. ***Suggested by member `cinchedlibra` and `manuel04_`***
- Changed sound from `BLOCK_ANVIL_FALL` to `BLOCK_BEACON_POWER_SELECT`.
* Food dropped by mobs is cooked when killed by firebending. ***Suggested by member: `novatitan_`***
* Waterbenders can use wet …

Implementing suggestions: Mudbending viability, AvatarState sound change, cooking food with fire, using and drying sponges, WaterArms action bar

---

core/src/com/projectkorra/projectkorra/OfflineBendingPlayer.java
core/src/com/projectkorra/projectkorra/PKListener.java
core/src/com/projectkorra/projectkorra/airbending/AirBurst.java
core/src/com/projectkorra/projectkorra/airbending/AirShield.java
core/src/com/projectkorra/projectkorra/airbending/Suffocate.java
core/src/com/projectkorra/projectkorra/airbending/Tornado.java
core/src/com/projectkorra/projectkorra/command/TempCommand.java
core/src/com/projectkorra/projectkorra/configuration/ConfigManager.java
core/src/com/projectkorra/projectkorra/earthbending/Tremorsense.java
core/src/com/projectkorra/projectkorra/event/BendingPlayerLoadEvent.java
core/src/com/projectkorra/projectkorra/event/PlayerChangeElementEvent.java
core/src/com/projectkorra/projectkorra/event/PlayerChangeSubElementEvent.java
core/src/com/projectkorra/projectkorra/firebending/FireBurst.java
core/src/com/projectkorra/projectkorra/firebending/WallOfFire.java
core/src/com/projectkorra/projectkorra/firebending/combo/FireComboStream.java
core/src/com/projectkorra/projectkorra/firebending/combo/FireKick.java
core/src/com/projectkorra/projectkorra/hooks/PlaceholderAPIHook.java
core/src/com/projectkorra/projectkorra/util/ChatUtil.java

- Added insurance for getting an OfflineBendingPlayer while it is already loading
- Added PAPI `%projectkorra_element_prefix%` placeholder. Uses the defined prefixes from the language.yml
- Updated ProjectKorra's PAPI expansion to use the latest PAPI API
- Tweaked some language config stuff related to temp elements
- BendingPlayerLoadEvent is now thrown when a player joins the server and their data is converted from an OfflineBendingPlayer to BendingPlayer
- Fixed race condition for saving temp elements
- Fixed some PK events not working async
- Fixed ChatUtil outputting md5 component spam when sending to console
- Fixed remaining issues with the temp command
- Fixed AvatarState's default potion effects being unremovable from the config
- Fixed AirBurst cone not applying cooldown
- Fixed …

Final 1.12.0

---

core/src/com/projectkorra/projectkorra/command/ChooseCommand.java

* Bug where /pk ch avatar wouldn't add subelements of elements
* Line 190 | Changed the inner loop for getting subelements of an element.
> * For the line `for (final SubElement sub : Element.getSubElements(e))`,(previous version: `for (final SubElement sub : Element.getSubElements(element))`, the getSubElements method would take the Element object outside of the for loop instead of the one needed in the outer for loop `for (Element e : new Element[] {Element.AIR, Element.EARTH, Element.FIRE, Element.WATER})`

Fix /b ch SubElements for Avatar

---

core/src/com/projectkorra/projectkorra/configuration/ConfigManager.java
core/src/com/projectkorra/projectkorra/waterbending/ice/IceBlast.java
core/src/com/projectkorra/projectkorra/waterbending/ice/IceSpikeBlast.java

This bug prevents damage from being applied consistently when using IceSpikeBlast and IceBlast. When a player is hit with IceSpikeBlast or IceBlast during the `bPlayer.slow(slowCooldown)`  the attack wouldnt pass through the `if(bPlayer.canBeSlowed())` check where the damage command for players is located.
* Adds a SlowCooldown parameter to the config under "Abilities.Water.IceBlast.SlowCooldown".
* IceBlast uses new SlowCooldown parameter.
* Line 98 IceSpikeBlast
> * Moves damage out of the `canBeSlowed()` check.
* Line 165 IceBlast
> * Moves damage out of the `canBeSlowed()` check.
* Line 99 IceSpikeBlast
> * Removes recasting of entity to get the bending player. Now uses the same method as IceSpikePillar to get the bending player.

Ice damage not being applied during slow cooldown

---

core/src/com/projectkorra/projectkorra/command/PresetCommand.java
core/src/com/projectkorra/projectkorra/configuration/ConfigManager.java
core/src/com/projectkorra/projectkorra/object/Preset.java
core/src/plugin.yml

* Added methods to serialize (exportToString) and deserialize (importFromString) presets.
* Added export and import subcommands (with aliases) to PresetCommand; with a use case in mind for easily moving presets across servers, or not completely losing configurations due to low max preset limits.

Preset Command Additions (Import/Export)
